### ISSUE TITLE
Out of sync with local time zone

### ISSUE THREAD

**Issue by bbbe-me** [juanfont/headscale#1000]
I found a serious problem, the time zone displayed by headscale is completely wrong

Use latest version of headscale v0.17.0-beta4 and latest version of tailscale linux client

As shown in the picture, you can observe the last seen update of the client for ten seconds

<img width="893" alt="time" src="https://user-images.githubusercontent.com/59217495/203090386-7bebbcc8-8bae-4f3c-af67-7827193826e1.png">

But it is several hours different from the local time. I am in China, and the server and client where headscale is located are in China's time zone.

Googled the headscale and the time displayed should be British time

How should I set the time zone, there is no option to customize the time zone in the configuration file

**Comment by alexbathome** [comment]
The time you are seeing here is the date in [UTC or Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time), which is pretty much the de-facto timezone used in computing, it keeps things uniform :D

You should be able to confirm this by running `date --utc` and matching it up with the date time that headscale is returning. 

I hope that helps :)
