### ISSUE TITLE
Hide other namespaces

### ISSUE THREAD

**Issue by 12nick12** [juanfont/headscale#1026]
I would love to be able to hide other namespaces. I know we can limit access, but my thinking was I have my namespace which is able to see namespaces related to me, but if I have one for my brother and his friends to game I don't want them to be able to see my hosts.

**Comment by 12nick12** [comment]
Once again looks like I need to read more. I got it. Thanks.

**Comment by whao** [comment]
@12nick12 Hello, I wonder how you solved this if I may ask :)
