### ISSUE TITLE
Magic DNS and AAAA records pointing at IPv6 addresses of nodes in dual-stack tailnet

### ISSUE THREAD

**Issue by almereyda** [juanfont/headscale#1027]
**Issue description**

When connecting to a dual stack tailnet, only A records of nodes are resolved via Magic DNS.

**To Reproduce**

1. `dig +short A node1.ns.headscale.fqdn`
2. `dig +short AAAA node1.ns.headscale.fqdn`

**Context info**

This sounds as if it is related to:

- #295 

The nodes list also only displays the IPv6 address in the first column.

It is possible to ping the displayed IPv6 address, and it is possible to retrieve the IPv4 address via Magic DNS.

Ideally, both of these functionalities (display + DNS) could support dual stack mode more completely.

- Version of headscale used: `latest`
- Version of tailscale client: `1.32.3`
- Linux Ubuntu 22.04
- Kernel 5.15.0-53-generic

**Comment by juanfont** [comment]
I am afraid we depend on upstream for this one. Please have a look to https://github.com/tailscale/tailscale/issues/1152

**Comment by almereyda** [comment]
Pardon me for not finding that, and thanks for the link.
