### ISSUE TITLE
Webpage not reachable via port 8080 when using docker

### ISSUE THREAD

**Issue by frakman1** [juanfont/headscale#1029]
**Bug description**

I tried following the documentation here:
https://github.com/juanfont/headscale/blob/main/docs/running-headscale-container.md

I got the template config file as described (no changes) and created the `db.sqlite` file then executed the `docker run` command. The container ran without errors but attempting to access the page via port 8080 failed.
I tried `127.0.01:8080` and `local-ip:8080` with no luck.

I originally tried the syntax publishing `127.0.0.1:8080` before trying `0.0.0.0:8080` as per the documentation.

I also tried this on a Mac, Ubuntu and finally on Kali before giving up.

**To Reproduce**

**Context info**

- Version of headscale used: `0.17.0`
- Version of tailscale client: `Not Used`
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) `Kali 2021.3`
- Kernel version: `Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux`
- The relevant config parameters you used. `See output below:`
- Log output:

```

└─$ docker run   --name headscale   --detach   --volume $(pwd)/config:/etc/headscale/   --publish 0.0.0.0:8080:8080   --publish 127.0.0.1:9090:9090   headscale/headscale:latest   headscale serve
b550a1b4e30208e5b4424d5ed9146c9d9f65b72cf40db9af4aa9fbbafb2baa7e

└─$ docker logs headscale                                                                                                                                                                                                   125 ⨯
2022-11-30T14:38:54Z INF Setting up a DERPMap update worker frequency=86400000
2022-11-30T14:38:54Z INF listening and serving HTTP on: 127.0.0.1:8080
2022-11-30T14:38:54Z INF listening and serving metrics on: 127.0.0.1:9090

└─$ telnet 127.0.0.1 8080
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.

└─$ curl http://127.0.0.1:9090/metrics                                                                                                                                                                                        1 ⨯

curl: (56) Recv failure: Connection reset by peer

└─$ curl http://127.0.0.1:8080                                                                                                                                                                                               56 ⨯

curl: (56) Recv failure: Connection reset by peer


└── config
    ├── config.yaml
    ├── db.sqlite
    ├── noise_private.key
    └── private.key
```

**Comment by kradalby** [comment]
We do not really support docker, please ask the community in Discord.

**Comment by frakman1** [comment]
I did, twice and got no response but thanks.

**Comment by frakman1** [comment]
Thank you. 
I got further but ran into this error when trying to do the `tailscale up --login-server xxx ` from a node machine.
Logs below are from a Raspberry Pi running latest version of tailscale 1.46.0
Also using latest headscale docker image.
Same result when running from MacOS using latest version 1.44.0 from App Store  `/Applications/Tailscale.app/Contents/MacOS/Tailscale up --login-server xxx`

Basically complaining about an unsupported protocol scheme.

```
tailscaled[9289]: Start
tailscaled[9289]: control: client.Shutdown()
tailscaled[9289]: control: client.Shutdown: inSendStatus=0
tailscaled[9289]: control: mapRoutine: quit
tailscaled[9289]: control: Client.Shutdown done.
tailscaled[9289]: Backend: logs: be:a0eb62d4b30fd996a4b46ff050db3cdb4510b8f315ed005623d77e34eebe69f4 fe:
tailscaled[9289]: Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
tailscaled[9289]: blockEngineUpdates(true)
tailscaled[9289]: Reconfig(down): no changes made to Engine config
tailscaled[9289]: StartLoginInteractive: url=false
tailscaled[9289]: control: client.Login(false, 2)
tailscaled[9289]: control: LoginInteractive -> regen=true
tailscaled[9289]: control: doLogin(regen=true, hasUrl=false)
tailscaled[9289]: Received error: fetch control key: Get "192.168.86.145/key?v=65": unsupported protocol scheme ""
```
@Orhideous
