### ISSUE TITLE
Unable to join Headscale server, machine IP seems to be empty

### ISSUE THREAD

**Issue by maddie** [juanfont/headscale#104]
Using Tailscale v1.14.0 here, and when I try to join the network, `tailscale up` hangs and logs printed by `headscale`:

```
Sep 06 06:38:42 headscale headscale[51960]: [GIN] 2021/09/06 - 06:38:42 | 500 |    6.694432ms | 192.168.103.253 | POST     "/machine/8220a4cce5513fc662404da43020abe2eabc3def64d5f38a362b60689466a51d/map"
Sep 06 06:39:01 headscale headscale[51960]: 2021-09-06T06:39:01Z ERR Cannot convert to node error="netaddr.ParseIPPrefix(\"/32\"): ParseIP(\"\"): unable to parse IP" func=getMapResponse
Sep 06 06:39:01 headscale headscale[51960]: 2021-09-06T06:39:01Z ERR Failed to get Map response error="netaddr.ParseIPPrefix(\"/32\"): ParseIP(\"\"): unable to parse IP" handler=PollNetMap id=8220a4cce5513fc662404da43020abe2eabc3def64d5f38a362b60689466a51d machine=test_machine
```

It seems that headscale fails to get the machine IP here:

https://github.com/juanfont/headscale/blob/123f0fa18516e812ff19ff069d5fb5544768d46c/machine.go#L80

Any pointers?

**Comment by juanfont** [comment]
Are you still having this issue? Where you connected to the official Tailscale.com service in that machine before?

**Comment by juanfont** [comment]
Ok. Gonna close this due to inactivity... Let us know if you still face the problem.

**Comment by maddie** [comment]
Sorry, been busy.. I'll test again when I have time, and re-open if there's still issue.

FWIW the node was a freshly installed Ubuntu 20.04 and Tailscale.

**Comment by diseq** [comment]
The root cause is an expired pre-auth key.
@juanfont @maddie
