### ISSUE TITLE
the same server,client 1.34.0 fail register. but client 1.24.2-dev success.

### ISSUE THREAD

**Issue by jerrell851** [juanfont/headscale#1056]
- Version of headscale used:v0.18.0-beta1
- Version of tailscale client:1.34.0
  tailscale commit: bb6e746f335b45c0b103345c88a8ba9e0fba0e1a
  other commit: 8d1edab6f4eb0c28a9e64f7919b7e19a24beaa57
  go version: go1.19.2-ts3fd24dee31

- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version:Linux
- Kernel version:5.4.164
- Log output:

tailscale status
# Health check:
#     - not logged in, last login error=register request: Post "https://[hidden]/machine/register": all connection attempts failed (HTTP: unexpected HTTP response: 404 Not Found, HTTPS: unexpected HTTP response: 404 Not Found)

* For safety, the domain name is erased

**Comment by kradalby** [comment]
Please post information on how to reproduce, this is to vague.

**Comment by juanfont** [comment]
Closing it. Please add more details if you want to reopen it.
