### ISSUE TITLE
Usage with Tailscale on MacOS

### ISSUE THREAD

**Issue by projx** [juanfont/headscale#106]
Hey

Could add some clue how to use this with the MacOS TailScale client? It seems the GUI client needs to be loaded and logged in before I can use the CLI command, but then this mean I cannot run the following, as it is already authenticated to TailScales hosted controller.

/Applications/Tailscale.app/Contents/MacOS/Tailscale up -login-server <> --authkey <KEY>

If I run the following, it forces the client to logout, but it doesn't reconnect:

/Applications/Tailscale.app/Contents/MacOS/Tailscale up -login-server <> --authkey <KEY> --reset --force-reauth

Thank you

**Comment by kradalby** [comment]
Hi @projx, to get it working on my machine, I would:

1. Start the UI client (but _not_ log in)
2. `/Applications/Tailscale.app/Contents/MacOS/Tailscale up -login-server https://headscale.example.no --accept-routes --authkey $KEY`

This seem to work for me without having to force a reauth, I have _never_ logged in with the official Tailscale service. You might be able to get all of that deleted so its fresh.

Whenever I reboot, I usually need to run `/Applications/Tailscale.app/Contents/MacOS/Tailscale up -login-server https://headscale.example.no`

**Comment by kradalby** [comment]
For the brave, have a look at #113 and you can generate a profile that overrides the default login server. Currently macOS works and it allows you to not have to fiddle with the command line.

**Comment by kradalby** [comment]
I have updated #113 with more details on setting up macOS. Feedback would be appreciated.
