### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Frankzhang854** [juanfont/headscale#1060]
Excuse me, the old version cannot be installed with the new configuration file, but the old configuration file can be installed and connected to the client. Is there any change in the new version of the configuration file and the installation method of the installation package? Thank you

**Issue description**

**To Reproduce**

**Context info**

**Comment by sachinshakya507** [comment]
I got following issue while installing
$headscale serve
/usr/local/bin/headscale: line 8: syntax error near unexpected token `newline'
/usr/local/bin/headscale: line 8: `<!DOCTYPE html>'

**Comment by juanfont** [comment]
Please always check our release notes. Any breaking change in the config is reported there.

**Comment by Frankzhang854** [comment]
Excuse me, is there any difference between the installation method and the previous one?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Juan ***@***.***&gt;; 
发送时间: 2023年1月1日(星期天) 晚上8:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [juanfont/headscale] Unable to install (Issue #1060)






请随时查看我们的发行说明。配置中的任何破坏性更改都会在此报告。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.

**Comment by Frankzhang854** [comment]
Please ask, the same configuration file, and the client version remains unchanged, headscale_0.18.0-beta2 cannot open the exit node, but headscale_0.18.0-beta1 can open the exit node, thank you
My English is very bad, please forgive me




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juanfont/headscale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juanfont/headscale] Unable to install (Issue #1060)





 
./ is the current dir as a relative path.
 Sockets usually fo into /run, but you are free to do as you see fit.

**Comment by Frankzhang854** [comment]
Please ask, the same configuration file, and the client version remains unchanged, headscale_0.18.0-beta2 cannot open the exit node, but headscale_0.18.0-beta1 can open the exit node, thank you
My English is very bad, please forgive me







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juanfont/headscale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juanfont/headscale] Unable to install (Issue #1060)





 
./ is the current dir as a relative path.
 Sockets usually fo into /run, but you are free to do as you see fit.

**Comment by Frankzhang854** [comment]
But if you don't modify it, headscale can't run. I don't know where my installation method is wrong.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juanfont/headscale"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 晚上7:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juanfont/headscale] Unable to install (Issue #1060)





 
./ is the current dir as a relative path.
 Sockets usually fo into /run, but you are free to do as you see fit.
