### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by magkopian** [juanfont/headscale#1073]
Hello,

I stumbled upon issue #310 while I was trying to figure out how I could donate to the project. But, I couldn't find any sponsor button in the repo. Then after some digging I found commit fc4361b225a14b3973f6d38cd1558f5abcabe22b which made clear what the issue was.

So, since the sponsor button no longer exists, I was curious if there were any other ways of donating to the project.

Thank you for all your hard work!

Edit: I didn't mean to add a `bug` label to this. No sure how it happened and I can't figure out how to remove it.

**Comment by juanfont** [comment]
Hi @magkopian, we have reconsidered this and we added a link to https://ko-fi.com/headscale in the project page.

Thanks!

**Comment by magkopian** [comment]
Great, thank you! I just made a small contribution.

**Comment by juanfont** [comment]
Thank you very much!!

**Comment by 0xb1b1** [comment]
Hi! It'd be nice if you had cryptocurrency donation options @juanfont ! Is it possible?
