### ISSUE TITLE
tailscale  1.34.1 can't login to headscale 0.17.1

### ISSUE THREAD

**Issue by linxd** [juanfont/headscale#1084]
I update the docker image up to 0.17.1, and update the tailscale client version to 1.34.1 ,
but the node can't ping the other node, and can't login to the server.

centos:  
  headscale +UI
windows client or centos client 1.34.1

**Comment by ulikoehler** [comment]
I am using Tailscale 1.34.1 and Headscale 0.17.1 via docker and everything works fine for me. What I haven't tried with these specific versions, is logging in a new node (tailscale up).
