### ISSUE TITLE
Remove ephemeral nodes immediately upon logout

### ISSUE THREAD

**Issue by noax** [juanfont/headscale#1087]
**Feature request**

A few months ago, Tailscale changed the way ephemeral nodes are handled during logout. https://tailscale.com/blog/ephemeral-logout/

It would be great if headscale could do the same and remove nodes immediately after a `tailscale logout`.

Best regards, 
Jakob

**Comment by noax** [comment]
Thank you very much, works like a charm 🙂

**Comment by juanfont** [comment]
Fantastic! Thanks :)
