### ISSUE TITLE
Headscale tab completion funky behaviour

### ISSUE THREAD

**Issue by aevans1987** [juanfont/headscale#1092]
Hitting tab for auto completion on a command like:

`headscale nodes list`

Presents an output like this:
![image](https://user-images.githubusercontent.com/23514631/209243887-380ceda5-f7c6-46a3-8a68-848f07da1591.png)

Obviously there is no completion for that command, but still a funky behavior.

**Comment by Schokobecher** [comment]
Pretty sure this is an issue with your local zsh install or one of the installed plugins (possibly using Oh my Zsh?). By 'default' (Ubuntu 22.04.1 LTS, bash here), there is simply no tab completion for the headscale command.

**Comment by aevans1987** [comment]
Nope, I use Bash and have setup Autocompletion via Headscale command.

**Comment by aevans1987** [comment]
Should note, this does not occur when there is options that completion would be able to offer
