### ISSUE TITLE
Could not load DERP servers map file error on Ubuntu 20.04

### ISSUE THREAD

**Issue by woudsma** [juanfont/headscale#110]
I'm trying to get headscale to work, but I'm stuck over this error.

```
$ docker run -v $(pwd)/private.key:/private.key -v $(pwd)/config.json:/config.json -v $(pwd)/derb.yaml:/derb.yaml -p 127.0.0.1:8080:8080 headscale/headscale headscale serve
  2021-09-18T10:19:24Z ERR Could not load DERP servers map file error="open : no such file or directory" path=
  2021/09/18 10:19:24 Error initializing: ephemeral_node_inactivity_timeout () is set too low, must be more than 1m5s
```

Running `headscale namespaces create $NAMESPACE` results in the same error.
I've tried both the binary and Docker, but both seem to be stuck.

When entering the Docker container with `docker run --rm -it -v $(pwd):/root headscale/headscale sh` and running `headscale` I see the command executes fine, and `headscale version` returns `dev`. Still I cannot create a namespace or start the server.

**Comment by sigio** [comment]
derb vs derp ?

**Comment by woudsma** [comment]
The command from the README says derb.yml, but now I see that the parameter should be derp.yml. (I've also created a PR for another typo).
https://github.com/juanfont/headscale/blame/main/README.md#L86

Still no luck though. I'm always getting the same error, both when trying to create a namespace and when trying `headscale serve`

```
2021-09-19T14:23:00Z ERR Could not load DERP servers map file error="open : no such file or directory" path=
2021/09/19 14:23:00 Error initializing: ephemeral_node_inactivity_timeout () is set too low, must be more than 1m5s
```

**Comment by mannp** [comment]
Try just /derp.yaml pointing to your locally stored derp.yaml.

The docs didn't work for me, but /derp.yaml did.

**Comment by juanfont** [comment]
Typo in readme fixed!
