### ISSUE TITLE
Nologin is on a different path in Debian and derivatives

### ISSUE THREAD

**Issue by murtezayesil** [juanfont/headscale#1142]
`nologin` is at `/usr/sbin/nologin` in Debian/Ubuntu and their derivatives. Running the code for creating a headscale user without knowing requires us to later editing `/etc/passwd` which is never advised to edit directly.

Please add a note for Debian/Ubuntu in 3rd step for Running Headscale on Linux.

Here is an example:
<details><summary>❗Debian/Ubuntu users should run</summary>

```bash
   useradd \
	--create-home \
	--home-dir /var/lib/headscale/ \
	--system \
	--user-group \
	--shell /usr/sbin/nologin \
	headscale
```

</details>

Here is how the example is implemented:
```
<details><summary>❗Debian/Ubuntu users should run</summary>

<code>
   useradd \
	--create-home \
	--home-dir /var/lib/headscale/ \
	--system \
	--user-group \
	--shell /usr/sbin/nologin \
	headscale
</code>
</details>
```

Thanks and have a great day.

**Comment by damianb** [comment]
`/sbin` is retained as a symlink on Debian 11 and I believe the same is on Ubuntu 22.04; not sure about Ubuntu 22.10, I don't have a deployment of that anywhere.

Is there any indication that Debian and its derivatives are dropping the symlink anytime soon?  If not, this isn't an issue, as specifying a symlinked location as the shell for a user still works as expected; you can test this with `sudo -iu $username` when the shell is set to `/sbin/nologin`.

**Comment by murtezayesil** [comment]
In my recent try, I had some trouble during installation. After checking what could be the culprit, I landed on there being 2 paths for nologin. I was wrong. Have a great day.
