### ISSUE TITLE
Support install headscale with helm to kubernetes cluster

### ISSUE THREAD

**Issue by willzhang** [juanfont/headscale#1153]
**Feature request**

Support install headscale with helm to kubernetes cluster. kubernetes is easy to install 、manage and scale application.

**Comment by kradalby** [comment]
Hi

We will not support this as it is too much for us to maintain, we only support the binary install. We are happy to review and have people contribute community supported configuration: https://github.com/juanfont/headscale/tree/main/docs/examples
