### ISSUE TITLE
Have to reconnect Tailscale on Android now and then to resolve custom DNS records

### ISSUE THREAD

**Issue by zebhlindqvist** [juanfont/headscale#1155]
When custom DNS records was added to 0.18.0, I moved my DNS records from my domain DNS to the new extra_records section.
The DNS records point towards Headscale client IPs.

When I used my domain DNS, everything worked fine, but since I moved the records to the extra_records section, I have to reconnect a few times a day in as the DNS records stops resolving.

It often happens when connecting/disconnecting WiFi. Sometimes it will work after a while, but it usually won't.

To reproduce:
1. Add some records to the extra_records section
2. Connect Tailscale Android
3. Connect/disconnect WIFI
4. Try to resolve DNS records
5. Repeat step 3-4 a few times if step 4 doesn't fail

- Headscale 0.18.0
- Tailscale client 1.34.2
- Android 13

**Comment by omernaveedxyz** [comment]
Perhaps you're having the same issue as mentioned [here](https://github.com/tailscale/tailscale/issues/5783)?

If so, the solution for me has been to enable override_local_dns and specify nameservers.
