### ISSUE TITLE
Enable taildrop support from headscale?

### ISSUE THREAD

**Issue by mannp** [juanfont/headscale#118]
Hi

I wondered if it would be possible to enable taildrop support from within headscale at all?

Cheers

**Comment by russkel** [comment]
More information here:
https://tailscale.com/blog/2021-06-taildrop-was-easy/

Looks like a useful addition.

**Comment by juanfont** [comment]
Just landed in v0.9.1 https://github.com/juanfont/headscale/releases/tag/v0.9.1

Cheers!

**Comment by mannp** [comment]
> Just landed in v0.9.1 https://github.com/juanfont/headscale/releases/tag/v0.9.1
> 
> Cheers!

Thanks for the very prompt implementation :) is taildrop enabled automatically, or needs a env or config setting ro enable like it does in tailscale?

Cheers

**Comment by juanfont** [comment]
Automatically enabled. Actually, hardcoded 😅

**Comment by mannp** [comment]
Thanks for the quick clarification 👍🏻 presume its selectable in tailscale as its currently showing as an alpha grade feature .... likely you know its good, but might be worth a switch until its final code in tailscale....just a thought :-)
