### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by pkpowell** [juanfont/headscale#119]
Is it possible to connect to multiple servers?
I just set up 2 offering different subnets, but can only connect to one at a time.

**Comment by juanfont** [comment]
I am a bit confused. Do you want to have multiple namespaces? Or multiple subnets exposed from the same server?

**Comment by allastornin** [comment]
Perhaps this is what I mean - https://tailscale.com/kb/1115/subnet-failover/

I am also interested in this functionality.

**Comment by pkpowell** [comment]
What I meant was can I connect a single machine to multiple login servers with their own namespaces and subnets.
atm tailscaled seems to only create one utun interface at a time, so I can't simultaneously connect to say 100.90.0.0/20 and 100.70.0.0/24 hosted on separate headscale servers.
Use case would be either failover or separating office and test networks.

**Comment by kradalby** [comment]
I dont think the upstream tailscale client supports multiple servers. So for now, this is a no.

**Comment by pkpowell** [comment]
Ok, thanks.
