### ISSUE TITLE
Is it possible to host headscale on serverless platforms?

### ISSUE THREAD

**Issue by lyc8503** [juanfont/headscale#1215]
**Feature request**

There're many cloud platforms providing serverless app hosting. Tailscale client can [be deployed to many of them](https://tailscale.com/kb/integrations/serverless/). 

I am wondering if a headscale server could be deployed to some serverless platforms so that we don't need to maintain infrastructure by ourselves and maybe reduce costs by a VPS? 

Is that possbile **in theory**? Is headscale now handling requests seperately and don't rely on memory to keep states? (since PaaS may not share memory data between different requests, and variables in memory do not persist.)

If it's possible, I may try to migrate it to some of serverless platforms and have a PR on documents. Thanks!

**Comment by juanfont** [comment]
Hi @lyc8503, Headscale requires active connections to their managed nodes. I recommend you looking at something like Scaleway's Stardust instances https://www.scaleway.com/en/stardust-instances/, that should be enough to host headscale for ~100 nodes.

**Comment by lyc8503** [comment]
OK, thanks a lot for your explanation & recommendation!

**Comment by allamedo** [comment]
Some guy has migrated its headscale instance to fly.io here: https://github.com/cloudflare/cloudflared/issues/990#issuecomment-1911471373

**Comment by lyc8503** [comment]
I have been using Scaleway Stardust, working so well for me for a long time.
