### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Norodix** [juanfont/headscale#1217]
**Issue description**

I really like this software! I just set up it on my VPS and I would like to give some feedback on the installation instructions. Issues I ran into that were not very obvious from the documentation.

**To Reproduce**

Install headscale on linux following the docs.

**Context info**

I love the software, and I hope I can help with this feedback.

### File permissions not explained

I think it is not unreasonable to think someone with little to no linux experience would try to set up their own VPN. The docs dont go into detail with what the file permissions need to look like. There is mention of running it with a headscale user but not that this user needs to be able to write to some dirs and read others. Should the config files under /etc be read-only, belong to root or headscale, etc. I think it might be worth mentioning what it should look like.

### Running from the same directory

This might be a bug, but when I started headscale for the first time from the command line, in the new terminal I could not list the users. I could wget the metrics as shown in the docs but I had to cd to `/etc/headscale` to be able to `headscale users list`. If it is not a bug, it should be mentioned explicitly.

### Systemd not printing all errors.

This might be a bug, but when I ran headscale as a systemd service it could not start but in the status it did not show the errors. I had to run it with headscale user to see that I had some permission errors. I dont know why it was not printed to systemd's status.

### Some files need to be created manually

Some files like `/var/run/headscale/headscale.sock` need to be created manually. It is not created by headscale if it does not exist. It might be better to explicitly mention it in the docs.

### How to keep up-to-date

I dont see any mention in the docs how to upgrade between version of headscale. Given how fast it is developed it might be a good idea to add a short guide. I assume back up stuff, replace bin, run again, but I am just guessing.

**Comment by kradalby** [comment]
Hi, it would be great if you could help improve the docs with your feedback :), we are very happy for pull requests to update the docs!

Thanks

**Comment by Norodix** [comment]
I'm happy to do so but to be perfectly honest I'm not sure about some of the points. Should I just create  PR for the ones I'm confident about and leave this issue up for the rest?

**Comment by kradalby** [comment]
Yes that’s better than the current state :) Sent from Proton Mail for iOS On Sat, Feb 18, 2023 at 14:13, Norodix ***@***.***> wrote:  
I'm happy to do so but to be perfectly honest I'm not sure about some of the points. Should I just create  PR for the ones I'm confident about and leave this issue up for the rest?

**Comment by Norodix** [comment]
I opened a PR.

The only missing thing that I found is the general description on how to update headscale when a new version comes out. I'm curious about that myself.

**Comment by Pr0pHesyer** [comment]
It doesn't create `/var/run/headscale/headscale.sock` in 0.22.3 deb still,doc has no more information.
Is it need to fix?
