### ISSUE TITLE
Deleting a node does not delete the associated route entry (v0.20.0)

### ISSUE THREAD

**Issue by NetworkEngineer509** [juanfont/headscale#1228]
**Bug description**
Deleting a node does not delete the associated route entry

**To Reproduce**

1. Register a node with an advertised route
2. Delete the node manually via headscale cli
3. Check the routes, you will see the entry is still there, but the name is blank

**Context info**
- Version of headscale used: v0.20.0

Here is the output of headscale route list showing the issue
![image](https://user-images.githubusercontent.com/34389163/221382751-9762b8a8-8a35-4d6a-ba26-f4774d01496b.png)

**Comment by iFargle** [comment]
Yep, seeing the same issue here.

**Comment by kradalby** [comment]
Has anyone tried with @juanfont fix?

**Comment by NetworkEngineer509** [comment]
> Has anyone tried with @juanfont fix in #1244?

Yes, it's working now. I have deleted the old routes.
