### ISSUE TITLE
Support 2FA / RADIUS or LDAP?

### ISSUE THREAD

**Issue by sunrez** [juanfont/headscale#125]
First,

Thanks for contributing this high quality piece of software.

Does headscale currently supposed a secondary authentication against something like a RADIUS or LDAP server?  I believe Tailscale can do this and it's very needed.

**Comment by juanfont** [comment]
You mean to authorize the nodes? Not sure how LDAP or RADIUS would fit.

We have received today #126, which we will be reviewing soon. That would another authorization workflow (in addition to CLI and the authkeys) for the nodes.
