### ISSUE TITLE
headscale can ping through different namespaces

### ISSUE THREAD

**Issue by Frankzhang854** [juanfont/headscale#1257]
**Bug description**

**To Reproduce**

**Context info**

headscale can ping through different namespaces
<img width="1270" alt="微信图片_20230307091325" src="https://user-images.githubusercontent.com/68718977/223293708-7dcbf122-ace0-4beb-b605-bcd88472ec40.png">

![微信图片_20230307091335](https://user-images.githubusercontent.com/68718977/223293854-da07d994-e2f0-44b3-bfda-a7683a50a01f.jpg)

![微信图片_20230307091344](https://user-images.githubusercontent.com/68718977/223293899-c61c0cc7-0d51-40b8-ae80-c74ad4d58346.jpg)

**Comment by QZAiXH** [comment]
你设置了ACL吗？没有设置默认之间可以互相ping

**Comment by Frankzhang854** [comment]
没有，麻烦问一下，有相关教程吗？

**Comment by kradalby** [comment]
This is intended behaviour, ACLs can be used to prevent this.
