### ISSUE TITLE
Expected client polling behavior

### ISSUE THREAD

**Issue by diseq** [juanfont/headscale#127]
Thanks for this implementation of the tailscale controlplane. Works great for me.

I just wanted to confirm the expected behavior for polling:
Initially I thought it's the reverse proxy. (disabled in the log below. i.e. directly exposed port. no https)
I basically see clients closing the connection after about a minute. is this how client should behave?

```
headscale[42022]: 2021-09-27T08:43:09Z INF Sending initial map handler=PollNetMap machine=desktop-1
headscale[42022]: 2021-09-27T08:43:09Z INF Notifying peers handler=PollNetMap machine=desktop-1
headscale[42022]: 2021-09-27T08:43:09Z INF Notifying peer server-1 (100.64.0.2/32) address=100.64.0.2/32 func=notifyChangesToPeers machine=desktop-1 peer=server-1
headscale[42022]: 2021-09-27T08:43:31Z INF Notifying peer desktop-1 (100.64.0.1/32) address=100.64.0.1/32 func=notifyChangesToPeers machine=server-1 peer=desktop-1
headscale[42022]: 2021-09-27T08:43:31Z INF Notifying peer desktop-1 func=requestUpdate machine=desktop-1
headscale[42022]: 2021-09-27T08:43:39Z INF Notifying peer desktop-1 func=requestUpdate machine=desktop-1
headscale[42022]: 2021-09-27T08:44:09Z INF Notifying peer desktop-1 func=requestUpdate machine=desktop-1
headscale[42022]: 2021-09-27T08:44:09Z INF The client has closed the connection handler=PollNetMapStream machine=desktop-1
```

**Comment by kradalby** [comment]
Possibly not, I suspect there is some issues with the long polling. I will try to investigate this when I'm looking at #97.

That said, using a reverse proxy in front is something we can't control, so a bit hard for us to debug.

**Comment by kradalby** [comment]
Great, keep me updated, I made some adjustments to write timeouts :) and feel free to close if you think it is resolved

**Comment by diseq** [comment]
issue is resolved. no "client has closed the connection" any more.
thanks a lot!
