### ISSUE TITLE
Equipment insulation

### ISSUE THREAD

**Issue by Friedjof** [juanfont/headscale#1271]
**Feature request**

Currently, any device in the headscale VPN network can reach any other device. Now, however, this is not necessarily always desirable. Therefore, I would like to be able to define exactly which devices can see each other and which cannot. So perhaps one could create separate subnets for devices, whereby a device can also be in several subnets (with several IP addresses). This would allow Headscale to be used in a larger environment. Alternatively, one could of course also define who can see whom via a list. However, it would be more intuitive via subnets.

This structuring would specifically help me to include people from my circle of friends in my VPN and not directly release my entire network. It could also help to operate larger instances and shield individual users from each other.

**Comment by madjam002** [comment]
You can do this with ACLs https://github.com/juanfont/headscale/blob/main/docs/acls.md

**Comment by kradalby** [comment]
This is the intended behaviour, as @madjam002 points out, ACLs would be the desired solution for this.
