### ISSUE TITLE
iOS does not take custom Coordination URL into account

### ISSUE THREAD

**Issue by matbgn** [juanfont/headscale#1276]
**Bug description**

The 1.38.1 iOS app does not respect custom coordination server URL and goes either on tailscale.com or, after multiple try/error on 127.0.0.1 (without any port)

**To Reproduce**

Mount a Headscale server on Ubuntu 22.04 and successfully connect from other device. Download last iOS app, set custom URL in settings and try to start app for authentication process.

**Context info**

- Version of headscale used: 0.21.0
- Version of tailscale client: 1.38.1
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version: Ubuntu 22.04
- Kernel version: 6.2.6
- The relevant config parameters you used: local server discoverable on 192.168.x.x even by AirCast with UxPlay and iSH ping command
- Log output: unfortunately none known

**Comment by prom3theu5** [comment]
Sorry not seeing this myself.
I just set it up on my mobile after updating my server to 0.21.0

I ensured tailscale was closed on my iPhone 
Then went into settings -> tailscale. 
Toggled reset keychain to true and input my controller url

After that I started Tailscale. 
The initial auth popup was tailscale.com, which I hit cancel on
I then opened the menu in the app and chose resurgent I ate which then used my controller and showed nodekey

**Comment by mentos1386** [comment]
I'm experiencing the same issue. This is my first time setting this up.

I tried `https://vpn.example.com`, `vpn.example.com` and `https://vpn.example.com:443` but non of them work. I'm trying to use OIDC as well if that matters.

It works on my linux and android machines.

**Comment by travisboss** [comment]
I think there is also an issue with subdomains, I have a domain `headscale.example.ddns.com` but when you try to reauth it just goes to `example.ddns.com` instead which then fails and I cannot change the url to access that domain.
