### ISSUE TITLE
IPv6 exit node ACL not working

### ISSUE THREAD

**Issue by fuomag9** [juanfont/headscale#1277]
**Bug description**

Is ipv6 exit node with ACL possible? As the ACL below makes ipv4 work but ipv6 does not, and I see this in the logs, which does not seem correct:

`Mar 21 20:41:49 headscale headscale[7944]: 2023-03-21T20:41:49+01:00 WRN No IPs found with the alias all6`

On discord it was suggested to use `[::]/0` but that did not work as well and outputted the same log

**To Reproduce**

Create an exit node and use the following ACL
```
{
  "groups": {
    "group:admin": ["fuomag9"]
  },
"Hosts": {
        "all6":  "::/0",
    },
  "acls": [
   { "action": "accept", "src": ["group:admin"], "dst": ["group:admin:*"] },
   {"action": "accept", "src": ["group:admin"], "dst": ["0.0.0.0/0:*"]},
   {"action": "accept", "src": ["group:admin"], "dst": ["all6:*"]}
  ]
}
```

**Context info**

- 0.21.0
- 1.38.1
- MacOS 13.2.1 (22D68) tailscale, RHEL 9.1 headscale
- Linux proxmox 6.1.15-1-pve

**Comment by almereyda** [comment]
It will be useful to reconsider this use case, now that the #1473 has passed.

**Comment by turbotorsten** [comment]
`"dst": ["::/0:*"],`

works for me to enable IPv6
