### ISSUE TITLE
Better Docker Support PR

### ISSUE THREAD

**Issue by acul009** [juanfont/headscale#1300]
**Feature request**

I would like to edit the configuration logic as well as the Dockerfile to make it possible to configure headscale using the environment variables only. I'd need this for my portainer setup.

I'd suggest adding a configuration "SKIP_CONFIG_READ" which would skip checking the config file and instead rely on the environment variables only.

I also think it would be nice to use a double underscore as environment separator, like some other projects like gitea do, as I think that helps differentiate the variables better, but this would break backwards compatibility, so it's probably a bad idea.

If you are ok with my suggestion, I'd get to work on a PR.

Edit: I should probably clarify my intent a bit better. My goal would be to run headscale without any additional configuration as bind mounts so it's easier to deploy. If you'd want this feature for consistency, I could  also autocreate the sqlite db if it hasn't been initialized yet.

**Comment by babyhuey** [comment]
This is relevant to me too. Can it be reopened?
