### ISSUE TITLE
Cannot register machine: machine not found in registration cache

### ISSUE THREAD

**Issue by MagicStarTrace** [juanfont/headscale#1309]
headscale Version: v0.21.0
OS version : CentOS 7

![image](https://user-images.githubusercontent.com/15685376/229467659-125b9d94-b2ed-4b51-bbf5-8ecbd85bc691.png)

headscale nodes register  --user home  --key nodekey:0038a88xxxxxxxxxxxxxxxxxxxxxxxxx

Cannot register machine: machine not found in registration cache 

I get an error when executing headscale nodes register
What should I do?

Thank You!

**Comment by LyuShawn** [comment]
My node machine can successfully register after the second tailscale up, which should be a bug

**Comment by MagicStarTrace** [comment]
I lowered the version and it seems to work, not sure if it's related to the namespace name

**Comment by juanfont** [comment]
Closing this. Please check Discord if you still face issues with the latest version
