### ISSUE TITLE
Generic DoH/DoT (DNS-over-HTTPS/DNS-over-TLS) Support

### ISSUE THREAD

**Issue by Zottelchen** [juanfont/headscale#1312]
**Feature request**

As you may know, the use of DNS-over-HTTPS/DNS-over-TLS (DoH/DoT) has been increasing in popularity due to its enhanced privacy and security features. However, currently, there are only limited options available for DoH support, namely NextDNS. Other DNS providers such as Cloudflare, Google, Quad9, ControlD, etc. are left out. 

Personally I would like to use ControlD for it also offers proxying via DNS. I don't think this is supported yet, as the config very specifically mentions NextDNS.

**Comment by skedastically** [comment]
I'm still interested

**Comment by TornaxO7** [comment]
Wait, so headscale doesn't have DoH or DoT support yet?

**Comment by Arbel-arad** [comment]
can we get this reopened?
i would also like to use my local DNS-over-HTTPS/TLS/QUIC server with headscale.

**Comment by dotWee** [comment]
### **PSA:** DoH (DNS over HTTPS) **is already supported**. It's just not documented.

See the following code reference:

> If a nameserver is a valid URL, it will be used as a DoH resolver. 

https://github.com/juanfont/headscale/blob/72fcb93ef3ae99a5f9fe769a51ea0d50ef702b97/hscontrol/types/config.go#L739-L744

DoH DNS server can be configured through `dns.nameservers.global` as well as `dns.nameservers.split`.

For example, this configuration will rout all your headscale client dns requests through [Quad9](https://quad9.net)'s DoH Server and uses Cloudflare as backup.

```yaml
dns:
  nameservers:
    global:
      - https://dns.quad9.net/dns-query
      - 1.1.1.1
  
  override_local_dns: true
```

**Comment by llego** [comment]
I just configured my Headscale instance to use my own Control D endpoint as a global nameserver:             "https://dns.controld.com/xxxxxxxx". It works well and I see queries in the log in the Control D dashboard. However, I don't see which machine made the query. Those machines which use Control D via my Unifi router do appear in the Control D logs. It would be cool if this was possible also via Headscale. With Tailscale it seems to be possible according to this doc: https://docs.controld.com/docs/tailscale-integration

Does anyone know if this is possible?
