### ISSUE TITLE
Synology support?

### ISSUE THREAD

**Issue by rudidev08** [juanfont/headscale#1320]
There’a tailscale app for synology NAS, would headscale work with it, or does it need custom support? I didn’t see synology mentioned in readme file as possible client.

**Comment by nblock** [comment]
> There’a tailscale app for synology NAS, would headscale work with it, or does it need custom support?

It should work, have you tried the steps described here: https://techoverflow.net/2022/03/26/how-to-connect-synology-nas-to-headscale/ ?

**Comment by kradalby** [comment]
It should work the same as the other Tailscale clients, check out Discord for discussing with people and asking for help.
