### ISSUE TITLE
What specific services does 'embedded DERP (and STUN) server' provide

### ISSUE THREAD

**Issue by threerog** [juanfont/headscale#1326]
embedded DERP (and STUN) server #388

In addition to assisting client connections, this derp service
Can data relay transmission services be provided when the client cannot connect directly
Do you still need to build your own derp service for data relay

**Comment by nblock** [comment]
A DERP server can be used to relay traffic when a direct connection between nodes is not possible. [Tailscale provides some DERP servers for their users](https://tailscale.com/kb/1232/derp-servers/) and Headscale can also provide a single DERP instance for you.

You don't need to run your own DERP server, but you probably should to not put additional burden on Tailscale DERP servers.

**Comment by threerog** [comment]
> A DERP server can be used to relay traffic when a direct connection between nodes is not possible. [Tailscale provides some DERP servers for their users](https://tailscale.com/kb/1232/derp-servers/) and Headscale can also provide a single DERP instance for you.
> 
> You don't need to run your own DERP server, but you probably should to not put additional burden on Tailscale DERP servers.

Yes, my goal is not to use the official Derp service of Tailscale, but to use my own server to relay traffic. So I need to ensure that after blocking the official derp service of tailscale, can headscale provide relay services to ensure 100% success of the connection

**Comment by kradalby** [comment]
This question is more suitable for Discord than Github, I will close this, please continue the conversation there.

> Do you still need to build your own derp service for data relay

In principal, you would _not_ need to add more than  the one DERP server that comes with headscale, however, you would introduce a single point of failure into your setup, so having more than one might be sensible.
