### ISSUE TITLE
Delete of shared host causes 500 Errors / cli errors.

### ISSUE THREAD

**Issue by linuxkidd** [juanfont/headscale#133]
Reproduction:
1. Create two namespaces
2. Add a host to each
3. Share a host from one namespace to another
4. Delete the shared host

Log output:
~~~
Oct 01 21:25:05 myhost headscale[2726810]: 2021-10-02T03:25:05Z ERR Cannot fetch peers error="invalid hex key (\"\"): length=0, want 32" func=getMapResponse
Oct 01 21:25:05 myhost headscale[2726810]: 2021-10-02T03:25:05Z ERR Failed to get Map response error="invalid hex key (\"\"): length=0, want 32" handler=PollNetMap id=XXXXXXXXXXXXXXXXXXXXX
~~~

Further, `headscale -n NAMESPACE nodes list` fails with:
~~~
2021/10/01 21:19:35 Error fetching shared machines: record not found
~~~

Only obvious way out was to wipe `headscale` db and start  fresh, although I'm sure some sql queries could have cleared it.  I'm just starting with `headscale`, so no reason to spend time salvaging the DB.

**Comment by kradalby** [comment]
Ah good catch, @juanfont can you take a look at this?

We should probably also verify deleting nodes and shared nodes in the integration tests.

**Comment by juanfont** [comment]
Yes, I am on it. Hopefully today will be fixed.
