### ISSUE TITLE
Upgrade path from Binary to .deb / .rpm

### ISSUE THREAD

**Issue by Porco-Rosso** [juanfont/headscale#1341]
The installation docs do not reflect the current .deb and .rpm releases, as they mention direct go binaries instead.
1. How does one install headscale using the new release format?
2. How does one upgrade from the previous method to the new one, given the manual SystemD install process?

This is both a matter of documentation and upgrade functionality. I assume eventually headscale will be released on default package mangers, at which point the process should be simplified.

**Comment by kradalby** [comment]
Hi, I will work on documentation on how to install it on various platforms today; but in the mean time:

1. Download the file that is associated with your linux distribution; .deb for Debian/Ubuntu and .rpm for Fedora/Alma/CentOS and use the platform specific installation instructions to install them.
2. The ideal would be to remove everything from before, except for the config.yaml, and use the method above.

We do not aspire to add it to the package managers, and we will most likely just release it via Github as now.

**Comment by Porco-Rosso** [comment]
I see the new documentation is up, so I will close this.

This was a roadbump for my transition, but all is good now.
https://github.com/juanfont/headscale/issues/1342#issuecomment-1516779155

**Comment by Porco-Rosso** [comment]
As I mentioned on the other thread still having problems with permissions, `/var/run/headscale/` in particular

**Comment by loprima-l** [comment]
Please make sure to run this with user being the user that launches Headscale :
`sudo chown user /var/run/headscale`
