### ISSUE TITLE
Tailscale status strange IP display

### ISSUE THREAD

**Issue by qzydustin** [juanfont/headscale#1344]
**Bug description**

When I run "Tailscale status," some nodes show ipv6 ip, and some nodes show ipv4 ip.

And ipv4 and ipv6 both work on these nodes.

For example, I can use fd7a:115c:a1e0::3 and 100.64.0.3 to connect the 2nd node in the pic, and I can use fd7a:115c:a1e0::c and 100.64.0.12 to connect the 3rd node too.

![screenshot](https://i.imgur.com/bhpB5Pz.png)

**To Reproduce**

I removed and re-added the nodes, but it still shows the same.

**Context info**

In the screenshot,
1st Ubuntu shows ipv6
2nd Debian shows ipv6
3rd iOS shows ipv4
4th Android shows ipv4
5th Windows shows ipv4
6th iOS shows ipv6
7th macOS show sipv6

Out the screenshot,
9th Windows shows ipv6

That is so strange.

**Comment by kradalby** [comment]
I suspect this is that we dont sort the list sent to the client, and it seems mostly cosmetic. This should be a "good starter issue" for anyone who wants to find where we send the NetMap to Tailscale and sort the ips so that ipv4 is always first.

**Comment by qzydustin** [comment]
> I suspect this is that we dont sort the list sent to the client, and it seems mostly cosmetic. This should be a "good starter issue" for anyone who wants to find where we send the NetMap to Tailscale and sort the ips so that ipv4 is always first.

That's the right reason. I use `tailscale status --json`. Here is the difference.
- This node shows ipv4 in status 
![screenshot](https://i.imgur.com/MjJXvOs.png )

- This node shows ipv6 in status 
![screenshot](https://i.imgur.com/t1WjRyR.png )

**Comment by kradalby** [comment]
Sounds good, perfect first issue for someone to write a patch that makes sure IPv4 is always first in the list.

**Comment by loprima-l** [comment]
I've taken a look at it and as I can see, the status command just returns the ipn status from the tailscale lib, should we fix it there or address a PR to tailscale ?

**Comment by kradalby** [comment]
It should be fixed where Headscale builds the MapResponse, make sure IPv4 is always first in the list if present.

**Comment by gbraad** [comment]
Also, the order is something the Tailscale client should handle; it should consistently show the addresses by type/version and not just in the order received.

**Comment by kradalby** [comment]
@gbraad I disagree with that, while I do not know the reason for the original decission, I suspect it is intentional to allow the control server to change the behaviour without having to wait for all clients to upgrade.

It is a perfectly viable design to accept a list that has stable order.

**Comment by gbraad** [comment]
We can't say if that is the case... but it does make their implementation easier (centralized). If so, perhaps this order might also be dependent on how the prefixes are stated in the config?

```
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10
```

or

```
ip_prefixes:
  - 100.64.0.0/10
  - fd7a:115c:a1e0::/48
```

**Comment by gbraad** [comment]
@juanfont 

> That's a known issue with the tailscale client. Please use 100.64.0.0/10, or a subnet of it.

Is that filed? I experienced the same and decided to revert to the suggested subnet for now.
