### ISSUE TITLE
Remove `v0.23.0` Docker Tag

### ISSUE THREAD

**Issue by gabe565** [juanfont/headscale#1368]
**Issue description**

Hello! I maintain a Helm chart for Headscale at https://charts.gabe565.com/charts/headscale/. This morning, an automated PR that bumps Headscale from v0.21.0 to v0.23.0 was opened (see [here](https://github.com/gabe565/charts/pull/120)). As far as I can tell, v0.22.1 is the latest release and v0.23.0 shouldn't exist yet. I checked GHCR and Docker Hub and there are v0.23.0 tags in both, and I see a GitHub Actions run for v0.23.0, but the tag doesn't exist anymore. If this was released by accident, you may want to remove this tag from both container repos.

For now, I'll manually update my Helm chart to v0.22.1 for now and ignore the PR for v0.23.0.

**To Reproduce**

**Context info**

**Comment by ohdearaugustin** [comment]
I just took a look and I can confirm this issue and we should manually delete the tags. Otherwise we will have future problems. @juanfont @kradalby

**Comment by juanfont** [comment]
Done!

**Comment by ohdearaugustin** [comment]
There are still the docker container in the github repository. https://github.com/juanfont/headscale/pkgs/container/headscale/86901223?tag=0.23

**Comment by alexdelprete** [comment]
> Done!

it's still there in ghcr.io package repo.

**Comment by kradalby** [comment]
@juanfont can you delete that tag in ghrc, I dont think I can.

**Comment by juanfont** [comment]
done!
