### ISSUE TITLE
FR: Send Peers delta in MapResponse

### ISSUE THREAD

**Issue by kev-the-dev** [juanfont/headscale#1383]
**Feature request**

**I'm currently working on this feature and will submit my patch upstream, but creating a ticket to prevent duplicate work**

This is a ticket to implement the sending of Peers list as deltas rather then the full list each time, per this TODO https://github.com/juanfont/headscale/blob/d0113732fe1a3248456da84259f01967b4d09b49/api_common.go#L72.

In addition to improving performance, there is at least one bug I've found associated with not sending deltas:
* There are two nodes in a tailnet, A and B
* Node B is deleted
* A MapResponse is generated for node A. Node A no longer has any peers, so `len(MapResponse.Peers) == 0`
* Tailscale interprets `len(MapResponse.Peers) == 0` as no change, meaning it isn't notified of node B being deleted https://github.com/tailscale/tailscale/blob/43819309e18ac7d496643fcd86489a2ee0927964/control/controlclient/map.go#L227
* Node B remains on tailnet after being deleted, causing a security vulnerability for deleted nodes

**Comment by loprima-l** [comment]
How is it going ? Do you have any issues ?

**Comment by loprima-l** [comment]
Nice, that's a good step on Headscale optimization, thanks for your investment.

**Comment by kradalby** [comment]
This is implemented as part of #1492.
