### ISSUE TITLE
Bug: peers not notified of deletion when 2 nodes in network

### ISSUE THREAD

**Issue by kev-the-dev** [juanfont/headscale#1384]
**Bug description**

* There are two nodes in a tailnet, A and B
* Node B is deleted
* A MapResponse is generated for node A. Node A no longer has any peers, so len(MapResponse.Peers) == 0
* Tailscale interprets len(MapResponse.Peers) == 0 as no change, meaning it isn't notified of node B being deleted https://github.com/tailscale/tailscale/blob/43819309e18ac7d496643fcd86489a2ee0927964/control/controlclient/map.go#L227
* Node B remains on tailnet after being deleted, causing a security vulnerability for deleted nodes

Should be fixed by implementing Peer list deltas (sending PeersDeleted explitcly in #1383)

**Comment by loprima-l** [comment]
Hi, can you please close this issue as we have #1383, it will help to see easily what are the urgent fix.

Thanks
