### ISSUE TITLE
CertManager's 10s TLS handshake error EOF

### ISSUE THREAD

**Issue by ventsislav-georgiev** [juanfont/headscale#1386]
Version: 0.22.1
Usage: Kubernetes

When using the LetsEncrypt auto certificate provisioning. There is a constant error in the logs.
Seems to be related to this issue: https://github.com/cert-manager/cert-manager/issues/4594
<img width="527" alt="image" src="https://user-images.githubusercontent.com/5616486/235007466-2427e42f-7c3a-45f3-af21-e22a5b2e91d6.png">

Is it expected or there is a way around it?

**Comment by loprima-l** [comment]
Is the connection with 10.36.2.1 working well ? Have you tried that (https://github.com/cert-manager/cert-manager/issues/4594#issuecomment-997164924) ?

**Comment by ventsislav-georgiev** [comment]
@loprima-l There is no such pod in the cluster. Isn't in headscale the certmanager server started internally in the same process?

As for the 10.36.2.1 connectivity. That is the default gateway and all our things work as expected.

I forgot to mention an important detail.. The logs above don't break any functionality. The SSL certificate is provisioned successfully and connections from tailscale clients work as expected. All is working, except it constantly logs this EOF error.

**Comment by loprima-l** [comment]
Thanks for your reply I'm just starting on Headscale so TLS wasn't the first thing I checked. I will look at it when I've got the time as it's not a major outage.

**Comment by loprima-l** [comment]
@ventsislav-georgiev Hi, have you created your instance based on the example directory ?

**Comment by loprima-l** [comment]
The version of cert-manager in this [file](https://github.com/juanfont/headscale/blob/main/examples/kustomize/install-cert-manager.bash) is responsible for the bug you've described I think, I'm not familiar with Kubernetes but maybe updating it would fix your issue, can you try it ?

**Comment by ventsislav-georgiev** [comment]
Hmm.. I haven't deployed cert manager at all and I don't think it is part of the helm chart as I don't see any deployment in the cluster related to cert manager. That is why I think it is used internally by headscale.

**Comment by loprima-l** [comment]
I can't find it in the dependencies ... 
@juanfont any idea ?

**Comment by ventsislav-georgiev** [comment]
@loprima-l it seems autocert is used. Here is the code: https://github.com/juanfont/headscale/blob/main/app.go#L843

The ref to certmanager issue I provided is matching the error message. I'm not sure if autocert and certmanager are related.
