### ISSUE TITLE
logout node expired but not deleted

### ISSUE THREAD

**Issue by Carseason** [juanfont/headscale#1388]
- Version of headscale used: 0.22.1
- Version of tailscale client : 1.40.0
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version : Openwrt And Mac
- Kernel version
- The relevant config parameters you used:  tailscale logout
- Log output
2023-04-28T10:19:54Z INF go/src/headscale/protocol_common.go:649 > Successfully logged out machine=iStoreOS noise=true

headscale Grpc.ListMachines get nodes ,
the node still exists on the user ;node Expiry is Current Date
tailscale the new user B   in  login
the node still exists on the user to A

**Comment by Carseason** [comment]
> 您有多少个节点，包括已删除的节点？



> How many nodes had u including the deleted one ?

I only have 2

**Comment by loprima-l** [comment]
Please refer to #1384 and close your issue
