### ISSUE TITLE
Allow OIDC tokens for API request

### ISSUE THREAD

**Issue by acul009** [juanfont/headscale#1402]
**Feature request**

I would like to use OIDC tokens to manage some aspects of my machine. This includes adding tags to a machine.
When using an ID token, there would already be basic code to identify the user, which could be a bit expanded to be used by the api.

This could increase security for external managment UIs, as the Interface would no longer need to use an "administrative" token. Current Interfaces have to handle Access Control seperately again and have to protect their Headscale token.
When allowing OIDC ID-Tokens, the ui would only need to obtain such a token and then use is to e.g. query machines, which would only return the machines this user is allowed to see or edit.

**Comment by korfuri** [comment]
I'd like to reopen this. I'm running headscale and not being able to integrate with my OIDC SSO is a pain: I have to manage headscale tokens out of band, which in practice means sshing to a machine and generating a token via the CLI.

Being able to rely on OIDC tokens would abstract all of this.
