### ISSUE TITLE
Support of Tailscale ACL node attributes

### ISSUE THREAD

**Issue by tunip** [juanfont/headscale#1407]
**Feature request**

Support of Tailscale ACL node attributes (nodeAttrs) would be great.

I use Tailscale and NextDNS together. Configure different NexDNS IDs for specific devices (parentw/kids) (see https://tailscale.com/kb/1218/nextdns/)

```
"nodeAttrs": [
        {           
                "target": ["kids"],
                "attr": [
                        "nextdns:abc123",
                        "nextdns:no-device-info",
                ],
        },
],
```

**Comment by aalmenar** [comment]
+1
