### ISSUE TITLE
ip_prefixes cannot be displayed properly

### ISSUE THREAD

**Issue by threerog** [juanfont/headscale#1409]
When `ip_prefixes` is `100.64.0.0/24`, running `tailscale status` normally displays the IPs of all devices. However, when `ip_prefixes` is in other network segments, `tailscale status` cannot display the IPs of other devices,

Also, I have a question whether `Hedascale` supports multiple IPv4 `ip_prefixes`?
How to use multiple `ip_prefixes` if supported?

**Comment by juanfont** [comment]
Ranger other than 100.64.0.0/10 and fd7a:115c:a1e0::/48 (or their subnets) are not supported, and it can/will lead to odd behaviour. 

This issue should be tackled in the Tailscale client.
