### ISSUE TITLE
[Missing documentation] Security considerations – what if Headscale server gets compromised?

### ISSUE THREAD

**Issue by codethief** [juanfont/headscale#1432]
I have been trying to find information about security aspects of Headscale (and Tailscale in general), in particular about what risk I'm facing should my Headscale server get compromised. [So far](https://forum.tailscale.com/t/tailscale-security-what-if-the-coordination-server-goes-rogue/5015), my impression is that a compromised Headscale instance would basically mean that my entire Tailnet is at risk, since the coordination server is not only able to modify ACLs and e.g. grant SSH access to nodes (also compare https://github.com/juanfont/headscale/issues/661) but, in the absence of Tailscale Lock (compare 
https://github.com/juanfont/headscale/issues/1307), it can also add new nodes to the network (and then grant them access to everything). But *even with* Tailscale Lock enabled, if the machine on which the Headscale daemon is running is part of the Tailnet and that entire machine (and its private key) get compromised, or if the attacker has another way of obtaining a private key of one of the peers of the Tailnet, my impression is – and please correct me if I'm wrong here – that it'd be game over for the entire network.

Since this this doesn't seem to be a far-fetched risk (people usually run all kinds of things on their personal servers, and vulnerabilities abound) and the potential impact of the above attack vector is devastating, I'd be grateful for clarification. Moreover, if my concerns are indeed justified, I think they would also deserve a mention in the documentation and, also, proper warning (e.g. "Never run Headscale on a Tailnet node!"). And if they're not justified, all the better! But even in this case, adding documentation about potential attack vectors and their impact would be great.

Related issues: https://github.com/juanfont/headscale/issues/1072

**Comment by tillnelown** [comment]
Regarding ssh access, headscale currently doesn't support it and when it does it will only be an issue if you enable it on the clients as per `tailnet up -h`:

`--ssh, --ssh=false
        run an SSH server, permitting access per tailnet admin's declared policy (default false)`

But taildrop may also be an issue, you can currently add files to any android device using it without user input though this may change when the app gets a ui for it. I haven't used it on other platforms so I can't comment on how it's handled there.

**Comment by codethief** [comment]
Ugh. The issue is *not* stale.

**Comment by IronBeardKnight** [comment]
I am also concerned about how it is actually secured if your self hosting.

**Comment by zebogan** [comment]
Same concern, only stuff I've found online so far is this and an unanswered tailscale forum post.

**Comment by nokados** [comment]
So, a year and a half later, are there any plans to implement this critical feature in the near future?

And it is really important, because in a private network, where all devices do not have a public IP and access from the outside, the coordinating server is the most vulnerable part. Moreover, many people have it located in a VPS (#1072 ) that have root access to all their virtual machines. Without the ability to sign nodes, the network is completely open to the VPS provider and all his "friends". 

If you are still not ready to implement it yourself, maybe you will give it to contributors?

**Comment by street-grease-coder** [comment]
I think I get it, this is just a plaything, if the headscale coordination server, which is afaik just one, nonredundant system, all computers and internal networks are compromised. It's one giant point of failure and weakness
