### ISSUE TITLE
Updating to 0.22.2 causes all devices to see each other, regardless of ACLs

### ISSUE THREAD

**Issue by networkException** [juanfont/headscale#1457]
## Bug description

  
After updating to 0.22.0, running `tailscale status` on any connected machine shows a list of all devices in the tailnet, even if machine A doesn't have any ACL allowing access to machine B.

## Environment

- OS: Linux
- Headscale version: 0.22.2
- Tailscale version: 1.40.0

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

- Run headscale 0.22.2
- Run `tailscale status` on a connected machine
- See all devices in the tailnet

**Comment by pkrivanec** [comment]
Hi, I do not see this behavior in my environment.
Can you provide a minimal ACL file where the problem occurs?

**Comment by networkException** [comment]
```jsonc
{
    "hosts": {
        "a": "fd7a:115c:a1e0::4",
        "b": "fd7a:115c:a1e0::6",
    },
    "acls": [
        {
            "action": "accept",
            "proto": "tcp",
            "src": ["b"],
            "dst": ["a:8001"]
        },
    ],
}
```

**Comment by pkrivanec** [comment]
Hi, yes I can confirm that, the problem occurs as soon as a hosts entry is used.

**Comment by statkashaman** [comment]
Hi, with this configuration, users also began to see each other, although previously they saw only exit nodes. This happened after updating from 0.21.0 to 0.22.3.
`      headscale-acl.yaml: |-
        ---
        tagOwners:
          tag:exitnode:
            - exitnodes
        acls:
          - action: accept
            src:
              - "*"
            dst:
              - "tag:exitnode:*"
          - action: accept
            src:
              - "*"
            dst:
              - "0.0.0.0/0:*"`

**Comment by kradalby** [comment]
If the case is as mentioned above, this is intended behaviour, this is because a one way direction needs to be present on both nodes even if one node cannot actually access the other. This was previously wrongly implemented in Headscale, giving the wrong impression of how it should work.

If this is _not_ the case, please reopen with a reply to the previous comment.

**Comment by networkException** [comment]
Sorry for only coming back to this now.

> > ```js
> > {
> >     "hosts": {
> >         "a": "fd7a:115c:a1e0::4",
> >         "b": "fd7a:115c:a1e0::6",
> >     },
> >     "acls": [
> >         {
> >             "action": "accept",
> >             "proto": "tcp",
> >             "src": ["b"],
> >             "dst": ["a:8001"]
> >         },
> >     ],
> > }
> > ```
> 
> To clarify, the issue is that after version `0.22.2`, when you run `tailscale status` on host `a` or `b`, both `a` and `b` will be listed?
> 
> Previously, when you ran `tailscale status` on host `a`, you did _not_ see host `b` in the list?

They would both see each other perfectly fine previously, this is just the minimal reproducible config to trigger the issue.

What was not clear from my example is that there were actually a lot more devices in the tailnet, hence my "all devices in the tailnet" description initially. Just those don't need to be mentioned in the hosts or acls for the issue to accur, as such I left them out when reducing.

The following config would be a more "complete" example, hinting at the other devices existing. Running `tailscale status` on any one of those (also ones that are not explicitly listed in the `hosts` section would yield a list of all nodes in the entire network, again regardless of acls.

```js
{
    "hosts": {
        "1": "fd7a:115c:a1e0::1",
        "2": "fd7a:115c:a1e0::2",
        "3": "fd7a:115c:a1e0::3",
        "a": "fd7a:115c:a1e0::4",
        "5": "fd7a:115c:a1e0::5",
        "b": "fd7a:115c:a1e0::6",
    },
    "acls": [
        {
            "action": "accept",
            "proto": "tcp",
            "src": ["b"],
            "dst": ["a:8001"]
        },
    ],
}
```

**Comment by networkException** [comment]
@kradalby could you please take another look at this?

**Comment by kradalby** [comment]
Ive reopened this, but I don't expect to get to it in a while.

**Comment by disconn3ct** [comment]
Did stalebot fix this bug? Or just close it?
