### ISSUE TITLE
Difficult login on windows

### ISSUE THREAD

**Issue by iszhi** [juanfont/headscale#1467]
Whenever I restarted my PC, I need spend hours to login my headscale server with tailscale client on my Windows PC. 
I"m using the commend tailscale login --login-server https://my server.com:443 in the CMD. However, The response takes hours, and maybe days, I don't. What I did in the past is to restart the tailscale service, then try again, try again.  Maybe uninstall tailscale, and install it again. and try again, try again. I don't remember how many times I tried. In the end, sometimes, I'm luck, I succeed, sometimes not. I don't know what's the problem.

**Comment by luizvaz** [comment]
I was facing the same issue.
Watching the logs, I found that the Headscale server was receiving the request correctly.
But it sent back the wrong address to the Windows client request.

After fixing the config file, everything started to work:
![image](https://github.com/juanfont/headscale/assets/691612/a096e114-13a8-42d2-ae57-a2fcb87e3c53)

I used the following steps on Windows client
- `CMD `as Admin
- close Tailscale client
- `net stop Tailscale`
- delete the %appdata% local\tailscale folder
- `net start Tailscale`
- `tailscale logout`
- `tailscale up --accept-routes --login-server=https://<SERVER_URL>/ --unattended`

Add the node using the key part to the WebUI or using the console command:
`headscale nodes register --user USER --key nodekey:2ceb1d687ae8adaa9f3d1cd530a076cdfbfb8fd30ca87ebd78ea409d1e9e5360`

**Comment by iszhi** [comment]
@luizvaz  Thanks for the suggestions, but actually it didn't work for me. I cannot find any log about my windows client on my headscale server. And, after I clean up my client on my windows by following your suggestion, it still didn't work.  

Actually, I think my server configuration is OK, because I also have another PC(ubuntu) at my home, and my Android phone and my Android Pad.  All of the other devices works fine with my headscale server, only I cannot make it running on windows.  

Or accurately I can not always promise I can run it on windows.  Sometimes I can succeed without any reason, sometimes failed also without any reason.

I'm not an expert. I don't know how to debug it.  Or are you interested in teaching me how to debug on my windows?

**Comment by juanfont** [comment]
Hi :)

This is user support, please use our Discord channel.

**Comment by iszhi** [comment]
@wtdry This may be a solution. I'll try it later.
