### ISSUE TITLE
Usage issues

### ISSUE THREAD

**Issue by ysn2382617094wsw** [juanfont/headscale#1472]
Hello, I'm a beginner, I want to use headscale for cross-region play LAN games, similar to Red Alert 2, but strangely, my game can't scan my friend's computer, but he can see me, I have the same command as he up --reset --login-server=http://ip:8080/ --unattended --accept-routes=true -- accept-dns=false --advertise-routes=0.0.0.0/0,::/0, why is that?
** I can't use Discord to ask questions, sorry to ask questions on github **
My firewall and his firewall are closed

**Comment by rjmalagon** [comment]
Do you need to advertise routes for this porpouse?
On Windows is better to first logout on the tailnet, delete the nodes on headscale server, and register again than mere "--reset"

**Comment by lionslair** [comment]
Did you solve this? the remote network can ping devices on my network but I can only ping the local ip of the host running tailscale.
