### ISSUE TITLE
How to customize the registration authentication page

### ISSUE THREAD

**Issue by VMCoud** [juanfont/headscale#1479]
## Why

The default authentication interface is too simple. I want to add the function of automatically copying nodekey:id by clicking
## Description

https://xxxx.com/register/nodekey:af5d8e16f6314112aa6d032f6c948893903637d08ceee21978987bf26f7e6662 How to customize the registration authentication page

**Comment by VMCoud** [comment]
I would like to know the template file location for the default registration verification page

**Comment by yunsip** [comment]
Self registration of client users can be achieved through OIDC authentication

**Comment by VMCoud** [comment]
> 客户端用户可通过OIDC认证实现自注册

Hello, I am trying to access keycloak, which address in headscale should be filled in the 'Valid redirect URIs''Web origins' in keycloak

**Comment by VMCoud** [comment]
Trying to fill in the headscale https://networks.xxx.com/auth/callback will return a 404 error

**Comment by VMCoud** [comment]
Is there any detailed documentation about accessing keycloak in headscale,

**Comment by yunsip** [comment]
keycloak Valid Redirect URIs  https://headscaleserver/oidc/callback      {
  "realm": "tailscale",
  "auth-server-url": "https://keycloakserver/auth/",
  "ssl-required": "external",
  "resource": "headscale",
  "credentials": {
    "secret": "EYwCuajKbVaGmxlZCgoewew7VVhMaeCj"
  },
  "confidential-port": 0
}

**Comment by kradalby** [comment]
As per comment (https://github.com/juanfont/headscale/pull/1435#issuecomment-1576304151) we will not support customising the registration page, however a nicer one will probably be merged soon so it will be prettier (#1484).
