### ISSUE TITLE
kubernetes integration

### ISSUE THREAD

**Issue by karthick-kk** [juanfont/headscale#1481]
## Why

It helps accessing kubernetes services and pods privately over headscale network without exposing services for outside traffic
## Description
Currently tailscale has such integration through sidecar proxies and subnet router (https://github.com/tailscale/tailscale/blob/main/docs/k8s/README.md) . We do not see such documentation references for exposing controlplane api of headscale to access the underlying services of a k8s cluster.

**Comment by lijozech-12** [comment]
Hi were is the documentation for this k8s intergration.

**Comment by cyber-goka** [comment]
@lijozech-12 did you manage to find it?
