### ISSUE TITLE
[minor Bug] ephemeral_node_inactivity_timeout (3d) is set too low

### ISSUE THREAD

**Issue by PizzaProgram** [juanfont/headscale#1486]
Setting this at `config.yaml` file:
  `ephemeral_node_inactivity_timeout: 3d` (3 days)
causing this:
```
FTL ../home/runner/work/headscale/headscale/cmd/headscale/cli/root.go:48 > 
  Error loading config error="Fatal config error: ephemeral_node_inactivity_timeout (3d) is set too low, 
  must be more than 1m5s"
```

But setting it to :
`10000m` (ten thousand minutes) is OK.

## Environment

- Version of headscale used: `v0.22.3`
- OS: `Linux Debian 11`

**Comment by vsychov** [comment]
@PizzaProgram , `d` is not valid time unit, you can see more info there: https://pkg.go.dev/time#ParseDuration
`Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".`
