### ISSUE TITLE
node with tailscale 1.44.0 can't connect to  other node. 

### ISSUE THREAD

**Issue by linxd** [juanfont/headscale#1494]
## Environment  centos 7.6.  headscale latest docker image .

- OS: centos /windows
- Headscale version: latest docker image
- Tailscale version:  1.44.0

- [y] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

**Comment by kradalby** [comment]
I've just added this version to our integration tests and cannot replicate this.

Please note that we do not support docker and (reverse)proxy.

Are you still seeing this issue?

**Comment by linxd** [comment]
it's ok now
Thanks



在 2023-07-07 21:52:46，"Kristoffer Dalby" ***@***.***> 写道：

I've just added this version to our integration tests and cannot replicate this.

Please note that we do not support docker and (reverse)proxy.

Are you still seeing this issue?
