### ISSUE TITLE
Allow DNS wildcards in config

### ISSUE THREAD

**Issue by gymnae** [juanfont/headscale#1496]
## Why

I have a bunch of domains and subdomains being served by a reverse proxy. I'd like to directly speak to this reverse proxy by using a wildcard DNS entry like:
"*.domain.tld"
"A"
"192.0.0.2"

Right now I need to add every DNS entry served by this reverse proxy by hand. 

## Description
Allow wildcards for DNS entries

**Comment by almereyda** [comment]
This may also be relevant for #1356.

**Comment by tctlrd** [comment]
This would indeed be a huge time saver...

**Comment by termermc** [comment]
I would also like to see this. A workaround for now would be redirecting DNS to an internal CoreDNS server or similar to set up records manually, but that's not a great solution.

**Comment by PatrickHuetter** [comment]
This would be very nice!
