### ISSUE TITLE
Derb error on startup

### ISSUE THREAD

**Issue by thenitai** [juanfont/headscale#1500]
Hi,

```
Could not load DERP map from path error="Get \"/etc/headscale/derp.yaml\": unsupported protocol scheme \"\"" func=GetDERPMap url=/etc/headscale/derp.yaml
```

Seeing this issue on a Ubuntu 22 server. Fresh install. Migrated from another Tailscale server. Running the latest 0.22.3 version.

**Comment by kradalby** [comment]
Could you please post your config and the derp map?

**Comment by thenitai** [comment]
> Could you please post your config and the derp map?

Sorry for the late reply. It was an issue on the network. Awesome project. Couldn't do a lot with our network without you guys :)
