### ISSUE TITLE
Ability to reload headscale in docker container

### ISSUE THREAD

**Issue by winterheart** [juanfont/headscale#1506]
## Why

Currently headscale supports reloading config on `kill -HUP` signal which has no downtime, but headscale in docker do not have `kill` or equivalent command. I forced to restart whole container to apply changes which may result unavailability of service.

## Description

It would be great if headscale will watch config.yaml and acl.yaml files for changes and  gracefully reloads them on changes. Less elegant but more straightforward approach would be adding `kill` command into docker image, so admin can call `docker exec kill -HUP ...` to reload config inside container.

**Comment by winterheart** [comment]
Ok, after quick digging, I found that I can actually `docker kill --signal HUP headscale` which forces to reload config, but still, it would be great if headscale will automatically reloads configs on changes.

**Comment by juanfont** [comment]
Dupe https://github.com/juanfont/headscale/issues/173
