### ISSUE TITLE
/key?v=65 unsupported protocol scheme 

### ISSUE THREAD

**Issue by frakman1** [juanfont/headscale#1511]
Continuation of this [issue](https://github.com/juanfont/headscale/issues/1029) using docker container. Instructions [here](https://github.com/juanfont/headscale/blob/main/docs/running-headscale-container.md)

Ran into this error when trying to do the `tailscale up --login-server xxx ` from a node machine.
Logs below are from a Raspberry Pi 3B+ (Buster) running latest version of tailscale 1.46.0
Also using latest headscale docker image.

Same result when running from MacOS using latest version 1.44.0 from App Store  `/Applications/Tailscale.app/Contents/MacOS/Tailscale up --login-server xxx`

Basically complaining about an unsupported protocol scheme.

```
tailscaled[9289]: Start
tailscaled[9289]: control: client.Shutdown()
tailscaled[9289]: control: client.Shutdown: inSendStatus=0
tailscaled[9289]: control: mapRoutine: quit
tailscaled[9289]: control: Client.Shutdown done.
tailscaled[9289]: Backend: logs: be:a0eb62d4b30fd996a4b46ff050db3cdb4510b8f315ed005623d77e34eebe69f4 fe:
tailscaled[9289]: Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
tailscaled[9289]: blockEngineUpdates(true)
tailscaled[9289]: Reconfig(down): no changes made to Engine config
tailscaled[9289]: StartLoginInteractive: url=false
tailscaled[9289]: control: client.Login(false, 2)
tailscaled[9289]: control: LoginInteractive -> regen=true
tailscaled[9289]: control: doLogin(regen=true, hasUrl=false)
tailscaled[9289]: Received error: fetch control key: Get "192.168.86.145/key?v=65": unsupported protocol scheme ""
```
I even got the `latest-debug` version of headscale but don't see any additional logs from `docker logs --follow headscale`. Just this:
```
An updated version of Headscale has been found (0.22.3 vs. your current 0.22.3-debug). Check it out https://github.com/juanfont/headscale/releases
2023-07-21T15:44:13Z INF Setting up a DERPMap update worker frequency=86400000
2023-07-21T15:44:13Z INF listening and serving HTTP on: 0.0.0.0:8080
2023-07-21T15:44:13Z INF listening and serving metrics on: 0.0.0.0:9090
```

@Orhideous

**Comment by juanfont** [comment]
@frakman1 can you share the value you have in `server_url` in your config, and a redacted version of xxx in `tailscale up --login-server xxx`?

**Comment by frakman1** [comment]
`config.yaml` is largely the same as the default one downloaded from [here](https://raw.githubusercontent.com/juanfont/headscale/main/config-example.yaml)
I just changed `listen_addr` and `metrics_listen_addr` otherwise I couldn't connect to it via the host IP address from aanother machine.
```
server_url: http://127.0.0.1:8080
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
```

xxx is the same as the value in the logfile: 192.168.86.145

**Comment by juanfont** [comment]
You need to use a full domain name name like `frakman
com`, in both server_url and the tailscale up command. There you also need to include the https:// in https://frakman.com

**Comment by frakman1** [comment]
Thank you for your response.

Is there a reason why an IP address can't be used? e.g. websites support `http(s)://<ip-address>:8080` formats
If SSL is required to validate a Fully Qualified Domain Name (FQDN), then can that be turned off somehow?

The idea was to use headscale to connect various internal LANs behind a corporate firewall with no outside access. Using a known and accessible IP address for the headscale server would be ideal for all the nodes that reside in different LANs.

I was hoping to avoid having to register and get a certificate for a FQDN and constantly renewing it.
