### ISSUE TITLE
fail2ban rule for API?

### ISSUE THREAD

**Issue by unusualevent** [juanfont/headscale#1520]
## Why
If headscale is part of the outer services of a network (along with email servers), it'd be great to have strong tooling to monitor and block attempts to authenticate to it, to disallow bruteforcing.

This is important for things like the API, but less well defined for things like wireguard itself, which doesn't provide good logging for key attempts for use in blocking. At least the other negotiation ports on headscale would be more secured.

## Description

It would be nice to have a recommended filter & block action for headscale, to be used in fail2ban.

these can simply be documented in a section entitled "hardening".

For example:

- Vaultwarden's fail2ban documentation: https://github.com/dani-garcia/vaultwarden/wiki/Fail2Ban-Setup
- Mailu's fail2ban documentation: https://mailu.io/1.9/faq.html#do-you-support-fail2ban

you would need:

1. a consistent location for authorization failures in logs
2. a consistent regular expression for failures (to make a filter)
3. a good action for failures (in mailu since it's containers it's slightly different) - to make the jail file
4. a good spot in the documentation to place it
5. a network to test the fail2ban rules with

**Comment by juanfont** [comment]
This can be implemented in a reverse proxy if needed.

**Comment by mathmaniac43** [comment]
Hello!

I am interested in hardening my Headscale instance as well. I am hosting it behind a Traefik reverse proxy, so I believe I could set up fail2ban or something like that in Traefik, which is great.

However, I am not sure HOW to do that, or specifically how to have Headscale pass along failures to authenticate to the reverse proxy to eventually decide to fail/block. Any guidance or ideas would be appreciated.

Thanks!

**Comment by phs78** [comment]
1. configure traefik to create an access log readable by fail2ban
2. create a fail2ban filter that catches failregex = ^<HOST> - - \[.*\] "GET /api/v1/apikey.*" 500 .* 
3. create a jail

I have this working. I just need to write it up and I'll share.

**Comment by numericOverflow** [comment]
> 1. configure traefik to create an access log readable by fail2ban
> 
>     2. create a fail2ban filter that catches failregex = ^ - - [._] "GET /api/v1/apikey._" 500 .*
> 
>     3. create a jail
> 
> 
> I have this working. I just need to write it up and I'll share.

@phs78 - you ever get around to sharing?  Thought it'd be smart to get headscale hooked up to fail2ban if possible, since I see a ton of IPs that constantly try to connect to my setup.

**Comment by kradalby** [comment]
A bit related but not directly, when potentially redoing the api in https://github.com/juanfont/headscale/issues/2305

We should make sure we just build in rate limiting from the start, nothing fancy, go has https://pkg.go.dev/golang.org/x/time/rate and we should just use that.
