### ISSUE TITLE
command ping higher not match command Tailscale ping

### ISSUE THREAD

**Issue by arrow2012** [juanfont/headscale#1529]
## Environment

- OS:
- Headscale version: v0.22.3
- Tailscale version: 1.46.1  ,1.48.0

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

headscale and tailscale-linux install on linux server A 
tailscale-macos install on macos B
derp install on linux server A

tailscale-macos IP : 10.66.0.1
tailscale-linux IP : 10.66.0.2

on tailscale-macos
% ./Tailscale ping 10.66.0.2       ping is 18

but direct ping 10.66.0.2 ping is 40 - 50
% ping 10.66.0.2 

<img width="926" alt="image" src="https://github.com/juanfont/headscale/assets/46478986/b3bfdaad-be2a-4ddd-9ad5-74f2dbfaae26">

10.66.0.1 route to 10.66.0.2 via DERP ,the derp install same with tailscale-linux ,the ping should not higher than 20

**Comment by arrow2012** [comment]
top view
<img width="704" alt="image" src="https://github.com/juanfont/headscale/assets/46478986/c346a04c-b1ff-41f9-8c8e-107a2653dc32">

**Comment by kyhwana** [comment]
This is probably due to the fact that the tailscale ping command is using a DERP server, which has a lower latency router between the two machines (via tailscale) than the two machines going direct (not via tailscale)
