### ISSUE TITLE
How to change standard port with script?

### ISSUE THREAD

**Issue by RobertusIT** [juanfont/headscale#1532]
## Bug description

I tried to install in my proxmox virtual machine an Headscale, without success, because my ISP, block a range of ports, so I can open only a specific range.

I need to use different ports. Is possibile? How?
I use the script to install it, with my duckdns domain, but fail in ssl because i can't setup differents ports, I guess.

## Environment

Ubuntu, last version from the script

**Comment by juanfont** [comment]
Can you please check our Discord channel for support? https://discord.com/channels/896711691637780480/896711692120129540
