### ISSUE TITLE
Please release a Headscale module for pfSense

### ISSUE THREAD

**Issue by ithakaa** [juanfont/headscale#1533]
Please release a Headscale module for pfSense

**Comment by cdestefano** [comment]
Not sure if you're aware, but this can be hosted anywhere that's publicly accessible.  Even behind a pfSense firewall.  

If you want to access your router / anything behind it in your tailnet, you can connect to your headscale instance out of the box with the tailscale plugin in pfSense.

**Comment by ithakaa** [comment]
I am aware thanks

**Comment by juanfont** [comment]
So what do what is the suggestion? A pfsense module to host headscale?

**Comment by ithakaa** [comment]
> So what do what is the suggestion? A pfsense module to host headscale?

Yes

So we can host a tailnet as a VPN on pfsense as we do with OpenVPN

**Comment by alijnclarke** [comment]
You'd typicaly use pfsense as a tailscale client, there's already a package for this that lets you expose subnets etc. Not sure it's a fantastic idea to run the headscale server pfsense.

**Comment by ithakaa** [comment]
> You'd typicaly use pfsense as a tailscale client, there's already a package for this that lets you expose subnets etc. Not sure it's a fantastic idea to run the headscale server pfsense.

Running a headscale server on pfsense, like OpenVPN, provides control of your tailnets.

I think it's a great idea and would love to see a model

**Comment by noseshimself** [comment]
And then OPNSense users will demand the same...

I'd suppose you ask the pfSense project for this. I put it into a jail on OPNSense without needing a plugin or a special version of the package in the OPNsense repositories. It is working out-of-the-box.

**Comment by ithakaa** [comment]
> And then OPNSense users will demand the same...
> 
> 
> 
> I'd suppose you ask the pfSense project for this. I put it into a jail on OPNSense without needing a plugin or a special version of the package in the OPNsense repositories. It is working out-of-the-box.

I'm not a OPNSense user so can't comment but if OPNSense has the ability to provision jails than wonderful

pfsense doesn't.

It's doesn't sound like you're interested which is fine however I personally, and professionally believe it's a great idea.

Thanks anyway

**Comment by nurailroaddev** [comment]
> > And then OPNSense users will demand the same...
> > I'd suppose you ask the pfSense project for this. I put it into a jail on OPNSense without needing a plugin or a special version of the package in the OPNsense repositories. It is working out-of-the-box.
> 
> Nobody is "demanding" anything, we're just making suggestions that would extend the reach of an already great project
> 
> I'm not a OPNSense user so can't comment but if OPNSense has the ability to provision jails than wonderful
> 
> pfsense doesn't.
> 
> It doesn't sound like you're interested which is fine however I personally, and professionally believe it's a great idea.
> 
> Thanks anyway

I get what you are saying 💯. I'd have thought these "coders" would be smart enough to read text. 🤣. Host not connect. As in, we currently host tailscale as an exit node on pfsense. Get a real router and quit using Asus 🤣🤣🤣.

TL:DR
Great suggestion. Crybaby crowd. Worse devs.

**Comment by kradalby** [comment]
Hi, we do not have capacity to maintain this, we are happy to receive help from someone who can and are willing to maintain this. I have marked this issue with "help wanted".
