### ISSUE TITLE
when use embedded DERP server, there are a lot of identical logs with "named node xxx no address" in tailscaled

### ISSUE THREAD

**Issue by lcuwx2016** [juanfont/headscale#1542]
## Bug description
When use embedded DERP server, there are **a lot of identical logs** in tailscaled such as:
```
Wed Sep  6 13:52:17 2023 daemon.err tailscaled[9755]: 2023/09/06 05:52:17 netcheck: netcheck.runProbe: named node "901" has no address
Wed Sep  6 13:52:44 2023 daemon.err tailscaled[9755]: 2023/09/06 05:52:44 netcheck: netcheck.runProbe: named node "901" has no address
Wed Sep  6 13:54:01 2023 daemon.err tailscaled[9755]: 2023/09/06 05:54:01 netcheck: netcheck.runProbe: named node "901" has no address
Wed Sep  6 13:54:27 2023 daemon.err tailscaled[9755]: 2023/09/06 05:54:27 netcheck: netcheck.runProbe: named node "901" has no address
Wed Sep  6 13:54:49 2023 daemon.err tailscaled[9755]: 2023/09/06 05:54:49 netcheck: netcheck.runProbe: named node "901" has no address
```
The part of config.yaml is like:
```
 76 derp:
 77   server:
 78     # If enabled, runs the embedded DERP server and merges it into the rest of the DERP config
 79     # The Headscale server_url defined above MUST be using https, DERP requires TLS to be in place
 80     enabled: true
 81 
 82     # Region ID to use for the embedded DERP server.
 83     # The local DERP prevails if the region ID collides with other region ID coming from
 84     # the regular DERP config.
 85     region_id: 901
 86 
 87     # Region code and name are displayed in the Tailscale UI to identify a DERP region
 88     region_code: "njc"
 89     region_name: "Nanjing City"
 90 
 91     # Listens over UDP at the configured address for STUN connections - to help with NAT traversal.
 92     # When the embedded DERP server is enabled stun_listen_addr MUST be defined.
 93     #
 94     # For more details on how this works, check this great article: https://tailscale.com/blog/how-tailscale-works/
 95     stun_listen_addr: "0.0.0.0:3478"
 96 
 97   # List of externally available DERP maps encoded in JSON
 98   urls:
 99     # - https://controlplane.tailscale.com/derpmap/default
100 
101   # Locally available DERP map files encoded in YAML
102   #
103   # This option is mostly interesting for people hosting
104   # their own DERP servers:
105   # https://tailscale.com/kb/1118/custom-derp-servers/
106   #
107   # paths:
108   #   - /etc/headscale/derp-example.yaml
109   paths:
110    # - /etc/headscale/custom_derp.yaml
111 
112   # If enabled, a worker will be set up to periodically
113   # refresh the given sources and update the derpmap
114   # will be set up.
115   auto_update_enabled: true
116 
117   # How often should we check for DERP updates?
118   update_frequency: 24h

```

## Environment

- OS: Ubuntu 22.04.LTS
- Headscale version: 0.22.3
- Tailscale version: 1.48.1

**Comment by flyzstu** [comment]
I had the exact same problem.

![image](https://github.com/juanfont/headscale/assets/94161727/50017e56-1a6d-455b-8dd1-80004b8786d4)

**Comment by juanfont** [comment]
Are you using a domain name for Headscale or your IP address?

**Comment by lcuwx2016** [comment]
I used a domain name.
![image](https://github.com/juanfont/headscale/assets/31233561/2b68f4b7-8c83-4b6f-9fe1-a22b409b5fe5)

**Comment by shilazi** [comment]
When I deploy with [fredliang/derper](https://hub.docker.com/r/fredliang/derper), the same log is output. After understanding the operation logic of [netcheck](https://github.com/tailscale/tailscale/blob/v1.48.1/net/netcheck/netcheck.go), now can explain this problem. If the server which running tailscaled, has an ipv6 address, the netcheck goroutine will also use ipv6  check derper. When [derper.yaml](https://github.com/juanfont/headscale/blob/main/derp-example.yaml) has an valid ipv6 or DNS response AAAA address with hostname, this [has no address] log will not output.

In other words, server is `vps1`, which tailscaled running on it, a derper is `derp1`

* `vps1` has ipv4, no ipv6
  * `derp1` has ipv4, no ipv6    -> 
  * `derp1` has ipv6, no ipv4    -> `has no address`
  * `derp1` has ipv4, has ipv6   -> 
* `vps1` has ipv6, no ipv4
  * `derp1` has ipv4, no ipv6    -> `has no address`
  * `derp1` has ipv6, no ipv4    -> 
  * `derp1` has ipv4, has ipv6   -> 
* `vps1` has ipv4, has ipv6
  * `derp1` has ipv4, no ipv6    -> `has no address`
  * `derp1` has ipv6, no ipv4    -> `has no address`
  * `derp1` has ipv4, has ipv6   -> 

It can be understood as the ipv4/ipv6 situation of `vps1`, then obtain the single-stack or dual-stack address of `derp1`. The log `has no address` can perhaps be expressed more clearly as `has no v4/v6 address`


* https://github.com/tailscale/tailscale/blob/v1.48.1/net/netcheck/netcheck.go#L822-L833
* https://github.com/tailscale/tailscale/blob/v1.48.1/net/interfaces/interfaces.go#L447-L495
* https://github.com/tailscale/tailscale/blob/v1.48.1/net/netcheck/netcheck.go#L486-L487
* https://github.com/tailscale/tailscale/blob/v1.48.1/net/netcheck/netcheck.go#L1559-L1643

**Comment by longregen** [comment]
I was able to suppress these warnings by setting `ipv4: none` or `ipv6: none` in the derp.map
