### ISSUE TITLE
How to have a reusable preauth key that does not expire?

### ISSUE THREAD

**Issue by bfontaine** [juanfont/headscale#1550]
## Why

I need to have access to the VPN from a CI container on Gitlab in order to install packages from a private registry. In order to do so, I created a dedicated node and a reusable preauth key for ephemeral nodes:

```bash
headscale --user ci-node preauthkeys create --ephemeral --reusable --tags tag:ci
```

The CI node installs Tailscale then uses the key to connect:
```bash
tailscale up --authkey="${TAILSCALE_AUTH_KEY}" --hostname="ci-$(cat /etc/hostname)" --login-server="${TAILSCALE_LOGIN_SERVER}" --accept-routes --timeout 15s
```
(where `TAILSCALE_AUTH_KEY` is the preauth key and `TAILSCALE_LOGIN_SERVER` the headscale host)

However the preauth key I created earlier did expire at some point. I don’t see any option to disable this; if I don’t pass `--expiration ...` it defaults to 1h.

## Description

A flag on the `preauthkeys create` command to create a preauth key that does not expire.

**Comment by kradalby** [comment]
You cannot, what you should do is programatically create new keys with the API or CLI tool as you need them.

Please also refer support issues to Discord and not the issue tracker. Thank you.

**Comment by comminutus** [comment]
I'd like to see support for this.  Creating new keys for ephemeral services after expiration seems tedious, especially if there are a good amount of them.

**Comment by quantumdecoherence** [comment]
+1 for this issue. Enforcing password rotation is rather 2000's security, and generates a tedious amount of work for larger deployments.

**Comment by fluential** [comment]
We need non expiring keys

**Comment by travisghansen** [comment]
Does it not work to simply set the expiry to `99y`? I've done this and it shows up correctly as expiring well into the future but not sure if something else would cause an issue there as I'm new to tailscale and headscale.

**Comment by C-Duv** [comment]
Setting a far expiration date is possible, but non-reusable token is blocking when an headless/unattended server/node has restarted and needs to re-connect to the tailnet no?
