### ISSUE TITLE
Outdated or confusing documentation regarding ACLs ?

### ISSUE THREAD

**Issue by Erwyn** [juanfont/headscale#1569]
Hello,

I was looking around the ACL's possibilities in Headscale and following discussions I had on Discord and my own tests I'm wondering if part of the documentation on Headscale is not outdate or confusing. It can also be that I don't understand them correctly.

There are mainly two points:

1. [This part of ACLs page](https://github.com/juanfont/headscale/blob/fb4ed95ff63b96249bef5c8070daac07f0e52016/docs/acls.md?plain=1#L8-L10) is implying that user borders exist when not using ACLs. Is this still really the case because from my tests, **even without ACLs** I can see the nodes from other users ? Or are there other *borders* that I don't understand and that are disabled when using ACLs ?
2. [This proposal](https://github.com/juanfont/headscale/blob/main/docs/proposals/001-acls.md) that is referenced on the site seems to be outdated in a sense that it as already been implemented in my understanding and actually the example of "what could be done if implemented" is the example of the ACLs documentation page now. Is it left here on purpose or should it be move away/marked as done ?

I'm willing to propose a simple pull request to address those two points but I wanted to check with you that I'm not understanding this backwards.

Thanks in advance,

**Comment by disconn3ct** [comment]
While the topic is ACL docs, the wiki opens confusingly:

> For instance, instead of referring to `users` when defining groups you must use `users` (which are the equivalent to user/logins in Tailscale.com).

(Emphasis mine) Don't use "users", instead you must use "users"..?


https://github.com/juanfont/headscale/blob/main/docs/acls.md
