### ISSUE TITLE
"TRC DNS configuration loaded" logs always printed to STDOUT

### ISSUE THREAD

**Issue by lgrn** [juanfont/headscale#1576]
## Bug description

After upgrading to v0.23.0-alpha1, I'm noticing this log is printed after every headscale command:

```
# headscale nodes list
2023-10-16T12:09:45Z TRC DNS configuration loaded dns_config={"ExitNodeFilteredSet":null,"ExtraRecords":[{"Name":"
(...)
```

After a few seconds this is then followed by the commands expected output. This looks like it was [added last month here](https://github.com/juanfont/headscale/blame/fb4ed95ff63b96249bef5c8070daac07f0e52016/hscontrol/types/config.go#L483) by @kradalby -- I guess my question is whether this is expected behavior (for example due to misconfiguration on my part) or a bug.

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

Run any `headscale` command on v0.23.0-alpha1

**Comment by mskram** [comment]
I have this issue in 0.23.0-alpha5 after upgrading from 0.22.3.

My dns_config section looks similar to the example.

In my case the text printed is: 

```
TRC DNS configuration loaded dns_config={"Nameservers":["1.1.1.1"],"Proxied":true,"Resolvers":[{"Addr":"1.1.1.1"}]}
```

**Comment by SuperSandro2000** [comment]
Please see #1939 for a fix
