### ISSUE TITLE
The headscale node status displays an error, showing offline but actually online.

### ISSUE THREAD

**Issue by doubletry** [juanfont/headscale#1577]
## Bug description

The `headscale node list` command shows that the status of all nodes is `offline`, but the tailscale nodes can be connected. When I restart the headscale service through `systemctl restart headscale.service`, the results will be updated to the `online` . However, after a period of time, all nodes gradually become `offline`.

## Environment

- OS: Windows 11, Ubuntu 22.04 and Ubuntu 20.04
- Headscale version: [v0.23.0-alpha1](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha1)
- Tailscale version:  v1.50.1

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by proitlab** [comment]
I experienced same condition. I have 2 nodes, pinged each other. But it shown offline with command headscale nodes list:

# headscale nodes list
2023-10-19T03:46:16Z TRC DNS configuration loaded dns_config={"ExitNodeFilteredSet":null,"Nameservers":["1.1.1.1"],"Proxied":true,"Resolvers":[{"Addr":"1.1.1.1"}]}
ID | Hostname              | Name                  | MachineKey | NodeKey | User   | IP addresses                  | Ephemeral | Last seen           | Expiration          | Online  | Expired
2  | backone-enterprise-01 | backone-enterprise-01 | [SkiQL]    | [SIpfN] | admins | 100.64.0.2, fd7a:115c:a1e0::2 | false     | 2023-10-17 09:55:19 | 0001-01-01 00:00:00 | offline | no
1  | Dedys-MacBook-Air     | dedys-macbook-air     | [liL3/]    | [ket1S] | admins | 100.64.0.1, fd7a:115c:a1e0::1 | false     | 2023-10-19 03:03:41 | 0001-01-01 00:00:00 | offline | no

# date
Thu Oct 19 03:46:17 UTC 2023

Looking into file hscontrol/types/nodes.go

// IsOnline returns if the node is connected to Headscale.
// This is really a naive implementation, as we don't really see
// if there is a working connection between the client and the server.
func (node *Node) IsOnline() bool {
	if node.LastSeen == nil {
		return false
	}

	if node.IsExpired() {
		return false
	}

	return node.LastSeen.After(time.Now().Add(-KeepAliveInterval))
}

It seem table "nodes" field "last_seen" is not updated properly.

**Comment by proitlab** [comment]
Some more information from headscale logs:

headscale-latest.1.muxggm8plvj1@server3.saltis.id    | 2023-10-19T04:06:41Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=Dedys-MacBook-Air node_key=91eb754ac8427b8137720c11f3a8accf612582ba62dfd2ada00549034901ea25 noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.muxggm8plvj1@server3.saltis.id    | 2023-10-19T04:07:05Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.muxggm8plvj1@server3.saltis.id    | 2023-10-19T04:07:19Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true


It seems poll.go is not receiving KeepAlived message from nodes.

**Comment by proitlab** [comment]
Fix the issue. I am running headscale behind traefik. My configuration traefik set with minimal TLS version 1.3. While tailscale send TLS version 1.2. After update traefik configuration, to minimal TLS 1.2, I show this in headscale logs:

headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC PollNetMapHandler called handler=NoisePollNetMap
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC src/headscale/hscontrol/poll_noise.go:34 > Headers headers={"Accept-Encoding":["gzip"],"Content-Length":["1272"],"User-Agent":["Go-http-client/2.0"]}
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z DBG A node sending a MapRequest with Noise protocol handler=NoisePollNetMap node=Dedys-MacBook-Air
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:79 > Received endpoint update endpoints=["192.168.88.237:22545","175.158.54.120:12263","175.158.54.120:33547","175.158.54.120:12125","175.158.54.120:12128","175.158.54.120:52797","175.158.54.120:52798","192.168.20.193:53511","192.168.168.20:53511","192.168.192.99:53511"] node=Dedys-MacBook-Air node_key=91eb754ac8427b8137720c11f3a8accf612582ba62dfd2ada00549034901ea25 noise=true omitPeers=true readOnly=false stream=false
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC updating routes advertisedRoutes={} currentRoutes=[] node=Dedys-MacBook-Air
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC src/headscale/hscontrol/notifier/notifier.go:63 > acquiring lock to notify type=1
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC src/headscale/hscontrol/notifier/notifier.go:77 > sending update ignoring=["9622f7fce7d1a046d3f0dec4a45b09aa2a369a6543b9541dba60dcee7a531541"] machine=cc373add152685d3dee371b5895417eeed170d0af928f92275673cae914b5a06
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC src/headscale/hscontrol/notifier/notifier.go:77 > sending update ignoring=["9622f7fce7d1a046d3f0dec4a45b09aa2a369a6543b9541dba60dcee7a531541"] machine=4a48902e58643a7bbb07dc8e7a1d4dae69e280f0e1612ec606f0a0710fa2d81b
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z TRC src/headscale/hscontrol/notifier/notifier.go:65 > releasing lock, finished notifing type=1
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Received update node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Received update node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Sending PeerChanged MapResponse node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Sending PeerChanged MapResponse node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:339 > update sent node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true timeSpent=0.921334
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:339 > update sent node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true timeSpent=0.914151
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:30Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:37Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:38Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:35:38Z INF src/headscale/hscontrol/poll.go:33 > Waiting for update on stream channel node=Dedys-MacBook-Air node_key=91eb754ac8427b8137720c11f3a8accf612582ba62dfd2ada00549034901ea25 noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC PollNetMapHandler called handler=NoisePollNetMap
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC src/headscale/hscontrol/poll_noise.go:34 > Headers headers={"Accept-Encoding":["gzip"],"Content-Length":["1272"],"User-Agent":["Go-http-client/2.0"]}
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z DBG A node sending a MapRequest with Noise protocol handler=NoisePollNetMap node=Dedys-MacBook-Air
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:79 > Received endpoint update endpoints=["192.168.88.237:22545","175.158.54.120:52985","175.158.54.120:12125","175.158.54.120:52798","175.158.54.120:12128","175.158.54.120:52797","175.158.54.120:12263","192.168.20.193:53511","192.168.168.20:53511","192.168.192.99:53511"] node=Dedys-MacBook-Air node_key=91eb754ac8427b8137720c11f3a8accf612582ba62dfd2ada00549034901ea25 noise=true omitPeers=true readOnly=false stream=false
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC updating routes advertisedRoutes={} currentRoutes=[] node=Dedys-MacBook-Air
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC src/headscale/hscontrol/notifier/notifier.go:63 > acquiring lock to notify type=1
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC src/headscale/hscontrol/notifier/notifier.go:77 > sending update ignoring=["9622f7fce7d1a046d3f0dec4a45b09aa2a369a6543b9541dba60dcee7a531541"] machine=cc373add152685d3dee371b5895417eeed170d0af928f92275673cae914b5a06
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC src/headscale/hscontrol/notifier/notifier.go:77 > sending update ignoring=["9622f7fce7d1a046d3f0dec4a45b09aa2a369a6543b9541dba60dcee7a531541"] machine=4a48902e58643a7bbb07dc8e7a1d4dae69e280f0e1612ec606f0a0710fa2d81b
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z TRC src/headscale/hscontrol/notifier/notifier.go:65 > releasing lock, finished notifing type=1
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:33 > Received update node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:33 > Received update node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:33 > Sending PeerChanged MapResponse node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:33 > Sending PeerChanged MapResponse node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:339 > update sent node=backone-enterprise-01 node_key=488a5f341743b6d18269048c82dd79b9c025694cfd8124f1c252ced881d4ba1c noise=true omitPeers=false readOnly=false stream=true timeSpent=1.130774
headscale-latest.1.m5snv7itppzp@server1a.saltis.id    | 2023-10-19T05:36:31Z INF src/headscale/hscontrol/poll.go:339 > update sent node=DESKTOP-PDOIGN9 node_key=c36332ffa81093d51f818daf3d7077ea60e3835d92ed32833a9ca6b7bd34ed3e noise=true omitPeers=false readOnly=false stream=true timeSpent=1.177364

Nodes:
Dedys-MacBook-Air -> Tailscale 1.51.0
Others -> Tailscale 1.50.1


headscale nodes list:

# headscale nodes list
2023-10-19T05:43:09Z TRC DNS configuration loaded dns_config={"ExitNodeFilteredSet":null,"Nameservers":["1.1.1.1"],"Proxied":true,"Resolvers":[{"Addr":"1.1.1.1"}]}
2023-10-19T05:43:10Z TRC DNS configuration loaded dns_config={"ExitNodeFilteredSet":null,"Nameservers":["1.1.1.1"],"Proxied":true,"Resolvers":[{"Addr":"1.1.1.1"}]}
2023-10-19T05:43:10Z DBG Setting timeout timeout=5000
2023-10-19T05:43:10Z DBG HEADSCALE_CLI_ADDRESS environment is not set, connecting to unix socket. socket=/var/run/headscale/headscale.sock
2023-10-19T05:43:10Z TRC src/headscale/cmd/headscale/cli/utils.go:138 > Connecting via gRPC address=/var/run/headscale/headscale.sock
ID | Hostname              | Name                  | MachineKey | NodeKey | User   | IP addresses                  | Ephemeral | Last seen           | Expiration          | Online  | Expired
2  | backone-enterprise-01 | backone-enterprise-01 | [SkiQL]    | [SIpfN] | admins | 100.64.0.2, fd7a:115c:a1e0::2 | false     | 2023-10-19 05:28:37 | 0001-01-01 00:00:00 | offline | no
3  | DESKTOP-PDOIGN9       | desktop-pdoign9       | [zDc63]    | [w2My/] | admins | 100.64.0.3, fd7a:115c:a1e0::3 | false     | 2023-10-19 05:28:36 | 0001-01-01 00:00:00 | offline | no
1  | Dedys-MacBook-Air     | dedys-macbook-air     | [liL3/]    | [ket1S] | admins | 100.64.0.1, fd7a:115c:a1e0::1 | false     | 2023-10-19 05:28:37 | 0001-01-01 00:00:00 | offline | no

Still showing offline.

**Comment by shidoh** [comment]
same problem. - `Waiting for update on stream channel node`
nodes are shown offline
the network is working, but it is not possible to use exit nodes, clients consider them to be offline

0.23.0-alpha1
nginx reverse proxy configured according to documentation

**Comment by kradalby** [comment]
Should be addressed as part of #1564
