### ISSUE TITLE
API interface for start preauthkeys not set expiration properly

### ISSUE THREAD

**Issue by proitlab** [juanfont/headscale#1579]
I am trying to integrate Headscale API v1 into our internal application. In creation new preauth keys, I noticed something in preauth expiration field.

## Bug description
I created preauthkeys via HTTPS with POST method to https://apiurl/api/preauthkeys with json body

body = {
'user': 'admin',
'reusable': false,
'ephemeral': false
}

The respond:

{'preAuthKey': {'user': 'admins', 'id': '3', 'key': '0a7e0ebbf68709168fb4f53fa61f82c10e70437ee4e21a6c', 'reusable': False, 'ephemeral': False, 'used': False, 'expiration': '0001-01-01T00:00:00Z', 'createdAt': '2023-10-18T07:58:12.643916467Z', 'aclTags': []}}

I noticed:
'expiration': '0001-01-01T00:00:00Z'

When I created preauthkeys using headscale command in container, the expiration field is properly populated, which is 60 minutes later, even without specifying expiration paramater in command line:

headscale preauthkeys create -u admins

These are all my preauthkeys:
{'preAuthKeys': [{'user': 'admins', 'id': '1', 'key': '44f5dce35262edd4780f05b40968205c83b9a5a3743f3c82', 'reusable': False, 'ephemeral': False, 'used': True, 'expiration': '2023-10-17T10:47:13.729136Z', 'createdAt': '2023-10-17T09:47:13.731139Z', 'aclTags': []}, {'user': 'admins', 'id': '2', 'key': '38dea3a1f04b83db9dfc22ec6d19f9d9d3ff7dcfc488723c', 'reusable': True, 'ephemeral': False, 'used': True, 'expiration': '2023-10-17T10:54:53.951718Z', 'createdAt': '2023-10-17T09:54:53.954325Z', 'aclTags': []}, {'user': 'admins', 'id': '3', 'key': '0a7e0ebbf68709168fb4f53fa61f82c10e70437ee4e21a6c', 'reusable': False, 'ephemeral': False, 'used': False, 'expiration': '0001-01-01T00:00:00Z', 'createdAt': '2023-10-18T07:58:12.643916Z', 'aclTags': []}]}

## Environment
- postgresdb
- docker

- OS: Ubuntu 22.04
- Headscale version: 0.23.0-alpha

## To Reproduce
- Create preauthkeys via API with body not including expiration field.

**Comment by BeyondEvil** [comment]
Can confirm.

```sh
An updated version of Headscale has been found (0.23.0-alpha2 vs. your current v0.22.3). Check it out https://github.com/juanfont/headscale/releases
ID | Hostname           | Name                        | MachineKey | NodeKey | User    | IP addresses                  | Ephemeral | Last seen           | Expiration          | Online  | Expired
1  | adguard.domain.net | adguard.domain.net          | [Q1UzQ]    | [YUdWe] | adguard | 100.64.0.1, fd7a:115c:a1e0::1 | false     | 2024-01-02 01:08:36 | 2024-01-02 01:08:37 | offline | yes
2  | adguard.domain.net | adguard.domain.net-smqnci6a | [rDYHo]    | [CCf4Y] | adguard | 100.64.0.2, fd7a:115c:a1e0::2 | false     | 2024-01-02 01:38:04 | 0001-01-01 00:00:00 | online  | no
```

Key was created with:
`headscale preauthkeys create --user adguard --expiration 2d --reusable`

Happy to share more information upon request.

**Comment by BeyondEvil** [comment]
I believe this is still relevant.

**Comment by fluential** [comment]
Seems relevant to me

**Comment by BeyondEvil** [comment]
Still relevant afaict.

**Comment by yeyeoke** [comment]
This is still happening in beta2.

**Comment by kradalby** [comment]
This isnt really a bug, it is intentional, the CLI has a default 1h expiry, but the API does not have a default and it is the callers responsibility to set the expiry. 
The field to set the expiry is available in the API: https://github.com/juanfont/headscale/blob/main/proto/headscale/v1/preauthkey.proto#L23

As for "should the CLI have a default and not the API", it depends, I do not think there is a right answer here, the way I see it is:

The API is a clean slate and you tell it exactly what you want it to do, and it is from there, deterministic. 

The CLI _implements_ a client using the API, and in the CLI we have made the decision to set a default for the CLI to improve the user experience of the tool (also allowing you to define it in a "duration from now" instead of a timestamp).

**Comment by kradalby** [comment]
@BeyondEvil I think your issue is separate to the posted one, please create a separate issue for it. 
Please include if this is a regression between 0.22.3 and 0.23.x or if it has been present the whole time.
