### ISSUE TITLE
I have set up two users. But the computers in the two users can still communicate with each other. Am I setting it wrong?

### ISSUE THREAD

**Issue by zfung03** [juanfont/headscale#1593]
![Snipaste_2023-11-08_12-09-03](https://github.com/juanfont/headscale/assets/51111549/71d8c474-1ece-4d58-84f6-8481209adf08)

I have set up two users. But the computers in the two users can still communicate with each other. Am I setting it wrong?

## Environment

- OS:
- Headscale version:
- Tailscale version:

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by madejackson** [comment]
You should fill out the Environment-Infos to receive help.

1.  Did you setup acl's? As far as my experience is that there are no access restriction as long as you did not setup acl's.
2. Are you on v0.23? ACL's are somewhat broken in the alpha in my experience.

**Comment by n4zim** [comment]
For context, ACLs should be configured this way : https://headscale.net/acls/#acl-setup
