### ISSUE TITLE
headscale-node shows offline

### ISSUE THREAD

**Issue by MilkTeaNo7** [juanfont/headscale#1599]
``One question
I deployed the headscale server and used the Tailscale client, and it worked fine in another environment
But in the current environment
	It can connect, and the nodes can communicate with each other
	But when I check with 'headscale node ls', all nodes are shown as offline.

`server_url: http://headscale.com:58344
listen_addr:  0.0.0.0:58344
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false
private_key_path: /var/lib/headscale/private.key
noise:
  private_key_path: /var/lib/headscale/noise_private.key
ip_prefixes:
  - 100.64.0.0/10
derp:
  server:
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths:
       - /etc/headscale/derp.yaml
  auto_update_enabled: true
  update_frequency: 24h
disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""
tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"
tls_cert_path: ""
tls_key_path: ""
log:
  format: text
  level: info
acl_policy_path: ""
dns_config:
  override_local_dns: false
  nameservers:
     - 119.29.29.29
  domains: []
  magic_dns: true
  base_domain: example.com
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
logtail:
  enabled: false
randomize_client_port: true`

**Comment by kradalby** [comment]
Which version of Headscale?

**Comment by TymanWasTaken** [comment]
I can also reproduce on my own headscale server: the last seen date for all nodes doesn't seem to update unless I restart tailscaled to force them to re-connect to the headscale server. All connections work normally, just the last seen date and online status are bugged. The logs are also spammed with the following, so this isn't just a visual issue:
```log
INF node offline, finding a new primary subnet node=<nodename> prefix=<subnet>
2023-11-15T18:29:42Z WRN no alternative primary route found node=<nodename> prefix=<subnet>
```

My headscale server is currently the running latest main commit, with 2 OIDC-related PRs manually merged in

**Comment by nathan-march** [comment]
See https://github.com/juanfont/headscale/pull/1564

**Comment by Sh4d** [comment]
See https://github.com/juanfont/headscale/pull/1564

**Comment by MilkTeaNo7** [comment]
> 我还可以在我自己的 headscale 服务器上重现：所有节点的最后一次看到的日期似乎不会更新，除非我重新启动 tailscaled 以强制它们重新连接到 headscale 服务器。所有连接均正常工作，只是上次查看日期和在线状态有问题。日志中还充斥着以下内容，因此这不仅仅是一个视觉问题：
> 
> ```
> INF node offline, finding a new primary subnet node=<nodename> prefix=<subnet>
> WRN no alternative primary route found node=<nodename> prefix=<subnet>
> ```
> 
> 我的 headscale 服务器当前正在运行最新的主提交，其中手动合并了 2 个与 OIDC 相关的 PR
