### ISSUE TITLE
Main branch - server cannot connect to itself

### ISSUE THREAD

**Issue by Nickiel12** [juanfont/headscale#1633]
## Bug description

I have been having the issues described in issue #1572 , so I switched to the recommended PR (#1564) and I was able to re-register all of my devices, except for the server itself. I then switched to `:main` to see if that fixed the issue, and after some troubleshooting in the discord, rolled back to the latest stable (0.22.3) which then fixed the issue. 

The issue was that when I ran `tailscale up --login-server https://<domain>` and navigating to the provided URL and running the supplied command, either the node would successfully register, but tailscale would not connect - giving the "go to URL to authenticate" message -, or headscale would fail to add the nodes with the error 
```sh
github.com/juanfont/headscale/cmd/headscale/cli/utils.go:141 > Could not connect: context deadline exceeded error="context deadline exceeded"
```

## Environment

- Tested using `:main 0153e26392506ad389aca2f633e3b638644baa1c` and kradalby:1561-online-issue . Issue not preset in stable 0.22.3
- Tailscale 1.54.0, go version: go1.21.4
- Linux, NixOS 24.05 with unstable nixpkgs
- 6.1.62
- I don't know what configuration parameters would be relevant 

```
headscale nodes register output:

2023-12-03T13:30:42-08:00 FTL github.com/juanfont/headscale/cmd/headscale/cli/utils.go:141 > Could not connect: context deadline exceeded error="context deadline exceeded"
```

I do use nginx to proxy traffic to headscale, however I'm not sure if that counts as a reverse proxy, and this issue was not present when running on the latest stable

## To Reproduce
Install headscale on the latest `:main` version, and try to register the same device running headscale as a node.

**Comment by kradalby** [comment]
[0.23.0-alpha2](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha2) addresses a series of issues with node synchronisation, online status and subnet routers, please test this release and report back if the issue still persist.

**Comment by Nickiel12** [comment]
The host running headscale is able to connect its tailscale client to the server now.
