### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dsbt01** [juanfont/headscale#1648]
## Bug description

when trying to start the docker container, I am getting this error message:

headscale-headscale-1  | 2023-12-11T17:56:51Z INF No private key file at path, creating... path=
headscale-headscale-1  | 2023-12-11T17:56:51Z FTL go/src/headscale/cmd/headscale/cli/server.go:21 > Error initializing error="failed to read or create private key: failed to save private key to disk: open : no such file or directory"

I have setup the yml file like
volumes:
      - ./config:/etc/headscale/
      - ./data:/var/lib/headscale

I am not sure what the issue is since I have created the folders as requested in docker/headscale/config and data folders and I am runnng the process as root.  I really do not know why this is giving this error. 
## Environment
fresh copy of ubuntu latest LTS

**Comment by kradalby** [comment]
Hi,

Please use Discord for support requests.

If you are using 0.22.3, make sure you look at the example config from the correct git tag and not `main`.

If you are using `main` or the new alpha, make sure you have set the derp.server.private key if you have that enabled.
