### ISSUE TITLE
Incorrect example path in ACL documentation

### ISSUE THREAD

**Issue by rickr** [juanfont/headscale#1661]
Line 6 in `docs/acls.md` states:

`Please check https://tailscale.com/kb/1018/acls/, and `./tests/acls/` in this repo for working examples.`

https://github.com/juanfont/headscale/blob/6049ec758ca46b5c6ee7abba4f3d472fb1e2ffa6/docs/acls.md?plain=1#L6

However ./tests/acls does not exist. Perhaps it's referencing `integration/acl_test.go`?

**Comment by feurig** [comment]
Why is this closed? The linked references to sample acls still do not exist.

**Comment by feurig** [comment]
> Why is this closed? The linked references to sample acls still do not exist.

It's one thing to say We aren't going to fix this and remove or update the link. 
There are no polite words for ignoring it for 3 years and not correcting the link.
