### ISSUE TITLE
When using embedded DERP server, how to verify the client

### ISSUE THREAD

**Issue by hausen1012** [juanfont/headscale#1662]
Is it supported now? I don't want others to use my derp server.

thanks

**Comment by pope-L** [comment]
我也想知道呢

**Comment by yqs112358** [comment]
There are existing PR https://github.com/juanfont/headscale/pull/2046 which supports this. It will be reviewed in future I think.
Currently you can deploy an official derp server (for example, docker version here https://github.com/fredliang44/derper-docker) until the maintainer has time to review that PR.
