### ISSUE TITLE
config-example.yaml is missing private key path

### ISSUE THREAD

**Issue by Turney1337** [juanfont/headscale#1678]
After trying to install headscale for a couple of hours without any success, using native Ubuntu installation as well as docker, running behind a reverse proxy and without it, I found what seems to be a missing line in the official config-example.yaml by chance via another config file provided by some person on Youtube:

```
# Private key used to encrypt the traffic between headscale
# and Tailscale clients.
# The private key file will be autogenerated if it's missing.
#
private_key_path: /var/lib/headscale/private.key
```

**Comment by masterwishx** [comment]
you should use config from lasted version

**Comment by kradalby** [comment]
We mention this in the readme

> Note: Always select the same GitHub tag as the released version you use to ensure you have the correct example configuration and documentation. The main branch might contain unreleased changes.

if you are trying to install 0.22.3, you need to select that tag as that private key was removed in main in preparation for 0.23.0
