### ISSUE TITLE
add linux/arm64 build

### ISSUE THREAD

**Issue by vielmetti** [juanfont/headscale#168]
This issue tracks work to build headscale for arm64 and to test
it on the usual suspects for that platform:  Raspberry Pi 3/4
with 64-bit OS, Ampere, Graviton2, and the like.

I think it might be as simple as adding a stanza to the 
goreleaser code, at first glance.

**Comment by juanfont** [comment]
Done! 

Will come in 0.10.3

**Comment by juanfont** [comment]
Hey @vielmetti https://github.com/juanfont/headscale/releases/tag/v0.10.3

Can you confirm they work? I don't have any arm64 machine...

**Comment by vielmetti** [comment]
I'll confirm correct operations as soon as I bring up a network, @juanfont  - hopefully as soon as this weekend.

**Comment by vladvasiliu** [comment]
This seems to work.

Don't have the time to do extensive testing, but I could create a namespace and start the server, so I guess the SQLite issue is solved.
