### ISSUE TITLE
Support for 2fa?

### ISSUE THREAD

**Issue by Hans-kloss2** [juanfont/headscale#1680]
Is it possible to add a simple toggleable 2FA (Two-Factor Authentication) number request for clients each time they try to connect to VPN?

This was raised once here, so maybe this feature is already implemented and I overlooked it?:  Support 2FA / RADIUS or LDAP? #125

**Comment by juanfont** [comment]
The solution here is using a OIDC provider, with 2FA enforcement. Like Tailscale SaaS does :)
