### ISSUE TITLE
Headscale CLI reaching out to Github servers on every request

### ISSUE THREAD

**Issue by jtweaver** [juanfont/headscale#1693]
## Bug description

On every use of the `headscale` command, there appears to be a call to GitHub servers (iP 140.82.113.5, for example).

If I block egress for the headscale node, `headscale` commands hang for 30 seconds or so. I assume it's waiting for some response from GitHub before running the command.

What is this for? Can it be turned off?

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

## To Reproduce

Run a `headscale` command with egress disabled.

**Comment by kradalby** [comment]
This is likely the check to see if there is a new version available, you can turn this off:

https://github.com/juanfont/headscale/blob/main/config-example.yaml#L130
