### ISSUE TITLE
headscale server list nodes ,one node display offline,but other node

### ISSUE THREAD

**Issue by pope-L** [juanfont/headscale#1717]
why headscale server list nodes ,one node display offline,but other node can connect to the offline nodes

**Comment by pope-L** [comment]
lastest
headscale 0.23.0-a3
But it only occasionally displays this on the server, and that node is actually online normally.
但只是偶尔在服务端显示这个，那个节点其实是正常在线的

**Comment by cg31** [comment]
Maybe it was not fixed in 0.23.0, it is still old.

You can try the main branch code.

**Comment by pope-L** [comment]
> Maybe it was not fixed in 0.23.0, it is still old.
> 
> You can try the main branch code.

Thanks.
