### ISSUE TITLE
ACLs ?

### ISSUE THREAD

**Issue by szzylph** [juanfont/headscale#1718]
Hello, does headscale ACLs support control access based on the original IP between the site and the site subnet?
 A site has installed only one client to act as a gateway.

**Comment by lgrn** [comment]
Can you please clarify with example IPs and topology what you mean by "the original IP between the site and the site subnet"? What do you want to achieve?

**Comment by GoodiesHQ** [comment]
If you are using 2 headscale nodes to advertise local routes to one another, then you can add hosts in the ACL file. You can use CIDR notation to represent an IP or network directly in the `policies` or you can set `hosts` entries to IP's and refer to those in the ACL.

    {
      "action": "accept",
      "src": ["group:dev"],
      "dst": ["10.20.0.0/16:443,5432", "router.internal:0"]
    },

**Comment by kradalby** [comment]
Hi, please post question like this to Discord. It is better for support requests.
