### ISSUE TITLE
Add reload and test config commands

### ISSUE THREAD

**Issue by 0xcd0e** [juanfont/headscale#173]
Like the `nginx -t` command, it would be nice to verify the config (config.json, derp map, acl) prior to loading it.
Also, like `nginx -s reload`, it would be nice to reload the configuration during runtime without having to restart the service.

**Comment by juanfont** [comment]
I see the point of this, but I reckon we should develop first an internal API to communicate the CLI with the running service.

Also, bear in mind that given how Tailscale works, restarting the service does not break the connectivity of the nodes.

**Comment by juanfont** [comment]
You mean the current AMAZING state of the project 🤣

**Comment by kradalby** [comment]
We should handle signals, so we can do what "traditional" unix apps does and reload the configfile, acls etc on `HUP` and do graceful shutdown on `INT`, `KILL`, etc.

**Comment by kradalby** [comment]
Adding this support for ACLs in #601, in addition to a bit more graceful signal handling for shutdown.

Config reload will have to sit for a bit more, I think we need to do a few rounds of cleanups in the config handling first, to decouple it so this is possible.
