### ISSUE TITLE
Verify all database connections are closed when process is killed

### ISSUE THREAD

**Issue by TotoTheDragon** [juanfont/headscale#1747]
## Why

SQLite sometimes has trouble with locks. This often occurs when there was a connection being used while the process is killed.

## Description

Verify that on all ways of exiting an application the database connections are closed properly and implement where lacking

**Comment by ohdearaugustin** [comment]
This issue can be tested. Please add more information like which version on which system. Installed with docker or without. etc.

With which configuration can this issue be recreated.

**Comment by RainrZufall** [comment]
> This issue can be tested. Please add more information like which version on which system. Installed with docker or without. etc.
> 
> With which configuration can this issue be recreated.

I have the same problem.
I use Ubuntu, Docker and the current stable release image.

It always occurs when, for example, I have to restart the server because of a kernel update or Docker is being updated.
I then have to manually restart the container again using “docker restart headscale” so that it works again.

**Comment by kradalby** [comment]
This is a fair concern, we should check the shutdown logic.

**Comment by kradalby** [comment]
So I've looked into this a bit, and SIGKILL (signal 9) cannot be trapped in Go, I think that is the main "missing" signal that we could receive that isnt handled, but there is no way to also do it. I'm not sure if there are any other situation within the code as of now.

**Comment by TotoTheDragon** [comment]
Seems like this issue only occurs when containers are killed and restart within the sqlite lock timeout. Cannot do anything to fix this, so I propose we close this @kradalby

**Comment by kradalby** [comment]
Ok, let's fix the lock instead
