### ISSUE TITLE
Config is not migrated properly

### ISSUE THREAD

**Issue by TotoTheDragon** [juanfont/headscale#1758]
## Bug description

When upgrading to the new version v0.23.0-alpha4, the config is not migrated accordingly. This causes issues with starting up until the config migration is done by hand.

## Environment

- OS: N/A
- Headscale version: v0.23.0-alpha4
- Tailscale version: N/A

## To Reproduce

1. Set up a v0.23.0-alpha3 install.
2. Now upgrade to v0.23.0-alpha4.
3. When starting headscale it will give an error.

Known affected fields:
- db_type -> database.type
- db_path -> database.sqlite.path

- Most likely all other database fields

## How to resolve
1. Accept that config is not migrated automatically and instead write a HOW-TO-UPGRADE within the changelog.
OR
2. Fix config migration

I personally would choose option 1 to avoid more problems

**Comment by kradalby** [comment]
The config should have aliases so I'll try to investigate why they don't work, this should be a non breaking change

**Comment by kradalby** [comment]
hmm, you have a good point, 0.23 already has a lot of breaking changes, so might as well rip of the plaster and make all change.

**Comment by troycarpenter** [comment]
Just another question...is the database also supposed to be migrated as well?  My system accidentally "upgraded" to the 2.3-alpha4 but the database didn't appear to be migrated either, in addition to the config not migrating either.  Even after the config was changed to the new format, no nodes were in the database and every device generated a new key.  (reverting everything to 0.22.3 worked).

**Comment by TotoTheDragon** [comment]
> Just another question...is the database also supposed to be migrated as well? My system accidentally "upgraded" to the 2.3-alpha4 but the database didn't appear to be migrated either, in addition to the config not migrating. Even after the config was changed to the new format, no nodes were in the database and every device generated a new key. (reverting everything to 0.22.3 worked).

If you are using postgres there is an issue rn

**Comment by troycarpenter** [comment]
I'm use sqlite3.  But honestly I don't expect alpha level software to do those migrations. I would expect later in Beta when all the database changes are shaken out, then write a conversion routine.
