### ISSUE TITLE
headscale crashes with OOM when sqlite path is ommited

### ISSUE THREAD

**Issue by SuperSandro2000** [juanfont/headscale#1761]
## Bug description

When ommiting database.sqlite.path from the config, headscale doesn't properly fallback to `/var/lib/headscale/db.sqlite` and instead crash loops with the following error:

```
Feb 15 23:54:38 hydrogen headscale-start[2491519]: 2024-02-15T23:54:38+01:00 FTL github.com/juanfont/headscale/cmd/headscale/cli/server.go:21 > Error initializing error="unable to open database file: out of memory (14)"
```

## Environment

- OS: NixOS unstable
- Headscale version: 0.23.0-alpha4
- Tailscale version: 1.58.2

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by Nickiel12** [comment]
This issue appeared again in alpha-8. I was getting a "out of memory" error, until I specified the full path as shown by OP.

**Comment by aqxa1** [comment]
I've still got the issue with alpha-12. Setting `sqlite` instead of `sqlite3` worked around the problem, although I'm not sure how they differ.
