### ISSUE TITLE
Impossible to change server URL on firetv stick

### ISSUE THREAD

**Issue by ndx1905-github** [juanfont/headscale#1776]
## Bug description
To set up the android client you are required to click multiple times on the burger icon until it’s possible to add the head scale server URL instead of the Tailscale one. This requires to be able to click on the burger go back click again go back etc.  
this gesture is impossible on a firetv stick as you only have a remote that lets you click but when you go back you’re taken out of the app to the app launcher. If you click again you still are at the same place. If you close the app and redo the burger button it only counts as one. 

## Environment

Latest version of Tailscale from f droid 1.58.2
FireTV OS 6.2.8.1

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

headscale works with other devices. Android client just can’t show the server URL

**Comment by TotoTheDragon** [comment]
@ndx1905-github This is not an issue with headscale, but with the tailscale client. I would recommend creating a bug report in their repository https://github.com/tailscale/tailscale/issues

**Comment by TotoTheDragon** [comment]
@kradalby please close
