### ISSUE TITLE
improve error message and document that the ipv6 prefix is now required

### ISSUE THREAD

**Issue by christian-heusel** [juanfont/headscale#1785]
## Bug description

When missing the ipv6 section on the just relased [v0.23.0-alpha5](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5) a confusing error is printed:
```
Failed to get headscale configuration error="netip.ParsePrefix(\"\"): no '/'"
```

## Environment

- OS: deployed via docker
- Headscale version: v0.23.0-alpha5

Old config:
```yaml
ip_prefixes:
  - 100.64.0.0/10
```
New config:
```yaml
prefixes:
  # errors without v6 or when v6 is empty
  v6: fd7a:115c:a1e0::/48
  v4: 100.64.0.0/10
```

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

## To Reproduce

Migrate the config ip prefix from the format pre v0.23.0-alpha4 to v0.23.0-alpha5.
With alpha5 it is required that a ipv6 shall be specified and [after discussion on discord](https://discord.com/channels/896711691637780480/896711692120129540/1209133122566881360) this was declared a feature. Now that it is required it should be documented and the the error message also could use some improvement so people who face this during migration are not too confused (kradalby said I should open an issue about this small improvement).

**Comment by wu0lei** [comment]
The config.yaml file format is updated and the error disappears after modification.

**Comment by x86dev** [comment]
Thanks for bringing this bug up, was scratching my head as well what's wrong with my config ...yeah, that indeed should be documented or handled better.

**Comment by BJorah** [comment]
I also encountered this problem when I use "headscale namespace list"

**Comment by adamk** [comment]
I'm having a similar issue on v0.24.0-beta.2.

Error initializing error="failed to load configuration while creating headscale instance: 
no IPv4 or IPv6 prefix configured, minimum one prefix is required"

I tried using this format in my config file:

`prefixes:
  v6:fd7a:115c:a1e0::/48
  v4:100.64.0.0/10 # Default IP prefix for connected devices`
