### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by ruzko** [juanfont/headscale#1787]
## Why
Defined Networks (Nebula) just published a [blogpost with various benchmarks](https://www.defined.net/blog/nebula-is-not-the-fastest-mesh-vpn/) for Nebula, Tailscale, ZeroTier and Netmaker.
They'll publish their testing method (already published some `iperf3` commands) in a git repo soon, and are open to testing other mesh networks as well.

To make the decision to deploy Headscale more informed; knowing the perfomance (especially compared to Tailscale) would be good.
I don't know whether Headscale devs use systematic performance testing to guide development already, but if not, doing so might be a good idea.
Also, it'd be neat to see how Headscale stacks up against the alternatives :)

## Description

Benchmark Headscale and alternatives in a systematic manner, publish results.
Maybe include performance testing in CI pipeline?

**Comment by juanfont** [comment]
Although I very much like the benchmark, I am not sure if it would really add value on top of what the Tailscale benchmark already does.

We are using the clients from Tailscale. The performance will be 1:1.
