### ISSUE TITLE
Servers IBM AIX powerpc

### ISSUE THREAD

**Issue by sysbisa** [juanfont/headscale#1788]
Hello dears.

Can you help me know if headscale works on IBM AIX servers?

They are PowerPC architecture servers.

Thank you so much.

**Comment by kradalby** [comment]
I would assume you can compile it yourself and run it, but I do not think we will start to provide binaries or official support for it.

**Comment by kradalby** [comment]
I'm going to close this as we will not add the architecture to our build as it would be impossible for us to support it since we have no system like this. However I would note as the previous comment, it should work, and you can compile it with the go toolchain for AIX if it is supported by go.
