### ISSUE TITLE
Support SSH session recording configuration

### ISSUE THREAD

**Issue by Qup42** [juanfont/headscale#1793]
## Why

I would like to use the SSH session recording feature of tailscale. headscale unfortunately does not support the configuration required for SSH session recording.

## Description

The scope of this is that headscale should handle the configuration options in the SSH ACL rules (`recorder` and `enforceRecorder`) that are required for SSH session recording. This includes parsing the fields from the config and setting the fields in the `SSHAction` response. Providing an endpoint that can receive the recordings is not in the scope of this issue.

This should be small change. I am willing to provide a PR for this feature. This issues goal is to discuss the feature before opening a PR.

**Comment by p1-olm** [comment]
Have you managed to log the `tsrecorder` container with headscale ? When I last checked, there wasn't an option to specify a different server.

**Comment by Qup42** [comment]
> Have you managed to log the `tsrecorder` container with headscale ? When I last checked, there wasn't an option to specify a different server.

No. I am playing around with collecting the client logs and session recodings. But that this is in a repo that is private for now until it is in a usable state.
