### ISSUE TITLE
Cant get to Container Console in latest alpha5 after Updated from latest stable

### ISSUE THREAD

**Issue by masterwishx** [juanfont/headscale#1800]
Using Ubuntu Server in Oracle Cloud , Headscale in Docker [headscale/headscale:0.23.0-alpha5]
After updated to v 0.23.0-alpha5 from 0.22.3 cant get to Console from portainer also from SSH session of server : 

`docker exec -it headscale /bin/bash`
`docker exec -it headscale /bin/sh`

`OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown`
`OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown`

`docker exec headscale headscale nodes list` Working Fine

**Comment by ohdearaugustin** [comment]
@masterwishx This is not a bug and it is intend to work this way. We are using distroless images, this mean there is nothing inside the container that is not needed.

You can read more about distroless images [here](https://github.com/GoogleContainerTools/distroless)

If you have any specific question just let me know.

The debug image will container a shell: [v0.23.0-alpha5-debug](https://hub.docker.com/layers/headscale/headscale/v0.23.0-alpha5-debug/images/sha256-c3dd57d5ebc557b1f865a737593d6b249ffefa16f8a081010cdd42af852ca37b?context=explore)

**Comment by masterwishx** [comment]
> This is not a bug and it is intend to work this way. We are using distroless images, this mean there is nothing inside the container that is not needed.

Thanks, got it

**Comment by florian-obradovic** [comment]
I was asking myself how I can answer yes/no questions of a command like:
`docker exec headscale headscale nodes backfillips`
![CleanShot 2024-05-12 at 13 45 00@2x](https://github.com/juanfont/headscale/assets/57985125/7d5cea92-9479-4427-a5af-45a970205097)
