### ISSUE TITLE
Support ACL Tests

### ISSUE THREAD

**Issue by EtaoinWu** [juanfont/headscale#1803]
## Why

ACL `tests` is a tailscale feature that allows ACL creators to do a sanity check on an ACL. It is a quality of life feature for access management.

```javascript
// in ACL.hujson
{
  // ... other config
  "tests": [
    {
      "src": "alice-pc",
      "proto": "tcp",
      "accept": [ "jump-server:22", "tag:printer:80" ],
      "deny": [ "bob-laptop:443" ],
    },
  ],
}
```

Headscale currently parses but [ignores](https://github.com/juanfont/headscale/blob/7a920ee701f6c1cc5152075bfcd7dae6f6d604c6/hscontrol/policy/acls_types.go#L40) ACL tests in an ACL config hujson or yaml file.

## Description

Implement ACL testing as described in tailscale's [KB](https://tailscale.com/kb/1337/acl-syntax#tests). Note that the struct `ACLTest` misses some fields as defined by tailscale.

**Comment by wrbbz** [comment]
@kradalby , sorry for tagging you directly
Why is this issue closed as "not planned"? Is it somehow out of scope? Or just due to the inactivity?

It would be a nice to have feature. As it could help to create and maintain an ACLs

**Comment by kradalby** [comment]
I opened it again, yes inactivity. But will like to point out that there is no space for this feature in the roadmap for a while. If someone wants to take a stab at it, this is a pretty good standalone part of the code base.

**Comment by kradalby** [comment]
A new beta is out: [v0.29.0-beta.1](https://github.com/juanfont/headscale/releases/tag/v0.29.0-beta.1).

This feature is included in the release.

If you discover problems with it, open a new issue with full debug information: headscale config, policy, headscale logs at trace level, plus `tailscale debug netmap` and `tailscale status --json` from an affected client. See the [debugging and troubleshooting guide](https://headscale.net/development/ref/debug/) for collection steps and follow the issue template.
