### ISSUE TITLE
Docker Hub: No tag 'headscale:latest' anymore

### ISSUE THREAD

**Issue by x86dev** [juanfont/headscale#1810]
When pulling Headscale via Docker Hub (https://hub.docker.com/r/headscale/headscale), i.e. via `docker pull headscale/headscale`, it errors out with "manifest for headscale/headscale:latest not found: manifest unknown: manifest unknown".

Only pulling "headscale/headscale:unstable" works. IIRC there was a "headscale/headscale:latest" tag before -- any reason why this vanished?

**Comment by ohdearaugustin** [comment]
We dropped the latest tag for now, please use tagged releases.

This has two reasons:
1. using the latest tag is bad practice
2. We changed the pipeline to release the docker images and accidentally tagged a pre-release with the latest tag. Therefore we manually had to remove the tag. 

Announcements on Discord:
```
Sorry, this message is a bit late, but we want to warn people that by accident, the alpha release got pushed to the latest tag which can cause problems.

We recommend you always tag a specific version to ensure you are in control of your own deployments, for ours and other containers.

As for the change, the alpha container changed the entrypoint so in the general case it should crash loop and not run the new version.

We are working on correcting the tags.
```

```
The docker tags issue we had with the previous issue should now be resolved, as part of this, we have chosen to untag latest for the time being, and we expect it to be reinstated when there is a new stable release, but we strongly recommend people to use version specific tags.
```

**Comment by x86dev** [comment]
Ok, thanks for clarifying this!

**Comment by x86dev** [comment]
True, ran into that as well.

**Comment by ohdearaugustin** [comment]
Please read the second part, they will be reestablished with the new stable release. Therefore I don't see a problem.

**Comment by piuser99** [comment]
Which version is the latest now?

**Comment by kradalby** [comment]
0.22.3 is the latest stable version.
