### ISSUE TITLE
Error: unknown command "headscale" for "headscale" Running headscale in a container

### ISSUE THREAD

**Issue by mockte** [juanfont/headscale#1822]
URL: https://github.com/juanfont/headscale/blob/v0.23.0-alpha5/docs/running-headscale-container.md

when I start docker container, get error:

[root@LESSZHDEVPR01 headscale]# docker logs headscale
Error: unknown command "headscale" for "headscale"
Run 'headscale --help' for usage.
unknown command "headscale" for "headscale"

how can I fixed it?

**Comment by winterheart** [comment]
Hello.

0.23.0-alpha5 changes way to run headscale in container (https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5). You need to change `headscale serve` to `serve` on launch command. I.e.:

```
docker run \
  --name headscale \
  --detach \
  --volume $(pwd)/config:/etc/headscale/ \
  --publish 127.0.0.1:8080:8080 \
  --publish 127.0.0.1:9090:9090 \
  headscale/headscale: 0.23.0-alpha5 \
  serve
```

**Comment by ohdearaugustin** [comment]
The documentation is currently still for the stable version 0.22.3. You can just run the stable version or join the discord to discuss with people to run the newer alpha version.

Some new documentation should be available in the future.

**Comment by kradalby** [comment]
I've assigned @ohdearaugustin , hope you can help us update the docs when 0.23.0 is about to be released
