### ISSUE TITLE
Update notice breaks JSON output

### ISSUE THREAD

**Issue by tmfksoft** [juanfont/headscale#1825]
## Bug description

When automating client management with Headscale using CLI and `--output=json` the JSON output is 'broken' by the message starting with "An updated version of Headscale has been found" etc, I can't take the JSON output directly.

Is there a flag to disable this output?

While actually updating obviously fixes this I can't sit checking every 5 minutes for an update.

## Environment

I'm running Headscale v0.23.0-alpha2 under Ubuntu 22.0.4, though Headscale does need updating.

## To Reproduce

Run the command
`headscale users list --output=json`

**Comment by fredrikekre** [comment]
`headscale users list --output json` works (note the missing `=`) so this is an inconsistency in argument parsing where the real argument parser handles it, but the crude check for machine output here https://github.com/juanfont/headscale/blob/8a8e25a8d1e6bc5fa27b7f72f99bbf24b290e0a6/cmd/headscale/cli/utils.go#L188-L196 doesn't.
