### ISSUE TITLE
Headscale exit node route needs to be reenabled every time a client advertises exit node

### ISSUE THREAD

**Issue by Ziomal12** [juanfont/headscale#1835]
Hello,

I'm not sure whether that should be a feature request or bug report, anyway...

If I use 'advertise exit node' on android client and then enable that route in headscale server's console it works as intended. However if I stop running exit node and then enable it again I need to also enable it in headscale server again. I feel like it should be done only once and then server should remember that this route is already enabled next time it comes up.

I'm running [v0.23.0-alpha5](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha5)

**Comment by ohdearaugustin** [comment]
Please test on the latest version again.

**Comment by kradalby** [comment]
I believe fixes in https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha12 should resolve this issue, let me now if not and we will reopen it.
