### ISSUE TITLE
Extra Records configuration changed in alpha5 to require subnet?

### ISSUE THREAD

**Issue by Nickiel12** [juanfont/headscale#1837]
## Bug description

I had been having issues with the latest stable, so I've been running on the alpha versions. I updated from alpha4 to alpha5, and I started getting this error:
`cmd/headscale/cli/root.go:54 > Failed to get headscale configuration error="netip.ParsePrefix(\"\"): no '/'"`

I researched on the discord, and found this was related to changes made to ACL and ipv6. So I added a subnet mask to my DNS record:
```yaml
dns_config:
    domains:
    extra_records:
    - name: git.nickiel.net
      type: A
      value: 100.64.0.1/31
```
And it builds and runs, but none of the added DNS records are resolving on any of my tailscale devices.

## Environment
- Headscale v0.23.0-alpha5
- Several, but my main testing rig was running tailscale 1.62.0
- NixOS 24.05 unstable
- 6.1.77

- [X ] Headscale is behind a (reverse) proxy, but I have not had any issues with it before upgrading to alpha5

## To Reproduce
Use an existing configuration that adds extra records from alpha4 or earlier, then try the same configuration on alpha5, and the ip `value` will cause an error if a subnet mask is not defined. 

I'm not entirely sure if it is intended behavior for DNS records to require a subnet mask now, or if it was a bug caused by the new IP validation, so I figured I would open a ticket about it.

**Comment by ohdearaugustin** [comment]
Please test with the newest version again.

**Comment by Nickiel12** [comment]
It does not give that error anymore when excluding subnet masks from DNS entries. Thank you!
