### ISSUE TITLE
Unclear sentences in documentation about ACLs

### ISSUE THREAD

**Issue by dariusarnold** [juanfont/headscale#1841]
## Bug description

The [following document](docs/acls.md) contains the sentence
> For instance, instead of referring to users when defining groups you must use users (which are the equivalent to user/logins in Tailscale.com).

The sentence is confusing and probably one of the mentions of user is wrong. I think what is meant that instead of defining groups made of users and using the groups for ACL, the users are used directly on the ACL.

> When using ACL's the User borders are no longer applied. All machines whichever the User have the ability to communicate with other hosts as long as the ACL's permits this exchange.

Borders are only used once here and not explained. I am having issues understanding what the sentence is supposed to mean. The official Tailscale doc about ACLs doesn't mention borders, but I am not overly familiar with tailscale/headscale, so it might be a common term. I understand this to mean using ACLs allows communication between machines despite them not belonging to the same user account. Is that not possible when ACLs are not in use?

## Environment

On the headscale main branch, file was last changed with commit https://github.com/juanfont/headscale/commit/a6bc792a6130dbfdc88b2436b790e542ea17ceba.

**Comment by allamedo** [comment]
In the ACLs documentation there is also a reference to the `./tests/acls/` directory that doesn't seem to exist anymore.
