### ISSUE TITLE
Add documentation about using the same machine as client and server

### ISSUE THREAD

**Issue by Riezebos** [juanfont/headscale#1852]
## Why

As a user of tailscale that wants to try headscale, I have not been able to find information on whether it is possible to use the same server as both a headscale server and a tailscale client at the same time. (And about whether it is a good/bad idea to do this).

My use case would be having a single VM in some cloud that I run Headscale on, but also setting up Gitea on the same VM and connecting to it via the Tailnet.

## Description

My proposal would be an FAQ question that looks like this:

**Can/Should I use the same machine as both server and client?**
Fantasy answer: _Yes, this is no problem, just install headscale and tailscale according to the instructions and use `--login-server=localhost`._

**Comment by ohdearaugustin** [comment]
You can make a PR and add it to the FAQ at https://github.com/juanfont/headscale/blob/main/docs/faq.md
