### ISSUE TITLE
incorrect version information in container images

### ISSUE THREAD

**Issue by derelm** [juanfont/headscale#186]
The output of `headscale version` in linux/amd64 images is incorrect:

```
➜  ~ docker run --rm -ti headscale/headscale:0.10.3 headscale version
dev
➜  ~ docker run --rm -ti headscale/headscale:0.10.4 headscale version
dev
➜  ~ docker run --rm -ti headscale/headscale:0.10.5 headscale version
dev
```

The would expect the output to match the container tag.

**Comment by kradalby** [comment]
We need to pass the variable into the Dockerfile, this is a good first issue for someone with (or without) docker experience.
