### ISSUE TITLE
Missing Metrics for last machine contact

### ISSUE THREAD

**Issue by wrenix** [juanfont/headscale#1896]
## Bug description

after:
https://github.com/juanfont/headscale/pull/1492

several metrics does not exists anymore.

i miss the metrics `headscale_last_update_seconds` which was nice for alerting if a machine was not connect correct with tailscale.

## Environment

- OS:
- Headscale version: main
- Tailscale version: X

- [x] Headscale is behind a (reverse) proxy
- [x] Headscale runs in a container

**Comment by kradalby** [comment]
Hi, this metric does not exist anymore due to a change in how we distribute updates. It will not return, but I am redoing the metrics that had been left and you can preview some of them in https://github.com/juanfont/headscale/pull/1895.

The closest/most relevant for a similar purpose might be:

```
# HELP headscale_notifier_open_channels_total total count open channels in notifier
# TYPE headscale_notifier_open_channels_total gauge
headscale_notifier_open_channels_total 149

# HELP headscale_mapresponse_current_sessions_total total count open map response sessions
# TYPE headscale_mapresponse_current_sessions_total gauge
headscale_mapresponse_current_sessions_total 150
```
