### ISSUE TITLE
[Bug] Minor issue, where headscale thinks alpha9 is newer than alpha11

### ISSUE THREAD

**Issue by peskyAdmin** [juanfont/headscale#1928]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
@Headscale:~/Development/headscale$ sudo docker exec headscale headscale nodes list | grep offline
2024-05-06T22:24:56Z TRC DNS configuration loaded dns_config={"Nameservers":["1.1.1.1"],"Proxied":true,"Resolvers":[{"Addr":"1.1.1.1"}]}
2024-05-06T22:24:56Z WRN An updated version of Headscale has been found (0.23.0-alpha9 vs. your current v0.23.0-alpha11). Check it out https://github.com/juanfont/headscale/releases
```

### Expected Behavior

instead of the line `WRN An updated version of Headscale has been found (0.23.0-alpha9 vs. your current v0.23.0-alpha11). Check it out https://github.com/juanfont/headscale/releases` I would expect to see something like `INFO You are on the latest version of headscale  v0.23.0-alpha11`

### Steps To Reproduce

1. installed and built tailnet on 0.23.0-alpha8 docker image
2. redeploy with newer image
3. execute a nodes list command with docker exec

### Environment

```markdown
- OS: Ubuntu 20.04
- Headscale version: 0.23.0-alpha11
- Tailscale version: 1.64.0
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by christian-heusel** [comment]
>  - [x] I have searched the existing issues

I think this is a duplicate of Issue https://github.com/juanfont/headscale/issues/1923 🤔

**Comment by peskyAdmin** [comment]
my apologies

**Comment by peskyAdmin** [comment]
my aplogies this is a repeat issue of https://github.com/juanfont/headscale/issues/1923
