### ISSUE TITLE
[Bug] Tailscale doesn't connect after phone reboot with Tailscale connection on

### ISSUE THREAD

**Issue by Ziomal12** [juanfont/headscale#1930]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After rebooting phone (without disabling connection) or force closing the android app it doesn't connect again (stuck at `starting...`)

In headscale logs after successful authorisation I see `2024-05-08T08:07:39+02:00 INF home/runner/work/headscale/headscale/hscontrol/poll.go:657 > node has an open stream(0x4000a8c480), rejecting new stream node=localhost node.id=6 omitPeers=false readOnly=false stream=true`
After force closing the app and restarting headscale I'm able to log back in.

### Expected Behavior

The app should connect again.

### Steps To Reproduce

1. Connect to tailnet 
2. Reboot phone without disabling tailscale connection
3. 3. Open app after restart and try to connect again.

### Environment

```markdown
- OS: android 14
- Headscale version: v0.23.0-alpha11
- Tailscale version: 1.65.182-t80df8ffb8-g6a15347453c (new beta app)
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by sjansen1** [comment]
There is a change in Tailscale 1.66.3 that may solve your issue.

https://tailscale.com/changelog#client
- "Improved the VPN service connection logic, especially when rebooting the device with Always-On VPN enabled."
