### ISSUE TITLE
Received error: control server is too old; no noise key

### ISSUE THREAD

**Issue by sachinshakya507** [juanfont/headscale#1932]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am Experiencing an issue while connecting to my headscale server.
When i try to connect my headscale it stuck with no any authticate message
This is my status log from tailscale
```
$sudo systemctl status tailscaled.service
: Received error: control server is too old; no noise key
: monitor: RTM_DELROUTE: src=, dst=fe80::/64, gw=, outif=197, table=254
: monitor: RTM_DELROUTE: src=, dst=ff00::/8, gw=, outif=197, table=255: 
[RATELIMIT] format("control: LoginInteractive -> regen=true") (2 dropped)
: control: LoginInteractive -> regen=true
: [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)") (2 dropped)
: control: doLogin(regen=true, hasUrl=false)
: Received error: control server is too old; no noise key
```

### Expected Behavior

Should be able to generate below authentication message.
```
To authenticate, visit:
https://my_headscale_server:443/register/nodekey:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

### Steps To Reproduce

What I did on my tailscale server to connect headscale.
```
sudo tailscale up --login-server http://my_headscale_server --accept-routes
```

### Environment

```markdown
- Headscale version: v0.12.3
- Tailscale version: 1.64.0
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

I think i should update my headscale version. But can i get any help regarding headscale update without changing my config file or having any issue as its my production server.

**Comment by ohdearaugustin** [comment]
I really hope you are not running 0.12.3 still. This version doesn't support the noise protocol. Only an update to 0.22.3 will help.

It just seems like you have no noise key defined on the server.

> Received error: control server is too old; no noise key

See this config snipped for 0.22.3:

https://github.com/juanfont/headscale/blob/b01f1f1867136d9b2d7b1392776eb363b482c525/config-example.yaml#L49-L56

This seem no to be a bug.
