### ISSUE TITLE
[Bug] Unstable tailscale client Integration Test fails

### ISSUE THREAD

**Issue by ohdearaugustin** [juanfont/headscale#1954]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the Integrationtest for TestAuthKeyLogoutAndRelogin is failing with the latest unstable tailscale client. This is probably caused by an update of the client. In more detail some verification of DERP is failing. For detail see for example this failed [job](https://github.com/juanfont/headscale/actions/runs/9139250875)

Also was able to reproduce this behaviour locally.

### Expected Behavior

The Integration test should work for the new unstable version again. We probably to investigate a bit further. 

### Steps To Reproduce

To localy reproduce you can run the `run.sh` scrip in the integration test as following:
```bash
integration/run.sh ^TestAuthKeyLogoutAndRelogin$ 1
```

### Environment

```markdown
- Integration Test [Workflows](https://github.com/juanfont/headscale/blob/main/.github/workflows/test-integration.yaml)
- Locally
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
Now fixed in #1931
