### ISSUE TITLE
[Bug] ACLs although going one way, are discoverable by the "dst".

### ISSUE THREAD

**Issue by mifraburneo** [juanfont/headscale#1961]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have this users as an example:
<img width="283" alt="image" src="https://github.com/juanfont/headscale/assets/31111883/06f1e8a9-8b14-41fa-aec3-c9a19f49b667">

As well as this ACL:
<img width="580" alt="image" src="https://github.com/juanfont/headscale/assets/31111883/1bc528cf-dd7f-4710-8118-d291d88cfd58">

So now currently:
Mifra's (admin's) machines are able to see all the network's machines.
BUT
Any user's machines are able to see Mifra's machines as well (aka discover via UI or tailscale status, providing information like IP and if they're up or not) although it seems that they're not able to ping nor ssh, etc.

### Expected Behavior

I expect that the only rule in the ACL is considered.
That is, **only the admin group members can _see and access_ other machines and not viceversa**.

### Steps To Reproduce

Create 3 users at least and assign an ACL in the same matter as shown above.

### Environment

```markdown
- OS: Ubuntu 24.4
- Headscale version: 0.22.3
- Tailscale version: indifferent, but 1.64 for example
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
Hi, this is intended behaviour, if one of two machines can reach each other, they will be visible in each others map (and therefore UI/status). Only nodes that cannot connect to each other at all will be fully removed from the list.
