### ISSUE TITLE
[Bug] dns_config.domains only works if override_local_dns is enabled

### ISSUE THREAD

**Issue by ajs124** [juanfont/headscale#1963]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setting `dns_config.domains` without setting `dns_config.override_local_dns = true` leads to this warning and `dns_config.domains` being not applied:
`Warning: dns_config.domains is set, but no nameservers are configured. Ignoring domains.` (https://github.com/juanfont/headscale/blob/main/hscontrol/types/config.go#L545)

This warning is quite misleading, because `nameservers` actually refers to `resolvers`, which is taken from the `nameservers` field, but only if `override_local_dns = true` (https://github.com/juanfont/headscale/blob/main/hscontrol/types/config.go#L503).

### Expected Behavior

If there are technical reasons, keep this behavior and emit a less misleading error message.

If there aren't any technical reasons for why `domains` needs `override_local_dns`, change the check and apply this config.

### Steps To Reproduce

Set `domains` to a non-empty list while setting `override_local_dns` to `false`.

### Environment

```markdown
- OS: NixOS 24.05
- Headscale version: master, e.g. 5f9c26930ce796284a8fc7ad167f76e187813d64
- Tailscale version: 1.66.4
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

I'm open to implementing either option (better error message or changing the check) and opening a PR, if you want me to.

**Comment by kradalby** [comment]
I think this is a longstanding bug, I dont think the error makes sense based on Tailscales docs, can you give https://github.com/juanfont/headscale/pull/1987 a go?

**Comment by ajs124** [comment]
Thanks! I will give that PR a go, but it might take some days/weeks.

**Comment by ajs124** [comment]
I gave it a try and it seems to solve my problem. Didn't do any extensive tests though.
