### ISSUE TITLE
[Bug] systemctl stop headscale is very slow!

### ISSUE THREAD

**Issue by 1298391314** [juanfont/headscale#1968]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

systemctl stop headscale  will takes a long time to stop every time!

By debugging, I found that blocking at [h.pollNetMapStreamWG.Wait()] (https://github.com/juanfont/headscale/blob/main/hscontrol/app.go#L816).

### Expected Behavior

to be resolved

### Steps To Reproduce

1.make a node online
2.systemctl stop headscale

### Environment

```markdown
- OS:Ubuntu 20.04
- Headscale version: headscale_0.22.3_linux_amd64
- Tailscale version: 1.66
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
please try the new alpha, the 0.22.3 wont receive any other fixes.

**Comment by 1298391314** [comment]
> please try the new alpha, the 0.22.3 wont receive any other fixes.

I compiled headscale myself using the latest code, and the problem still exists.

**Comment by bottiger1** [comment]
I am also getting this problem with [v0.23.0-alpha12](https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha12)

**Comment by nblock** [comment]
Problem also exists on 0.23.0-beta3
