### ISSUE TITLE
[Bug] Method ‎Hosts.UnmarshalYAML does not add CIDR notation

### ISSUE THREAD

**Issue by Hypnotist1148** [juanfont/headscale#1977]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The ‎`Hosts.UnmarshalJSON` function checks if there is a `/` in the IP Address and adds the CIDR /32 if needed. the YAML equivalent (`‎Hosts.UnmarshalYAML`) on the other hand does not.

### Expected Behavior

The `‎Hosts.UnmarshalYAML` method should add the CIDR notation the the end of the IP if there is none existing.

### Steps To Reproduce

1. Use the YAML config
2. Add a host (for example `myhost`) to the hosts object and use the IP `10.0.0.10`
3. You will get an error that the `netip.ParsePrefix` method failed to parse the IP.
4. Now you add the CIDR /32 at the end and watch it work.

### Environment

```markdown
- Client OS: Arch
- Server OS: Debian 12
- Docker Image: scratch (upstream)
- Headscale version: 0.23.0-alpha12
- Tailscale version: 1.66.4 (067defc641850791142cc83a44dadae29709344a-dirty)
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

### Anything else?

The mentioned methods can be found in the `policy` package on lines 64 and 93, or via [this link](https://github.com/juanfont/headscale/blob/1f4b59566a27d5933f32ae58d0fcc71ba8f1ea9a/hscontrol/policy/acls_types.go#L63-L111).

**Comment by kradalby** [comment]
Policy does not longer support yaml, so I will close this
