### ISSUE TITLE
Nodes shared in namespace

### ISSUE THREAD

**Issue by 12nick12** [juanfont/headscale#198]
NodeA_NameSpaceA, NodeB_NamespaceB -> both shared to NameSpaceC. 

Shouldn't the two of them be able to talk? This includes routed subnets. 

This doesn't appear to work that way. I would have to either have to share NodeA in NameSpaceB or vise versa. 

Otherwise this is pretty awesome, thanks.

**Comment by juanfont** [comment]
Shared nodes do not expose their subnets, to match the behaviour Tailscale.com has (https://tailscale.com/kb/1084/sharing/#sharing--subnets-subnet-routers)

And shared nodes to a namespace do not see each other, also to match Tailscale.com behaviour:

> Company A has two shared nodes from Company B and Company C. It would not be very nice if B and C are able to see each other :)


I am afraid this is one of this Working As Intended™ cases.
