### ISSUE TITLE
[Feature] allow environment variables in config file also in postgresql config

### ISSUE THREAD

**Issue by ibotty** [juanfont/headscale#2002]
### Use case

I'd like to get the postgresql configuration from the environment where I can configure it more flexible (in Kubernetes).

### Description

I searched quiet some time on why the `${..}` syntax did not work until I found that the `oidc.client_secret_path` is handled explicitly.

### Contribution

- [X] I can write the design doc for this feature
- [x] I can contribute this feature

### How can it be implemented?

I would propose that any `${..}` in the config file should be interpolated.

**Comment by ibotty** [comment]
I might be able to contribute, but I don't program in Go often so would need guidance.

**Comment by kradalby** [comment]
Hi, all configuration can already be done from the environment:

```yaml
database:
  type: postgres
  postgres:
    host: localhost
```

Can be set with:

```
HEADSCALE_DATABASE_TYPE: postgres
HEADSCALE_DATABASE_POSTGRES_HOST: localhost
```

We do this in the integration tests: https://github.com/juanfont/headscale/blob/main/integration/hsic/config.go#L113

**Comment by ibotty** [comment]
Oh, great.  I did not find any documentation.  I can try to formulate something.  Where should it be?

**Comment by kradalby** [comment]
That would be awesome!

I dont see a place where it would fit right now, so maybe a separate page under `docs/` with notes about the config would make sense.

What do you think @ohdearaugustin?
