### ISSUE TITLE
[Feature] add support for payments via stripe

### ISSUE THREAD

**Issue by ralyodio** [juanfont/headscale#2007]
### Use case

I'd like to sell access to a self-hosted VPN.

### Description

I'd like to sell access to a self-hosted VPN.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

### How can it be implemented?

I'd like to sell access to a self-hosted VPN.

**Comment by ohdearaugustin** [comment]
I think this is totally out of scope.

It is a individual use-case that has no advantage for others.

Furthermore it would implement a proprietary payment service.

Going to close this feature request.
