### ISSUE TITLE
[Feature] Add ExecReload to systemd service

### ISSUE THREAD

**Issue by rwky3gtelecoms** [juanfont/headscale#2016]
### Use case

This will allow reloading ACLs via `systemctl reload headscale`

### Description

Add `ExecReload=/bin/kill -HUP $MAINPID` to systemd service.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

### How can it be implemented?

Add `ExecReload=/bin/kill -HUP $MAINPID` to systemd service.

**Comment by kradalby** [comment]
That would be great.
