### ISSUE TITLE
[Bug] API backfillips call fail

### ISSUE THREAD

**Issue by akelge** [juanfont/headscale#2032]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/api/v1/node/backfillips fails, I think that the route is not matched, so it tries to retrieve info on node with id backfillips, failing, of course

### Expected Behavior

A call to `/api/v1/node/backfillips` should call the related function in headscale

### Steps To Reproduce

Do an API call to `/api/v1/node/backfillips` and inspect the response

### Environment

```markdown
- OS: docker
- Headscale version: v0.23.0-alpha12
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by nblock** [comment]
I could not reproduce this issue on 8a3a0fee3ccbca7dd67b0d2965b523c8b6cb5451. It works as expected. 

Steps in full to remove a previously assigned IPv6 address:
* Start `headscale` using the default prefixes for IPv4 and IPv6
* Register a node, it gets the IP addresses `100.64.0.1` and `fd7a:115c:a1e0::1` assigned
* Create an API key: `headscale apikeys create`
* Stop `headscale`
* Remove the configuration key: `prefixes.v6`
* Start `headscale`
* Send the following request via the headscale API (empty JSON object and `confirmed` as query parameter): 
  ```bash
  $ curl -H 'Authorization: Bearer APIKEY' --json '{}' 'http://localhost:8080/api/v1/node/backfillips?confirmed=true'
  {"changes":["removing IPv6 \"fd7a:115c:a1e0::1\" from Node(1) \"localhost\""]}
  ```
* Result: the node's IPv6 address is gone &rarr; OK

Actually adding back the IP works as well:
* Stop `headscale`
* Restore the default prefixes for IPv4 and IPv6
* Start `headscale`
* Send the following request via the headscale API (empty JSON object and `confirmed` as query parameter): 
  ```bash
  $ curl -H 'Authorization: Bearer APIKEY' --json '{}' 'http://localhost:8080/api/v1/node/backfillips?confirmed=true'
  {"changes":["assigned IPv6 \"fd7a:115c:a1e0::1\" to Node(1) \"localhost\""]}
  ```
* Result: the node's IPv6 address is back &rarr; OK

@akelge Can you try again on your installation, please?

**Comment by akelge** [comment]
I think this was a misunderstanding from my side, I tried it but as a POST and it was failing.
Still it does not work on an API client in python I am writing, but that is completely on me, I will fix my stuff.

Thanks for spending time investigating this

**Comment by akelge** [comment]
All was working, it was an issue with the python API client I am writing
