### ISSUE TITLE
[Bug] Self-built DERP server cannot obtain delay information

### ISSUE THREAD

**Issue by MilkTeaNo7** [juanfont/headscale#2039]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```INI
Report:
        * UDP: true
        * IPv4: yes, 116.230.95.243:31379
        * IPv6: no, but OS has support
        * MappingVariesByDestIP: false
        * PortMapping: UPnP
        * CaptivePortal: false
        * Nearest DERP: Tokyo
        * DERP latency:
                - tok: 115.2ms (Tokyo)
				………………………………………………………………
                -  SH:         (HOME)
```

1. The domain name in the `derp.yaml` configuration file matches the domain name in the Docker DERP Compose file.
2. Multiple nodes have been checked and all can obtain an IPv4 address.
3. The DERP server has opened external access permissions for ports 23479 and 3478.
4. By using the `nmap` command to scan the corresponding DERP domain name at other locations, it can be confirmed that the UDP port is open.

### Expected Behavior

The self-built node can return the correct latency information.

### Steps To Reproduce

1. The domain name in the `derp.yaml` configuration file matches the domain name in the Docker DERP Compose file.
2. Multiple nodes have been checked and all can obtain an IPv4 address.
3. The DERP server has opened external access permissions for ports 23479 and 3478.
4. By using the `nmap` command to scan the corresponding DERP domain name at other locations, it can be confirmed that the UDP port is open.

### Environment

```markdown
- OS:
- Headscale version:  headscale version v0.23.0-beta1

- Tailscale version:ALL
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
Might be a duplicate of #2025

**Comment by kradalby** [comment]
@MilkTeaNo7 can you check the comments from #2025?

**Comment by MilkTeaNo7** [comment]
> @MilkTeaNo7 can you check the comments from #2025?

"Well, I'm not sure how he got better, maybe it was just a wrong IP address? Anyway, he's fine now, thank you."
