### ISSUE TITLE
[Feature] Headscale policy set validate ACL before applying?

### ISSUE THREAD

**Issue by dragon2611** [juanfont/headscale#2044]
### Use case

Is it possible to have the headscale policy set command run validation before applying the policy and only load the policy if it passed syntax checking.

### Description

I accidentally put autogroup:internet instead of autogroup:internet:* and it really didn't like that.

Basically all the clients started throwing back 

`Could not get the create map update error="strconv.ParseUint: parsing \"internet\": invalid syntax" `  and I'm pretty sure they all dropped off the tailnet.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

**Comment by dragon2611** [comment]
Also see https://github.com/juanfont/headscale/issues/2045  - I'm happy to contribute but writing design docs is rather outside my area of expertise and you probably wouldn't want any code I'd attempted to write.

**Comment by kradalby** [comment]
Would make sense, @pallabpain are you able to take a look?

**Comment by pallabpain** [comment]
> Would make sense, @pallabpain are you able to take a look?

Yes, I'll take a look. @dragon2611 It'd be great if you could share the policy file you were trying to apply.

Although the SetPolicy API does validate the payload https://github.com/juanfont/headscale/blob/948d53f934b83f0ca6d4d5007973b334a4ed306a/hscontrol/grpcv1.go#L723, maybe it's missing something.

**Comment by dragon2611** [comment]
Whilst I'd rather not post the entire ACL The thing that seemed to trip things up was

> { "action": "accept", "src": ["tag:mobiles"], "dst": ["autogroup:internet"] },
> { "action": "accept", "src": ["tag:pcs"], "dst": ["autogroup:internet"] }

What appeared to work was however

> { "action": "accept", "src": ["tag:mobiles"], "dst": ["autogroup:internet:*"] },
> { "action": "accept", "src": ["tag:pcs"], "dst": ["autogroup:internet:*"] }

**Comment by pallabpain** [comment]
> Whilst I'd rather not post the entire ACL The thing that seemed to trip things up was
> 
> > { "action": "accept", "src": ["tag:mobiles"], "dst": ["autogroup:internet"] },
> > { "action": "accept", "src": ["tag:pcs"], "dst": ["autogroup:internet"] }
> 
> What appeared to work was however
> 
> > { "action": "accept", "src": ["tag:mobiles"], "dst": ["autogroup:internet:_"] },
> > { "action": "accept", "src": ["tag:pcs"], "dst": ["autogroup:internet:_"] }

Thanks. This helps. I'll use this for debugging the issue.

**Comment by dragon2611** [comment]
No problem, just be wary github initially parsed it I think as the * wasn't showing.

Was having a bit of problem with the formatting.

**Comment by pallabpain** [comment]
> No problem, just be wary github initially parsed it I think as the * wasn't showing.
> 
> Was having a bit of problem with the formatting.

So the issue is that while the policy may be a valid HuJSON/JSON that can be marshalled into the policy struct, it may not have the right values expected in the policy.

**Comment by dragon2611** [comment]
I'm guessing the tailscale client didn't like the lack of a port definition, which is weird as for no TCP/UDP traffic there wouldn't be a port anyways.

**Comment by pallabpain** [comment]
> I'm guessing the tailscale client didn't like the lack of a port definition, which is weird as for no TCP/UDP traffic there wouldn't be a port anyways.

Per Tailscale docs, the port is expected.
https://tailscale.com/kb/1337/acl-syntax#dst

**Comment by pallabpain** [comment]
> Would make sense, @pallabpain are you able to take a look?

@kradalby I couldn't find anything in the tailscale client that I can use to validate the policy. Looks like it has to be implemented in headscale.

**Comment by oneingan** [comment]
Slightly offtopic but in our company we have integration tests for ACL changes using NixOS VMs based testing framework. The misconfiguration were a coomon thing before that. So I can imagine how proper validation tests could help a lot with ACLs.

**Comment by kradalby** [comment]
I think this is being solved, or at least improved in #2089
