### ISSUE TITLE
[Bug] Feature request form 

### ISSUE THREAD

**Issue by dragon2611** [juanfont/headscale#2045]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The feature request form will only let you proceed if you are wiling to state you can write a design doc/contribute to a feature.

This feels like a bug as whilst anyone requesting a feature should participate in the discussion and help where they can, not everyone has the technical expertise to work on producing a design doc/implement the feature themselves. 

![image](https://github.com/user-attachments/assets/cd46fbc2-e67f-4631-87e3-c6bdbe9e0e84)

### Expected Behavior

I think these tickboxes probably weren't meant to be mandatory?

### Steps To Reproduce

raise a feature request on github

### Environment

```markdown
N/A - Github issue
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
Yes it does sound like an oversight, would be great to get a PR to rectify it.
