### ISSUE TITLE
[Bug] AutoApprovers route not work as expect

### ISSUE THREAD

**Issue by njzydark** [juanfont/headscale#2068]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`10.42.7.0/24` not auto approved by this acl config:

```json
{
  "autoApprovers": {
    "routes": {
      "10.42.0.0/16": [
        "k8s"
      ]
}
```

when use this, it work:

```json
{
  "autoApprovers": {
    "routes": {
      "10.42.7.0/24": [
        "k8s"
      ]
}
```

### Expected Behavior

`10.42.7.0/24` auto approved by this acl config:

```json
{
  "autoApprovers": {
    "routes": {
      "10.42.0.0/16": [
        "k8s"
      ]
}
```

### Steps To Reproduce

use this acl config to test `10.42.7.0/24` :

```json
{
  "autoApprovers": {
    "routes": {
      "10.42.0.0/16": [
        "k8s"
      ]
}
```

### Environment

```markdown
- OS: Ubuntu 22.04
- Headscale version: v0.23.0-beta2
- Tailscale version: 1.68.2
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
I must have missed this one, quick check, did this work in any prior release?

**Comment by njzydark** [comment]
> I must have missed this one, quick check, did this work in any prior release?

The specific version is unclear, but there is indeed a version that is useful.

**Comment by kradalby** [comment]
It would be helpful if you have the opportunity to help me track down where the change was introduced.

**Comment by kradalby** [comment]
@njzydark I have added [`6f1bba5` (#2105)](https://github.com/juanfont/headscale/pull/2105/commits/6f1bba5342e141fc6c71cf5291e3f471af72eceb) to validate this error, but it does approve the route as expected. I am not able to reproduce this.

Can you please read the test to see if there is anything I am missing?

**Comment by kradalby** [comment]
To ensure that there is nothing later in the chain that strips this route, I also added a e2e integration test here [`95ae548` (#2105)](https://github.com/juanfont/headscale/pull/2105/commits/95ae548a20649623b31d0cf29dfadc344067a96b).
