### ISSUE TITLE
[Bug] Latest supported client.

### ISSUE THREAD

**Issue by dragon2611** [juanfont/headscale#2070]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The release notes for the latest 0.23-beta2 release state the following.

> Remove support for older Tailscale clients https://github.com/juanfont/headscale/pull/1611
> 
>     The latest supported client is 1.42

### Expected Behavior

1.42 is very old, I suspect this is either just that this part of the notes hasn't been updated for a while or does it actually mean the earliest supported client is 1.42?

I'm currently running 1.7.0 against 0.23-beta1, and it seems to be working fine.

### Steps To Reproduce

N/A - Documentation issue

### Environment

```markdown
N/A - Documentation issue
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

### Anything else?

Not a Major issue just want to avoid confusion around which client versions can be used.

**Comment by hrtkpf** [comment]
As of #2034, this is the minimum required version (see https://github.com/juanfont/headscale/commit/73112e42e20d87aa30faac033271bce277e6535b), so the number itself seems to be correct. I guess some confusion comes from the wording, since "latest" actually means newest, i.e. maximum supported version. Maybe the wording could be changed to "Minimum required client version: 1.42" or something.

**Comment by EZPC-Matt** [comment]
Indeed, that would make more sense as In its current state I read it as anything newer than 1.42 is unsupported.

**Comment by dragon2611** [comment]
I think that would make sense, as in its current form I'd interpret it as not supporting anything Newer than 1.42 rather than anything older than.

**Comment by juanfont** [comment]
Indeed :)

The oldest supported client is 1.42, the latest 1.70.
