### ISSUE TITLE
[Bug] docker v0.23.0-beta2

### ISSUE THREAD

**Issue by firekirin67** [juanfont/headscale#2082]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I deploy and run using the docker image <v0.23.0-beta2>, it exits directly. By running the command `docker logs --follow headscale`, the following output is displayed:

```
Error: unknown command "headscale" for "headscale"
Run 'headscale --help' for usage.
unknown command "headscale" for "headscale"
```

### Expected Behavior

·

### Steps To Reproduce

docker run \
  --name headscale \
  --detach \
  --volume $(pwd)/config:/etc/headscale/ \
  --publish 0.0.0.0:4993:4993 \
  --publish 0.0.0.0:4994:4994 \
  headscale/headscale:v0.23.0-beta2 \
  headscale serve

[config.txt](https://github.com/user-attachments/files/16784742/config.txt)

### Environment

```markdown
- OS: Ubuntu-22.04
- Headscale version: v0.23.0-beta2
- Tailscale version:
- Docker versin: 20.10.17
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by Marcus1Pierce** [comment]
From https://github.com/juanfont/headscale/releases/tag/v0.23.0-beta2 releases, you must change entrypoint from headscale serve to serve.

So maybe looks like this

```
docker run
--name headscale
--detach
--volume $(pwd)/config:/etc/headscale/
--publish 0.0.0.0:4993:4993
--publish 0.0.0.0:4994:4994
headscale/headscale:v0.23.0-beta2
serve
```

**Comment by kradalby** [comment]
As @Marcus1Pierce mentions, this is addressed in the changelog.

**Comment by firekirin67** [comment]
> headscale

Thank you for your reply, the issue has been resolved.

**Comment by firekirin67** [comment]
> 从https://github.com/juanfont/headscale/releases/tag/v0.23.0-beta2版本开始，您必须将入口点从 headscaleserve 更改为serve。
> 
> 所以可能看起来像这样
> 
> ```
> docker run
> --name headscale
> --detach
> --volume $(pwd)/config:/etc/headscale/
> --publish 0.0.0.0:4993:4993
> --publish 0.0.0.0:4994:4994
> headscale/headscale:v0.23.0-beta2
> serve
> ```

Thank you for your reply, the issue has been resolved.
