### ISSUE TITLE
[Feature] <title>How can Headscale manage IPs and set the IP information for nodes?

### ISSUE THREAD

**Issue by fantasy-Kx** [juanfont/headscale#2085]
### Use case

How can Headscale set the IP for a node, which would be very helpful for our IP management?

### Description

How can Headscale set the IP for a node, which would be very helpful for our IP management?

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

**Comment by kradalby** [comment]
Headscale does not support setting IPs, please ask questions in discord.

**Comment by fantasy-Kx** [comment]
> Headscale does not support setting IPs, please ask questions in discord.

I found that issue #1455 can solve my problem.
