### ISSUE TITLE
[Bug] Convert proposals to issues or delete them

### ISSUE THREAD

**Issue by nblock** [juanfont/headscale#2101]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The documentation contains two proposals `docs/proposals/001-acls.md` and `docs/proposals/002-better-routing.md`. Both are from early 2022 and those should not be part of the user documentation as they are not actionable for users.

### Expected Behavior

Convert them to issues, probably feature requests. Or, in case they are no longer valid: delete them.

### Steps To Reproduce

not relevant

### Environment

```markdown
not relevant
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by khaleel2788** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by kradalby** [comment]
I'm ok with this, they are implemented I think, or likely not relevant, and we can find them in git. The proposals didnt work out the way we envisioned and it might be equally useful to do issues, or google docs in the future.

Happy for you to raise a PR to delete them and the links in the doc page.

**Comment by nblock** [comment]
> I'm ok with this, they are implemented I think, or likely not relevant, and we can find them in git. The proposals didnt work out the way we envisioned and it might be equally useful to do issues, or google docs in the future.
> 
> Happy for you to raise a PR to delete them and the links in the doc page.

OK, will do so soonish.
