### ISSUE TITLE
Allow Lan with Exit Node

### ISSUE THREAD

**Issue by engineeringsys** [juanfont/headscale#211]
I've got a properly configured exit node which by default when I bring tailscale0 up on a node and pass the arg flag of `--exit-node=exit-node-ip` will of course route `0.0.0.0/::0` through the exit as it should.

I was looking into the proper use `  --exit-node-allow-lan-access, --exit-node-allow-lan-access=false`

When trying this on the client node I would execute:
`sudo tailscale up --login-server https://steering.mydomain.com --authkey <my auth key> --exit-node=exit-node-ip --exit-node-allow-lan-access=true --reset --force-reauth`

The expected behavior based on what i know is that it will exit all traffic except for lan traffic but the actual behavior prevents me from ssh'ng to the machine via the lan which I do have a direct route to on my VLAN.

I'm hoping I'm misinterpreting the way this works but was also hoping someone could shed some light on this.

**Comment by 0xcd0e** [comment]
Afaik, thats not how the —-exit-node-allow-lan-access flag works.
You dont set that on your clients, but on the exit node itself when you advertise it as an exit node. The intention is here, that your exit node can control, if your clients can also access the LAN that your exit node is a part of, or if the clients are only allowed to access the internet through it.
