### ISSUE TITLE
[Bug] error 404 when trying to connect to headscale

### ISSUE THREAD

**Issue by superjcvd** [juanfont/headscale#2123]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello

I tried everything I could, but impossible to test Headscale on my Laptop.

- I installed lastest version 0.23.0-beta.4 (I tried previous ones too with no success)
- Then I allowed the service to listen on 0.0.0.0 in the config yaml file.
- I launched the server (using docker on MacOS)
- I was able to execute commands on the servers without any issues (like creating a user)

But when I try to connect the client 
`tailscale login --login-server http://127.0.0.1:8080`
I just receive error messages saying that server is not available:
`failed to connect to local Tailscale service; is Tailscale running?`

I tried every possible versions for the client or the server and allway the same result.
What is strange is that if I curl on the server url (http://127.0.0.1:8080) I receive empty 404 answer
(But http://127.0.0.1:9090/metrics works fine)

(I am on MacOS latest version by the way)

Any help eould be greatly apreciated :)

### Expected Behavior

`tailscale up --login-server http://127.0.0.1:8080`
`failed to connect to local Tailscale service; is Tailscale running?`

### Steps To Reproduce

Install Headscale Docker version like in the official documentation

`tailscale up --login-server http://127.0.0.1:8080`
`failed to connect to local Tailscale service; is Tailscale running?`

### Environment

```markdown
- OS: Macos 14.6.1
- Headscale version: 0.23.0-beta.4
- Tailscale version: 1.72.2 and 1.72.1
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by vinhjaxt** [comment]
It's not related to headscale, you forgot to run tailscaled?

try `sudo systemctl start tailscaled` first, and then `tailscale up --login-server http://127.0.0.1:8080`

Ref: https://tailscale.com/kb/1278/tailscaled#stopping-and-starting-tailscaled

**Comment by kradalby** [comment]
As @vinhjaxt says, your only running the CLI for tailscale and not the actual daemon.

**Comment by superjcvd** [comment]
@vinhjaxt @kradalby Thanks a lot !
