### ISSUE TITLE
[Feature] Allow nodes to use SSH agent forwarding

### ISSUE THREAD

**Issue by zraexy** [juanfont/headscale#2128]
### Use case

I use SSH keys for sudo on my servers, which requires agent forwarding.

### Description

Allow nodes to use SSH agent forwarding.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

### How can it be implemented?

Set `AllowAgentForwarding` to `true` on `Accept`ed `SSHAction`s

I am already using this change locally.

**Comment by zraexy** [comment]
@kradalby If this seems reasonable, I can make a PR.

**Comment by kradalby** [comment]
Yes, sounds good!
