### ISSUE TITLE
[Bug] <title>missing "Bearer " prefix in "Authorization"

### ISSUE THREAD

**Issue by skarpinis** [juanfont/headscale#2160]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2024-09-30T12:46:56+01:00 ERR home/runner/work/headscale/headscale/hscontrol/app.go:357 > missing "Bearer " prefix in "Authorization" header client_address=

### Expected Behavior

no errors 

### Steps To Reproduce

running in docker container

### Environment

```markdown
- OS:linux docker container 
- Headscale version:latest
- Tailscale version:latest
```

### Runtime environment

- [X] Headscale is behind a (reverse) proxy
- [X] Headscale runs in a container

**Comment by nblock** [comment]
> 2024-09-30T12:46:56+01:00 ERR home/runner/work/headscale/headscale/hscontrol/app.go:357 > missing "Bearer " prefix in "Authorization" header client_address=

It seems you try to use the headscale API but provide the API key in an invalid format. Can you please share more details, on how you call the headscale API?

**Comment by skarpinis** [comment]
> > 2024-09-30T12:46:56+01:00 ERR home/runner/work/headscale/headscale/hscontrol/app.go:357 > missing "Bearer " prefix in "Authorization" header client_address=
> 
> It seems you try to use the headscale API but provide the API key in an invalid format. Can you please share more details, on how you call the headscale API?

Hi, can you explain more did not understand your question

**Comment by nblock** [comment]
> Hi, can you explain more did not understand your question

What have you done to get the reported error message?

**Comment by skarpinis** [comment]
> > Hi, can you explain more did not understand your question
> 
> What have you done to get the reported error message?

updated headscale

**Comment by nblock** [comment]
> > > Hi, can you explain more did not understand your question
> > 
> > 
> > What have you done to get the reported error message?
> 
> updated headscale

Can you please provide more details, what commands did you run, etc? Also, the error message involves the API, are you using a web interface?

**Comment by skarpinis** [comment]
services:
 headscale:
    container_name: headscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GB
    volumes:
      - /var/lib/docker/volumes/headscale/config:/etc/headscale/
      - /var/lib/docker/volumes/headscale/keys:/var/lib/headscale/
    ports:
        - 8080:8080
        - 9090:9090
    image: headscale/headscale:0.23.0
    command: serve
    restart: unless-stopped

 headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
networks:
  default:
    external: true
    name: proxy

**Comment by nblock** [comment]
Please read: https://github.com/gurucomputing/headscale-ui?tab=readme-ov-file#errors-related-to-missing-bearer-prefix and join our discord server at https://discord.gg/c84AZQhmpx for further support with web interfaces.
