### ISSUE TITLE
Deleting a namespace will not remove its preauthkeys

### ISSUE THREAD

**Issue by 0xcd0e** [juanfont/headscale#217]
When deleting a namespace, headscale will keep all preauthkeys in its database. When a new namespace is created with the same name as the old one, all keys are available again.

**Comment by cure** [comment]
Whoops, my bad, I will make a PR to fix that.

**Comment by kradalby** [comment]
Might want to wait for #212

**Comment by cure** [comment]
@kradalby yes! will do.

**Comment by kradalby** [comment]
Think this one can be closed?

**Comment by cure** [comment]
Yes, fix merged!
