### ISSUE TITLE
[Bug] Inconsistency ‘givenName’ in node

### ISSUE THREAD

**Issue by hopleus** [juanfont/headscale#2177]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Host name where the error occurs - `MacBook-Pro`
**(This is the real hostname of my machine)**

When registering a node on the network, `hostname` as well as `givenName` is stored in its original form from `tailcfg.Hostname` - `MacBook-Pro`, without making it based on FQDN rules.
When renaming a node (changing the `givenName`), the logic checks the new name for FQDN compliance (`CheckForFQDNRules`) and does not allow the `MacBook-Pro` name to be saved, requiring lowercase i.e. `macbook-pro`.

### Expected Behavior

When a node is registered on the network, the givenName is stored subject to FQDN rules.

### Steps To Reproduce

1. Register node
2. Show givenName in DB
3. Try changing the node name to the same
4. Receive an FQDN error
5. Save the new node name taking into account the FQDN rules
6. It's OK, the new name is saved

### Environment

```markdown
- OS: MacOS 15
- Headscale version: 0.22.3
- Tailscale version: 1.74.0
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
A new beta is out: [v0.29.0-beta.1](https://github.com/juanfont/headscale/releases/tag/v0.29.0-beta.1).

This issue should be addressed in the release.

If the problem persists, open a new issue with full debug information: headscale config, policy, headscale logs at trace level, plus `tailscale debug netmap` and `tailscale status --json` from an affected client. See the [debugging and troubleshooting guide](https://headscale.net/development/ref/debug/) for collection steps and follow the issue template.
