### ISSUE TITLE
[Feature] Taildrop between users

### ISSUE THREAD

**Issue by ENGO150** [juanfont/headscale#2194]
### Use case

Hey! I use Taildrop really often, but one thing that keeps it from being perfect (at least for me) is sharing a file between nodes of two users... For instance when I want to send my colleague something on Tailnet.

I have tried looking through Headscale source, but I didn't find anything about the limitation.
<br>
**I have no idea if headscale can change this or if this is fully rooted in Tailscale.**

### Description

It would be great to be able to allow file sharing using Taildrop between users.

### Contribution

- [X] I can write the design doc for this feature
- [X] I can contribute this feature

### How can it be implemented?

I can think of three ways of allowing the shared Taildrop
- Allowing it in headscale config file
  - `shared_taildrop: bool`
- Setting it using headscale command
  - `headscale file shared` and `headscale file private`
- Setting the Taildrop to be shared by default and using ACLs instead
 
 ```
"nodeAttrs":
  [
      {
          "target": ["*"],
          "attr":
          [
              "file:share"
          ]
      }
  ]
 ```

**Comment by nblock** [comment]
According to [this Tailscale forum post](https://forum.tailscale.com/t/taildrop-files-between-users/1854) it is currently not possible.
