### ISSUE TITLE
[Feature] Support self-signed TLS (other than Let's Encrypt)

### ISSUE THREAD

**Issue by cg31** [juanfont/headscale#2201]
### Use case

We can use self-signed TLS service without outside service like Let's Encrypt, for simple network.

### Description

Headscale support Let's Encrypt, but it still needs domain name, and it also makes Headscale depending on other service.

Nowadays we can use mkcert or openssl to generate self-signed certificate, they can be done with IP only.

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

### How can it be implemented?

1. User generate local CA with mkcert or openssl
2. User installs the CA on all nodes
3. User creates a new certificate with CA for the headscale server
4. Headscale uses the certificate with ListenAndServeTLS to provide TLS service, client nodes (Tailscale) use the installed CA to verify the certificate.

**Comment by hopleus** [comment]
Isn't that what you're suggesting?

https://headscale.net/ref/tls/#bring-your-own-certificate

**Comment by cg31** [comment]
I tried it with certificate, but it doesn't work, and headscale report error "headscale/cli/utils.go:124 > Could not connect: context deadline exceeded"

When I look inside headscale, it still uses ListenAndServe, ListenAndServeTLS can use paths to cert and key directly.

**Comment by cg31** [comment]
> Isn't that what you're suggesting?
> 
> https://headscale.net/ref/tls/#bring-your-own-certificate

Turns out... it works after trying again, only I need to use 443 as serving port.

But "headscale nodes list" seems not working anymore, but it doesn't matter.
