### ISSUE TITLE
[Feature] Plea: keep "use_username_in_magic_dns" even after tags are fixed

### ISSUE THREAD

**Issue by noseshimself** [juanfont/headscale#2213]
### Use case

We do have a sufficient number of identical host names that have been personalized based on user names as intermediate components in DNS names. This has become necessary after deciding that we will be giving up centralized offices AND a number of centralized IT services during the Covid lockdown phase. One of the tools enabling us to do so was being able to use unqualified host names and having magicDNS do the job. Now you're pulling the rug under our lazy asses away.

### Description

Keep "use_username_in_magic_dns" if it is possible at all.

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

### How can it be implemented?

Just don't delete what is necessary.  The flag "use_username_in_magic_dns" can be used to turn it off as default setting and those who really need it can continue using it.

**Comment by celevra** [comment]
we use them also to organize "group" of hosts.
it is a great feature! So please keep it

**Comment by juanfont** [comment]
Sorry, this was my bad.

It was never ment to be added in the first place and it will not be added back, the goal of this project is to align with Tailscale.

**Comment by celevra** [comment]
this could be a optional feature
So in the default configuration you are fully compatible to tailscale
but for us it is a killer feature.
All our logic is based on it, so that we need a way to build it, if you really remove it (why remove a working feature?).
than we need a webhook for new devices and create custom dns entries...

**Comment by noseshimself** [comment]
> we need a webhook for new devices and create custom dns entries...

I don't think that will be sufficient unless you can override Magic DNS with another source based on that source's answer (if it is providing a CNAME or A/AAAA, fine but if there is a negative answer coming back it has to try Magic-ing. On receiving a CNAME it you need to add even more checks. It's a nightmare.

**Comment by kradalby** [comment]
I will add a way for you to programatically provide the DNS server with new entries, see https://github.com/juanfont/headscale/issues/2262.

We will not reintroduce the feature, it is not a fully working feature and it is not safe.

**Comment by celevra** [comment]
Awesome!
Thank you
