### ISSUE TITLE
[Bug] Latest config example contains deprecated key

### ISSUE THREAD

**Issue by sevenrats** [juanfont/headscale#2219]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

current conf example does not match latest spec

### Expected Behavior

match the latest spec

### Steps To Reproduce

use the example conf file. it has a deprecated key.

### Environment

```markdown
latest bookworm
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
Sorry, can you elaborate on which key is wrong?

**Comment by teleclimber** [comment]
Not the OP but if I were to guess: they are seeing this in their logs:

```
WARN: The "dns.use_username_in_magic_dns" configuration key is deprecated and has been removed. Please see the changelog...
```

Which presumably is due to the key being explicitly set to false in the current default config:

```
  # DEPRECATED
  # Use the username as part of the DNS name for nodes, with this option enabled:
  # node1.username.example.com
  # while when this is disabled:
  # node1.example.com
  # This is a legacy option as Headscale has have this wrongly implemented
  # while in upstream Tailscale, the username is not included.
  use_username_in_magic_dns: false
```

**Comment by sevenrats** [comment]
iirc there were one or three I had to fix to get main working. sorry for incomplete report, I think I intended to self-assign when I opened this.

**Comment by sevenrats** [comment]
"dns.use_username_in_magic_dns"
