### ISSUE TITLE
Debug docker image size is ridiculous.

### ISSUE THREAD

**Issue by sevenrats** [juanfont/headscale#2220]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new "unofficial" image is 2.5 gigabytes due to non-standard approaches in "Dockerfile.debug"

### Expected Behavior

Just do normal docker best-practices.

### Steps To Reproduce

Build your dockerfile, its huge.

### Environment

```markdown
Debian Bookworm,
.23
NA
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by sevenrats** [comment]
wontfix

**Comment by yqs112358** [comment]
You can use `ko` to build normal docker images and publish it to your own docker hub for use. Something like:
```
export CGO_ENABLED=0
export GOFLAGS='-mod=readonly'
export GOBUILD_FLAGS="-ldflags=-s -w"
export KO_DOCKER_REPO=docker.io/YOUR-USERNAME/headscale-test
export KO_DEFAULTBASEIMAGE=gcr.io/distroless/base-debian12

ko publish --bare ./cmd/headscale
```
