### ISSUE TITLE
[question] --verify-clients for the embedded DERP server

### ISSUE THREAD

**Issue by The-1818** [juanfont/headscale#2236]
### Use case

Protect self-hosted DERP server from accepting requests from unauthorized users.

### Description

Hi, hope you're doing well. Is there a way to set --verify-clients tag on Headscale for the embedded DERP server?

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

**Comment by nblock** [comment]
Duplicate #1953
