### ISSUE TITLE
[Bug] Unable to access Headscale http server after installation

### ISSUE THREAD

**Issue by jaeger-2601** [juanfont/headscale#2238]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've completed the installation of Headscale on Ubuntu 24.04 LTS. Headscale is being run as a systemd service and the server address is the default one provided in config: 127.0.0.1:8080. I've ensured no other program is using that port. The logs also indicate there is no error. Trying to access the http server by curling on the local machine doesn't seem to be working.

```
2024-11-16T06:46:41Z WRN
WARN: The "dns.use_username_in_magic_dns" configuration key is deprecated and has been removed. Please see the changelog for more details.

2024-11-16T06:46:41Z INF Opening database database=sqlite3 path=/var/lib/headscale/db.sqlite
2024-11-16T06:46:41Z INF Setting up a DERPMap update worker frequency=86400000
2024-11-16T06:46:41Z INF listening and serving HTTP on: 127.0.0.1:8080
2024-11-16T06:46:41Z INF listening and serving debug and metrics on: 127.0.0.1:9090
```

### Expected Behavior

Should be able to access Headscale http server of machine

### Steps To Reproduce

1. In Ubunutu 24.04 LTS
2. Install Headscale server using official guide using .deb package
3. Curl 127.0.0.1:800 on the machine.

### Environment

```markdown
- OS: Ubuntu 24.04
- Headscale version: v0.23.0
- Tailscale version:
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by nblock** [comment]
Can you give the output of these commands (run those on the same machine where headscale installed):

* `curl http://localhost:8080`
* `sudo ss -tlpn | grep headscale`
* `sudo ss -tlpn | grep 8080`

If you want to reach headscale from the outside, you'll need to update the configuration to set at least:

```yaml
server_url: http://your-headscale.exaple.com:8080 
listen_addr: 0.0.0.0:8080 
```

**Comment by jaeger-2601** [comment]
![image](https://github.com/user-attachments/assets/a5f355ba-a651-4819-a64d-dc266eb7a6d0)
![image](https://github.com/user-attachments/assets/829e3a1d-25d1-415e-b22c-183e658e1a2a)
![image](https://github.com/user-attachments/assets/f9f994dd-71c8-49b0-b6f8-0e45281b8f26)

I've also completely turned off my firewall btw to check if that was somehow the problem.

**Comment by nblock** [comment]
This is actually fine. Headscale does not provide a web interface by default. You can visit `http://localhost:8080/windows` which shows how to setup a windows client. Same with  `http://localhost:8080/apple`

**Comment by jaeger-2601** [comment]
Yeah that works lol. Wish someone would add this in the documentation though. It was not very clear at the end.
