### ISSUE TITLE
[Bug] Modifying prefixes:v4 does not take effect

### ISSUE THREAD

**Issue by lixh00** [juanfont/headscale#2249]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I changed prefixes:v4 in the configuration file and restarted headscale, it did not take effect and was still the previous setting。

### Expected Behavior

I want to change the value of prefixes:v4 from 100.100.100.0/24 to 100.99.98.0/24

### Steps To Reproduce

1. change config.yaml
2. restart headscale
3. restart tailscale

### Environment

```markdown
- OS:alpine latest
- Headscale version: 0.23.0
- Tailscale version: latest
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by kradalby** [comment]
When you say it does not take effect, do you mean:

New nodes gets addresses from the _old_ prefix?

or
 
Nodes that is already in the database dont get moved to the _new_ prefix?

**Comment by kradalby** [comment]
closing due to lack of response
