### ISSUE TITLE
"Your authentication has expired" in main branch

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#226]
#126 seem to have broken part of the registration work flow, making the authentication expire and continuously returning that the clients authentication has expired.

The two clients I am experiencing this issue with has been registered with the "old" machine key workflow, which now seem to be broken due to the new "expiry" logic:

I wonder if there is something here:
https://github.com/juanfont/headscale/blob/main/api.go#L141-L166

But I need to dig a bit deeper to be able to replicate properly.

Hosts added with preauthkey does not seem to be affected.

**Comment by paralin** [comment]
Not sure if this is related, but I'm having a issue on "master" similarly:

 - Register a machine successfully
 - Reboot that machine
 - Now it shows "Logged out."
 - When using "tailscale up" it hangs, and I see repeated (one every second or so) POST to /machine/machine-id-here.

**Comment by kradalby** [comment]
I think it is, I started to work on it yesterday, and I have a draft PR that has some work, but it's mostly refactor to get a better overview for now.

Will continue when I have some more time.

**Comment by kradalby** [comment]
@paralin in your steps above, do you use an authkey or the web flow?

**Comment by kradalby** [comment]
@paralin Could you give the build on the tip of that draft PR a go?

https://github.com/juanfont/headscale/actions/runs/1475591575

It focuses on a fix for AuthKeys.

**Comment by paralin** [comment]
@kradalby While that fixes re-connecting existing nodes, when adding a new node, it just hangs on the "tailscale up" command.

Using auth key.

**Comment by cure** [comment]
> @kradalby While that fixes re-connecting existing nodes, when adding a new node, it just hangs on the "tailscale up" command.
> 
> Using auth key.

@paralin that may have been caused by a different bug for which I just a merged a fix in #237. Can you confirm?

**Comment by paralin** [comment]
@cure Seems to be working now, thanks. Will continue to test.

**Comment by kradalby** [comment]
Closing as resolved, please reopen if not
