### ISSUE TITLE
[Feature] Hide Client List on Status

### ISSUE THREAD

**Issue by chsasank** [juanfont/headscale#2274]
### Use case

In hosted tailscale, I saw that the nodes list are not shown on `tailscale status`. How do I achieve the same with headscale?

### Description

Hide nodes

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

**Comment by nblock** [comment]
The nodes shown with `tailscale status` is influenced by ACLs. By default, headscale has no ACLs configured and thus all nodes are visible. [Headscale supports ACLs](https://headscale.net/stable/ref/acls/) and, once configured, should give you a similar node list.
