### ISSUE TITLE
Implement Helmchart

### ISSUE THREAD

**Issue by ohdearaugustin** [juanfont/headscale#228]
Create a helm chart for headscale with following features:

- headscale with sqlite
- headsacle with postgres
- headscale with cockroachdb

I started already with implementing it on base of the kustomization files includes here.
Could be found https://github.com/ohdearaugustin/charts/tree/topic/headscale

Open for further discussion.

**Comment by kradalby** [comment]
I am for this, I think I also want to have the `k8s/` folder removed (or updated and structured) as part of this. It seems largely unmaintained and generates support requests.

**Comment by gabe565** [comment]
I have built a Helm chart for Headscale if anybody is interested! It has autogenerated documentation and uses the bjw-s common library (formerly the k8s-at-home common library), so it is very configurable. I have been using it for a few weeks without any issues!

See the docs on [Artifact Hub](https://artifacthub.io/packages/helm/gabe565/headscale) or in [gabe565/charts](https://github.com/gabe565/charts/tree/main/charts/headscale).
