### ISSUE TITLE
[Bug] Unable to connect to Tailscale coordination server warning

### ISSUE THREAD

**Issue by ARizzo35** [juanfont/headscale#2288]
### Is this a support request?

- [X] This is not a support request

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Health check warning even when online and able to connect to coordination server. Causes degraded service over time.

```
# Health check:
#     - Unable to connect to the Tailscale coordination server to synchronize the state of your tailnet. Peer reachability might degrade over time.
```

### Expected Behavior

Tailscale client should be able to connect to coordination server when online.

### Steps To Reproduce

I posted the same issue in the tailscale github: https://github.com/tailscale/tailscale/issues/13906

### Environment

```markdown
- OS: MacOS Sonoma and Linux
- Headscale version: 0.23.0
- Tailscale version: 1.76.6
```

### Runtime environment

- [ ] Headscale is behind a (reverse) proxy
- [ ] Headscale runs in a container

**Comment by ARizzo35** [comment]
Resolved by using HTTPS/TLS, see https://github.com/tailscale/tailscale/issues/13906

**Comment by d3473r** [comment]
Hello, I'm having the same issue, but i already serve headscale via https.
Can you please reopen?

I can provide logs
