### ISSUE TITLE
Post Quantum

### ISSUE THREAD

**Issue by pomology** [juanfont/headscale#2317]
### Use case

Quantum Resistance

### Description

Is any work currently being done to make Headscale post quantum secure?

### Contribution

- [ ] I can write the design doc for this feature
- [ ] I can contribute this feature

**Comment by nblock** [comment]
Headscale implements a coordination server for Tailscale and is bound to the protocols used by the Tailscale client. The protocols are designed and developed by Tailscale and this issue should be discussed with them.
