### ISSUE TITLE
GORM errors are not checked for

### ISSUE THREAD

**Issue by enoperm** [juanfont/headscale#233]
While working on a local copy of this repository, I have noticed that pretty much none of the `db.Save` calls return any `error`s, which looked strange to me. As it turns out, errors *are* actually returned, but not in a conventional way: the returned `db` instances each have an `Error` field, that may contain any errors from the transaction that created them. I think this is a bit of a footgun, at it is probably a good idea to at least log any database errors, just in case.

So checking for errors would look like something like this:
```go
if err := h.db.Save(&machine).Error; err != nil {
    // handle err
}
```

**Comment by kradalby** [comment]
Ye I had a feeling about this. I have some relatively comprehensive db refactoring in the plans so I'll take this into account aswell, thanks.
