### ISSUE TITLE
Create changelog, Issue and PR template

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#240]
@cure rightfully pointed out that we really need a changelog, 0.12.0 is ramping up to be a large release with many breaking changes and having just the included commits is no longer viable. 

In addition, we should have PR and Issue templates to make sure users and contributes have a checklist of what to include.

### Changelog

I suggest having a file `CHANGELOG.md` which has a format like:

```markdown
**0.12.0:**

**BREAKING**:
- Feature [Link to PR]
- Feature [Link to PR]

**Changes**:
- Feature [Link to PR]
- Feature [Link to PR]
```

Where the version _to be released_ is on top and people add their entry as part of their PR.

Feedback appreciated.

### Issue template

Find a good example of another project, require OS, version, and information about the setup for most things. Some gist with log output.

### PR template
Have a description and checklist?

For example:
- [ ] Added unit tests
- [ ] Added integration tests
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md

Checklist must not all be checked, just more to remind people on what needs to be done

Thoughts? @juanfont @cure @ohdearaugustin

**Comment by dragetd** [comment]
An initial CHANGES.md is IMHO a separate issue than the ISSUE/PR template. But I'd love to have go at this, if I may :-)

**Comment by kradalby** [comment]
Yes please. I Will probably do the changes part this evening, and I would appreciate a proposal for the templates if your up for it :)

**Comment by dragetd** [comment]
PR here #243

**Comment by kradalby** [comment]
This has been implemented, now the continuous work is left.

**Comment by ohdearaugustin** [comment]
I guess we can close this issue then.
