### ISSUE TITLE
Are subnet routers supported in headscale?

### ISSUE THREAD

**Issue by HarvsG** [juanfont/headscale#249]
Can  I run `sudo tailscale up --advertise-routes=192.168.0.0/24,192.168.1.0/24` on a client with a headscale server?

I am keeping track of mesh WireGuard software here: https://github.com/HarvsG/WireGuardMeshes/edit/main/readme.md

**Comment by kradalby** [comment]
Yes, but for them to be distributed you will need to approve them with `headscale route`

**Comment by HarvsG** [comment]
Great, thanks. It looks as if there is some documentation [here[(https://issueexplorer.com/issue/juanfont/headscale/117) on how to achieve this
