### ISSUE TITLE
Question about ACL

### ISSUE THREAD

**Issue by negbie** [juanfont/headscale#252]
As far as I can see, ACL's are handled by the client by getting them from the server, right? What forbids someone to adapt the handling of the ACL's in the Tailscale client so that they are simply ignored?

**Comment by juanfont** [comment]
ACLs are enforced in all the clients. So even if the peer of a node is running a modified client, the unmodified clients will still apply the rules.

Of course, ACLs become useless if you tamper _all_ the clients in your network.

**Comment by negbie** [comment]
Thank you very much!
