### ISSUE TITLE
Docker releases appear out of sync with the code releases?

### ISSUE THREAD

**Issue by mannp** [juanfont/headscale#253]
**Issue description**

The tags used for docker releases appear out of sync with the code releases?

0.12 was released a month ago according to docker, and it is not clear how they relate to the code releases?

Is there a docker release for 0.12.0-beta2, or I presume those other docker tags should be ignored?

**To Reproduce**

The docker releases I am referring to are these -> https://hub.docker.com/r/headscale/headscale/tags

Thanks for any clarification 👍🏻

**Comment by madhavajay** [comment]
Also, is it just me or did the `latest` tag just get deleted? This has been working for months and now im getting:
```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/headscale/headscale:latest: not found
```

**Comment by Akruidenberg** [comment]
I would like to test Openid. So version  0.12 with docker would be nice

**Comment by kradalby** [comment]
The docker release job is failing: https://github.com/juanfont/headscale/runs/4631424805?check_suite_focus=true

Could you have a look @ohdearaugustin ?

**Comment by ohdearaugustin** [comment]
I'm taking a look at it. It seems the PR with the changes to use a cache was not tested. For now it seems like the setup of the buildx environment was forgotten. I'm just testing out a fixed version and a PR will follow as soon as it works.

**Comment by Akruidenberg** [comment]
When will we see a new docker release?

**Comment by kradalby** [comment]
We are missing ARM builds in the setup, I imagine that we will release a new version containing just docker builds as 0.12.2 when #259 is finished.

**Comment by ohdearaugustin** [comment]
The arm builds work with the #258, they are just slow. As qemu cross-compliation is not ideal.

**Comment by mannp** [comment]
Are amd64 builds available to get updated, while the arm builds are being worked on further?

**Comment by Akruidenberg** [comment]
Same question here. Would like to test the amd64 build soon

**Comment by kradalby** [comment]
@juanfont Can you try a -beta release to see if it works now and then release 0.12.2 to get things out?

**Comment by Akruidenberg** [comment]
No release yet?

**Comment by mannp** [comment]
Seems 0,12,2 beta 1 is out on dockerhub, thanks.

'latest' doesn't appear to work for me, it didn't update to beta 1 until I used the specific beta tag.

If it's fine for others, I'll close this issue.

**Comment by artemklevtsov** [comment]
It would bi nice to add alpine based image (with appropriate tag on the Docker Hub). It will be much more convenient  to manage container on the Synology Web UI for example.

**Comment by kradalby** [comment]
Why would alpine make it more manageable on synology?

**Comment by Akruidenberg** [comment]
Also, it takes less space and is more secure.

**Comment by artemklevtsov** [comment]
I can spawn separate shell with ash and run commands from the Web UI.
![изображение](https://user-images.githubusercontent.com/603798/149137358-9ffbf05f-c9f8-4199-9e0e-d015a7704e70.png)

**Comment by kradalby** [comment]
> Also, it takes less space and is more secure.

We use distroless images, they are small and probably even more secure.

**Comment by kradalby** [comment]
> I can spawn the separate shell with ash and run commands from the Web UI.

PRs are welcome, we dont plan to support alpine.
