### ISSUE TITLE
client need certificate?

### ISSUE THREAD

**Issue by woday-dev** [juanfont/headscale#254]
**Issue description**
When TLS key and cert is enabled in headscale server, tailscale client cannot connect, as server said client need to provide certificate.
After check with code, seems like bellow code is responsible, is this behavior expected?
Seems make no sense to require tailscale client provide any certificate.
```
app.go
ClientAuth:   tls.RequireAnyClientCert,
```

**Comment by negbie** [comment]
https://www.cloudflare.com/de-de/learning/access-management/what-is-mutual-tls/

**Comment by woday-dev** [comment]
> https://www.cloudflare.com/de-de/learning/access-management/what-is-mutual-tls/

Thanks for explanation,  it's mutual-tls and it's safer, that's not the issue.
Yet seems no option to let tailscale client provide certificate, thus handshake cannot be made.

**Comment by ficapy** [comment]
I have the same problem, using HTTP can be deployed successfully, but using HTTPS, the client can't connect

**Comment by arch4ngel** [comment]
I'm a bit perplexed by this as well.

I understand it's possible to issue client certificates once one has a CA, but I'm unsure how to supply that certificate to Tailscale client's for authentication.

I'm quite new to Tailscale and I've done some Google due diligence but I've come up empty handed.

Tailscale itself has a `cert` subcommand but it looks to be concerned with procuring certs from the Tailscale network.

I'd be grateful for a tip on this.

**Comment by arch4ngel** [comment]
Quite certain I'm not doing it right, but I implemented an Nginx reverse HTTP proxy using [this guidance](https://app.smallstep.com/hello-mtls/doc/client/nginx-proxy) at the perimeter of my network.

It gets the job done, though joining nodes is obviously limited to my home network.
