### ISSUE TITLE
Release arm64 docker optimization

### ISSUE THREAD

**Issue by ohdearaugustin** [juanfont/headscale#259]
After we fix #253, there is an issue with the time it takes to build the arm64 go binary for docker. Go needs about 15 mins to compile the binary, which is extremely slow.

More debugging is still required to speed up the build process.

One idea would be to use a build cache for golang.

**Comment by ohdearaugustin** [comment]
The main problem seems to be the cross-compilation with qemu--aarch64. I'm currently testing out cross-compilation with go native, but this is a bit more work as thought, as the library go-sqlite is cgo.

**Comment by huskyii** [comment]
@ohdearaugustin   Hi, as headscale is cgo free now, I think this issue could be closed.
```bash
$ lscpu | grep 'Model name'
Model name:                      AMD Ryzen 9 5950X 16-Core Processor

$ time GOOS=linux GOARCH=arm64 GGO_ENABLED=0 go build -ldflags "-s -w -X github.com/juanfont/headscale/cmd/headscale/cli.Version=dev" cmd/headscale/headscale.go

real	0m0.705s
user	0m1.433s
sys	0m0.379s
```

**Comment by ohdearaugustin** [comment]
@huskyii Thank you for the hint. I should take a look at this issue again.

**Comment by kradalby** [comment]
Any update on this @ohdearaugustin?
