### ISSUE TITLE
Groups in ACL

### ISSUE THREAD

**Issue by jhjadmin** [juanfont/headscale#265]
**Issue description**

Adding "Groups" to ACL file only works when using "namespace". I thougt using "node@namespace" would make more sense but when trying this, I get the ERR Could not load the ACL policy error="invalid namespace" path=/etc/headscale/acl.hujson

**To Reproduce**

Just add a "Groups" section to the acl file and add an entry only with the name of the namespace. That will work, but when you add a host part in front of the namespace, like node@namespace, it throws the mentioned error "invalid namespace"
BTW same issue for "Users" as well.

**Context info**

headscale v0.12.1
Debian 11, 5.13.19

**Comment by jhjadmin** [comment]
After getting a bit deeper into the concept, I am not sure if it is working as intended. What I now did, is creating several namespaces (e.g. one for servers and one for clients) and sharing the nodes between the namespaces. With that deployment I am now able to use the "Group" logic in the acl.

Is this just a workaround or is that the way, how groups are working in headscale acl's?

**Comment by restanrm** [comment]
Currently the namespaces are used as `user` in ACL's. Some work  needs to be done regarding this issue.

**Comment by jhjadmin** [comment]
Means that sometime it may work as I described and my workaround is obsolete?

**Comment by restanrm** [comment]
Currently the only supported solution is to create multiple namespaces and share the nodes. You're workaround is not obsolete.

**Comment by jhjadmin** [comment]
ok, further development will show then. Thanks for your answers.
