### ISSUE TITLE
From readme, I can see that there is already a Windows client, but I can't find the place to download it

### ISSUE THREAD

**Issue by chenxudong2020** [juanfont/headscale#269]
From readme, I can see that there is already a Windows client, but I can't find the place to download. Please tell me where to download the Windows client. Thank you; It's best to put the Windows client to the distribution for download.

**Comment by lauhayden** [comment]
Headscale is simply a third-party control server for Tailscale - the compatibility list in the readme is with the first-party clients, which can be downloaded here: https://tailscale.com/download

**Comment by lauhayden** [comment]
Unfortunately there is a bug (https://github.com/tailscale/tailscale/issues/2798) in the windows tailscale client right now preventing the login server from being saved. A workaround that's available is to set a bunch of registry keys, which can be found here in an ansible script (found by searching the Discord history): https://github.com/kradalby/plays/blob/master/roles/win_tailscale/tasks/main.yaml#L20

**Comment by chenxudong2020** [comment]
windows客户端如何登录 还是用命令吗

**Comment by lauhayden** [comment]
I'm assuming you have a server set up. if you don't, and don't understand the documentation (https://github.com/juanfont/headscale/tree/main/docs), then I would say that this project is not for you.

1. Get headscale running on a server of your choice, with a namespace.
2. Download and install the Windows app from the link I gave above. Make sure it's not running.
3. Set two registry keys:
    `HKEY LOCAL MACHINE\SOFTWARE\Tailscale IPN\UnattendedMode` (string): `always`
    `HKEY LOCAL MACHINE\SOFTWARE\Tailscale IPN\LoginURL` (string): `https://[your_headscale_url_here]`
4. Run the Tailscale app and right click -> login. It should direct you to a page on your headscale instance. Copy the command it gives. Run the command on your server, replacing the namespace with the one you set up. Your windows Tailscale client should be connected now.

**Comment by chenxudong2020** [comment]
https://github.com/juanfont/headscale/blob/main/docs/running-headscale-linux.md

Can you provide RPM package or DEB package? I find that the document is very complex？

**Comment by chenxudong2020** [comment]
> 

Thank you， I'll try

**Comment by lauhayden** [comment]
The documentation is quite rough on the edges, but should be doable with an hour or two of troubleshooting. There is no RPM or DEB yet, but there is a docker image that you can use. Reminder that this is a volunteer-run open source project in a sort of alpha/beta state, you're expected to figure some stuff out yourself. I'm not even affiliated with the authors of this project. You can ask the discord (link in Readme) for some help if you get stuck.

**Comment by chenxudong2020** [comment]
> 

v
非常感谢
Thank you.

**Comment by rjmalagon** [comment]
For the Windows clients, the use of a Headscale server exposes the subtle and complex credential management that the Tailscale client do in the user context.

The tailscaled daemon store the main auth and config on c:\programdata\tailscale, but the login credentials are stored on %localappdata%\tailscale where the current user has the tailscale-ipn gui app loaded. 

Without the unattended flag, the user tailscale-ipn app manages and resets this login process when loaded, with the unattended flag (or the unattended checkbox within tailascale-ipn app) the client store the login credentials on the user %localappdata%\tailscale and a special config on c:\programdata\tailscale that points to this user folder for the login data when the tailscaled service is started even without the user tailscale-ipn app loaded.

The catch with Headscale. The user  tailscale-ipn app resets the login server config %localappdata%\tailscale when loaded, and make a mess with Headscale connection keys process. But if you try to store the config via tailscale cli commnad without the user tailscale-ipn app (and prevent tailscale-ipn app to load), it fails to properly store the login server config too. 

(TLDR is here)
The registry config is news for me, and my actual workoaround is login on the Headscale server via cli with the user tailscale-ipn app loaded, then check the unattended box on the gui app, close the gui app, and prevent the same user app from loading, usually removing the C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\tailscale.lnk file.

Tip, if tailscale-ipn made a mess with the config, a shortcut is to clean the config: close the user Tailscale gui app, stop the Tailscale service, remove %localappdata%\tailscale and c:\programdata\tailscale, start the Tailscale service, open the Tailsacle gui app.

Opinion here.
The elegant simplicity on the *nix Tailscale *nix is a hard contrast to, somewhat overengineered, ACL and user credential management of the Windows (and OS X) Tailscale client. A big part of the complexity that Wireguard lacks, and someone needs (and Loves?).
