### ISSUE TITLE
How to connect a client that uses the web interface

### ISSUE THREAD

**Issue by willwill2will54** [juanfont/headscale#283]
I am trying to use headscale with the home assistant tailscale integration, that runs tailscale with the web command. I am in a position to modify/fork the integration, but I cannot get shell access to the tailscale container. How should I approach this?

**Comment by rafaribe** [comment]
Is tailscale running on the Home assistant container or how does that work?

**Comment by willwill2will54** [comment]
It runs inside a docker container hosted by the home assistant OS. It runs using the host_network mode with the NET_ADMIN capability enabled and the /dev/net/tun device mounted.
The repo can be found [here](https://github.com/hassio-addons/addon-tailscale).

**Comment by kradalby** [comment]
Not sure what is being asked here

**Comment by kradalby** [comment]
Closing this as we dont have enough info to do anything about it.
