### ISSUE TITLE
Multiple IP prefixes: All machine addresses are stored in a single column.

### ISSUE THREAD

**Issue by enoperm** [juanfont/headscale#295]
**Issue description**

While support of multiple IP prefixes is now possible (**NOTE:** not on `main` yet at the time of writing), it was implemented by squeezing all allocated addresses of a machine into a single column. This is probably suboptimal, and the address allocation logic may also benefit from having a separate table for individual addresses.

**Comment by kradalby** [comment]
Combining this with #614.
