### ISSUE TITLE
Retained rows in `shared_machines` may cause nodes to be accidentally shared later on.

### ISSUE THREAD

**Issue by enoperm** [juanfont/headscale#309]
**Bug description**

Namespace IDs may get reused after consecutive `destroy` and `create` operations.
Internally, shared nodes are represented as a separate relation that maps a machine ID with a destination namespace ID.
While machines belonging to the namespace are removed upon destroying a namespace, shared machines are left untouched.
When a new namespace is created later on, machines previously shared with the old namespace will be treated as shared with the new namespace without further user action or notice.

* Create namespace to hold a test node to be shared: `owner`
* Create initial namespace to share with: `another`
* Share a node from `owner` to `another`
* Destroy `another`.
* Create new namespace `yet-another`
* Observe the previously chosen test node being shared with the namespace `yet-another`.

**Context info**

- Version of headscale used: `0.13.0-beta1`

**Comment by kradalby** [comment]
Shared machines has been removed, so this is no longer a concern
