### ISSUE TITLE
Investigate not writing a machine to DB until registered

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#341]
Currently a Machine object is created in the database immediately when the registration process starts, and not always clean up.

This seem to be to hold temporary data between requests during the registration process.

This often leads to half-finished machine objects being left around in the database, this specially happens when registering Windows clients for some reason.

This ticket is to track an effort to not save the machine object to the database until it is actually registered, as there is no real point to have it in there. Any in-flight registration should be able to live in memory until complete.

**Comment by restanrm** [comment]
An in-memory solution seems quite good. It still should be implemented with interfaces in mind to be replacable by a small implementation of an external service like Redis in my opinion
