### ISSUE TITLE
View Tags

### ISSUE THREAD

**Issue by 12nick12** [juanfont/headscale#356]
Is there any way to view tags of hosts? I'm on the current version.

**Comment by restanrm** [comment]
You're right, it should be listed with `headscale nodes list `

**Comment by kradalby** [comment]
Maybe we could have a -o wide or something that adds more columns?

This sounds very sensible, but it might be quite large so some opt in makes sense

**Comment by restanrm** [comment]
I agree

**Comment by 12nick12** [comment]
That would be awesome. Thank you so much for the awesome software.
