### ISSUE TITLE
Should "namespace" or "user" be a part of the MagicDNS?

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#358]

**Comment by restanrm** [comment]
My first thought on this subject would be “no”. In personal usage, the number of hosts should stay relatively small. When a machine is tagged, the first owner shouldn't have any meaning to the host to not bring confusion.

**Comment by nosklo** [comment]
The idea is that the user can add more hosts, so I would like that option, otherwise I believe we will need to figure out some way to deal with hostname conflicts between users/namespaces

**Comment by restanrm** [comment]
On tailscale when there is a conflict on the hostname, the suffix `_1` is automatically added

**Comment by e-zk** [comment]
I personally like the idea of keeping it so each namespace/user has it's own subdomain, like `machine.user.example.com`. Just my 2c.

**Comment by kradalby** [comment]
Yep, we will keep it that way.
