### ISSUE TITLE
Create a namespace (equivalent to a user in tailscale.com) ???

### ISSUE THREAD

**Issue by outbackdingo** [juanfont/headscale#36]
If  this is a headnode co-ordination server why do you need a tailscale.com login ? im confused.

Create a namespace (equivalent to a user in tailscale.com)

headscale namespace create myfirstnamespace

also... i see
./headscale namespace create optim
2021/06/16 14:58:46 Error initializing: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by juanfont** [comment]
Hi @outbackdingo,

I have improved the readme wording. You don't need to have a tailscale login:


> 4. Create a namespace (a namespace is a 'tailnet', a group of Tailscale nodes that can talk to each other)



Can you please check the binary for the v0.1.1?  https://github.com/juanfont/headscale/releases/tag/v0.1.1

**Comment by outbackdingo** [comment]
Thanks that worked.
./headscale namespace create optim
Namespace created
root@openwisp2:~#
