### ISSUE TITLE
Add short hand aliases for named commands

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#361]
Add some handy aliases for commands, e.g.:

- `namespaces`: `namespace`, `ns`, `user`, `users`
- `nodes`: `node`, `machine`, `machines`, `no`
- `routes`: `route`, `r`
- `apikeys`: `apikey`, `api`
- `preauthkeys`: `preauthkey`, `authkey`, `pre`

Common subcommands:
- `list`: `l`, `ls`
- `create`: `c`, `new`?
- `delete`: `del`
- `expire`: `exp`, `e`

I think Cobra should support this, so should be relatively trivial to add.

Happy to take more suggestions :)

**Comment by e-zk** [comment]
I'm happy to work on this. Do we want all of these aliases or should I just pick a few from the ones you've listed?

I personally think it might be a bit unnecessary to have all of those aliases for `nodes`. Up to you though.
