### ISSUE TITLE
headscale up - 2 nodes registered cant ping one another

### ISSUE THREAD

**Issue by outbackdingo** [juanfont/headscale#37]
tailscale0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 100.117.125.229  netmask 255.255.255.255  destination 100.117.125.229
        inet6 fe80::328c:a52:702d:d463  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 133  bytes 11020 (10.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.10.10.1  netmask 255.255.255.0  destination 10.10.10.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 388355  bytes 70009852 (66.7 MiB)
        RX errors 321  dropped 0  overruns 0  frame 321
        TX packets 22940  bytes 2731180 (2.6 MiB)
        TX errors 92  dropped 480 overruns 0  carrier 0  collisions 0

root@openwisp2:~# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         212.32.234.190  0.0.0.0         UG        0 0          0 ens192
10.10.10.0      0.0.0.0         255.255.255.0   U         0 0          0 wg0
212.32.234.128  0.0.0.0         255.255.255.192 U         0 0          0 ens192

and node 2
ailscale0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 100.107.148.109  netmask 255.255.255.255  destination 100.107.148.109
        inet6 fe80::d04c:730:d336:caa7  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22  bytes 1828 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:7f:be:4e  txqueuelen 1000  (Ethernet)
        RX packets 1306778  bytes 201624054 (192.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 979134  bytes 459607920 (438.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vnet0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc54:ff:fe4a:cf12  prefixlen 64  scopeid 0x20<link>
        ether fe:54:00:4a:cf:12  txqueuelen 1000  (Ethernet)
        RX packets 267338  bytes 41792081 (39.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 191572  bytes 66665625 (63.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vnet1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc54:ff:fef9:b5dd  prefixlen 64  scopeid 0x20<link>
        ether fe:54:00:f9:b5:dd  txqueuelen 1000  (Ethernet)
        RX packets 9086  bytes 654414 (639.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 77397  bytes 4826090 (4.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vnet2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::fc54:ff:feaa:d545  prefixlen 64  scopeid 0x20<link>
        ether fe:54:00:aa:d5:45  txqueuelen 1000  (Ethernet)
        RX packets 1032049  bytes 177663162 (169.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 914283  bytes 400343605 (381.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

❯ sudo tailscale up -login-server http://portaladmin.optimcloud.com:8000
❯ ping 100.117.125.229
PING 100.117.125.229 (100.117.125.229) 56(84) bytes of data.
^C
--- 100.117.125.229 ping statistics ---
435 packets transmitted, 0 received, 100% packet loss, time 444450ms

❯ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.10.1    0.0.0.0         UG        0 0          0 eno1
192.168.10.0    0.0.0.0         255.255.255.0   U         0 0          0 eno1
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0

[GIN-debug] GET    /key                      --> github.com/juanfont/headscale.(*Headscale).KeyHandler-fm (3 handlers)
[GIN-debug] GET    /register                 --> github.com/juanfont/headscale.(*Headscale).RegisterWebAPI-fm (3 handlers)
[GIN-debug] POST   /machine/:id/map          --> github.com/juanfont/headscale.(*Headscale).PollNetMapHandler-fm (3 handlers)
[GIN-debug] POST   /machine/:id              --> github.com/juanfont/headscale.(*Headscale).RegistrationHandler-fm (3 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:8000
[GIN] 2021/06/17 - 03:33:41 | 200 |     111.562µs |   116.118.35.59 | GET      "/key"
2021/06/17 03:33:41 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:41 | 200 |    1.345531ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:41 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:41 | 200 |    1.032246ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:42 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:42 | 200 |    1.193469ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:42 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:42 | 200 |     987.379µs |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:42 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:42 | 200 |    1.037511ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:43 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:43 | 200 |    1.031472ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:43 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:43 | 200 |    1.140751ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:44 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:44 | 200 |    2.545385ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:45 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:45 | 200 |    1.076843ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:46 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:46 | 200 |    1.148693ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:47 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:47 | 200 |     897.474µs |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:48 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:48 | 200 |    1.059621ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
[GIN] 2021/06/17 - 03:33:48 | 200 |      35.703µs |   116.118.35.59 | GET      "/register?key=6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
[GIN] 2021/06/17 - 03:33:49 | 404 |       1.023µs |   116.118.35.59 | GET      "/favicon.ico"
2021/06/17 03:33:49 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:49 | 200 |    1.077035ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:50 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:50 | 200 |    1.091801ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:53 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:53 | 200 |    1.084071ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:54 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:54 | 200 |    1.146019ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:33:56 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:33:56 | 200 |    1.057807ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:00 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:00 | 200 |    1.074029ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:02 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:02 | 200 |    1.059043ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:04 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:04 | 200 |    1.114051ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:07 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:07 | 200 |    1.115037ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:13 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:13 | 200 |    1.102115ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:16 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:16 | 200 |    1.159897ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:19 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:19 | 200 |    1.111871ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:26 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:26 | 200 |     1.07197ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:32 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:32 | 200 |     927.425µs |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:38 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:38 | 200 |    1.104985ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:48 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:48 | 200 |    1.077712ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:53 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:53 | 200 |    1.197335ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:34:58 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:34:58 | 200 |    1.116692ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:35:06 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:35:06 | 200 |    1.087817ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:35:18 [localhost] The node is sending us a new NodeKey, sending auth url
[GIN] 2021/06/17 - 03:35:18 | 200 |    1.001356ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:35:32 [localhost] The node is sending us a new NodeKey, but machine is registered. All clear for /map
[GIN] 2021/06/17 - 03:35:32 | 200 |    1.170567ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074"
2021/06/17 03:35:32 [localhost] ReadOnly=true   OmitPeers=false    Stream=true
2021/06/17 03:35:32 [localhost] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:35:32 | 200 |    7.315647ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074/map"
2021/06/17 03:35:32 [localhost] ReadOnly=true   OmitPeers=true    Stream=false
2021/06/17 03:35:32 [localhost] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:35:32 | 200 |    6.525705ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074/map"
2021/06/17 03:35:33 [localhost] ReadOnly=true   OmitPeers=false    Stream=true
2021/06/17 03:35:33 [localhost] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:35:33 | 200 |    6.273575ms |   116.118.35.59 | POST     "/machine/6932e2c2bd1d08ba75050f8add63d2874208263e9fc30d61c5e8161b34fd5074/map"
2021/06/17 03:35:33 [localhost] ReadOnly=false   OmitPeers=false    Stream=true
2021/06/17 03:35:33 [localhost] Client is ready to access the tailnet
2021/06/17 03:35:33 [localhost] Sending initial map
2021/06/17 03:35:33 [localhost] Notifying peers
2021/06/17 03:35:33 [localhost] Sending data (1216 bytes)
2021/06/17 03:35:33 [localhost] Sending keepalive
2021/06/17 03:35:33 [localhost] Sending data (165 bytes)
2021/06/17 03:36:33 [localhost] Sending keepalive
2021/06/17 03:36:33 [localhost] Sending data (165 bytes)
2021/06/17 03:37:33 [localhost] Sending keepalive
2021/06/17 03:37:33 [localhost] Sending data (165 bytes)
^C
root@portaladmin:~# ./headscale serve &
[1] 5437
root@portaladmin:~# [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /key                      --> github.com/juanfont/headscale.(*Headscale).KeyHandler-fm (3 handlers)
[GIN-debug] GET    /register                 --> github.com/juanfont/headscale.(*Headscale).RegisterWebAPI-fm (3 handlers)
[GIN-debug] POST   /machine/:id/map          --> github.com/juanfont/headscale.(*Headscale).PollNetMapHandler-fm (3 handlers)
[GIN-debug] POST   /machine/:id              --> github.com/juanfont/headscale.(*Headscale).RegistrationHandler-fm (3 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:8000

root@portaladmin:~# 2021/06/17 03:37:50 [localhost] ReadOnly=false   OmitPeers=false    Stream=true
2021/06/17 03:37:50 [localhost] Client is ready to access the tailnet
2021/06/17 03:37:50 [localhost] Sending initial map
2021/06/17 03:37:50 [localhost] Notifying peers
2021/06/17 03:37:50 [localhost] Sending data (1214 bytes)
2021/06/17 03:37:50 [localhost] Sending keepalive
2021/06/17 03:37:50 [localhost] Sending data (165 bytes)
2021/06/17 03:38:50 [localhost] Sending keepalive
2021/06/17 03:38:50 [localhost] Sending data (165 bytes)
2021/06/17 03:39:50 [localhost] Sending keepalive
2021/06/17 03:39:50 [localhost] Sending data (165 bytes)
2021/06/17 03:40:50 [localhost] Sending keepalive
2021/06/17 03:40:50 [localhost] Sending data (165 bytes)
2021/06/17 03:41:50 [localhost] Sending keepalive
2021/06/17 03:41:50 [localhost] Sending data (165 bytes)
[GIN] 2021/06/17 - 03:42:13 | 200 |     202.556µs |  212.32.234.181 | GET      "/key"
2021/06/17 03:42:13 New Machine!
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |    3.560429ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |     913.675µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |     855.282µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |     882.553µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |     882.617µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:13 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:13 | 200 |     947.643µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:14 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:14 | 200 |    1.202272ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:14 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:14 | 200 |     896.731µs |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:15 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:15 | 200 |    1.252819ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:16 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:16 | 200 |    1.092878ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:16 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:16 | 200 |     1.06959ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:17 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:17 | 200 |    1.143727ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:18 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:18 | 200 |    1.088837ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:20 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:20 | 200 |     1.13734ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:22 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:22 | 200 |    1.089247ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
[GIN] 2021/06/17 - 03:42:23 | 200 |      52.923µs |   116.118.35.59 | GET      "/register?key=1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:24 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:24 | 200 |    1.199791ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:27 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:27 | 200 |     1.13902ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:30 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:30 | 200 |    1.227831ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:32 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:32 | 200 |    1.142404ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"

root@portaladmin:~# 2021/06/17 03:42:35 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:35 | 200 |    1.131066ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:37 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:37 | 200 |    1.048402ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:42 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:42 | 200 |    1.105127ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:48 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:48 | 200 |    1.176801ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:50 [localhost] Sending keepalive
2021/06/17 03:42:50 [localhost] Sending data (165 bytes)
2021/06/17 03:42:52 [openwisp2] Not registered and not NodeKey rotation. Sending a authurl to register
[GIN] 2021/06/17 - 03:42:52 | 200 |    1.261325ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:58 [openwisp2] Client is registered and we have the current NodeKey. All clear to /map
[GIN] 2021/06/17 - 03:42:58 | 200 |     1.13688ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f"
2021/06/17 03:42:58 [openwisp2] ReadOnly=true   OmitPeers=false    Stream=true
2021/06/17 03:42:58 [openwisp2] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:42:58 | 200 |     6.32538ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f/map"
2021/06/17 03:42:58 [openwisp2] ReadOnly=true   OmitPeers=true    Stream=false
2021/06/17 03:42:58 [openwisp2] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:42:58 | 200 |    5.965112ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f/map"
2021/06/17 03:42:58 [openwisp2] ReadOnly=true   OmitPeers=true    Stream=false
2021/06/17 03:42:58 [openwisp2] Client is starting up. Asking for DERP map
[GIN] 2021/06/17 - 03:42:58 | 200 |    6.551025ms |  212.32.234.181 | POST     "/machine/1c190a58787774c68ae8734fb2ee90503f2aef40307eba9aa70406c5b14e586f/map"
2021/06/17 03:42:58 [openwisp2] ReadOnly=false   OmitPeers=false    Stream=true
2021/06/17 03:42:58 [openwisp2] Client is ready to access the tailnet
2021/06/17 03:42:58 [openwisp2] Sending initial map
2021/06/17 03:42:58 [openwisp2] Notifying peers
2021/06/17 03:42:58 [openwisp2] Notifying peer localhost (100.107.148.109/32)
2021/06/17 03:42:58 [openwisp2] Sending data (1527 bytes)
2021/06/17 03:42:58 [localhost] Received a request for update
2021/06/17 03:42:58 [openwisp2] Sending keepalive
2021/06/17 03:42:58 [openwisp2] Sending data (165 bytes)
2021/06/17 03:43:50 [localhost] Sending keepalive
2021/06/17 03:43:50 [localhost] Sending data (165 bytes)
2021/06/17 03:43:58 [openwisp2] Sending keepalive
2021/06/17 03:43:58 [openwisp2] Sending data (165 bytes)
2021/06/17 03:44:50 [localhost] Sending keepalive
2021/06/17 03:44:50 [localhost] Sending data (165 bytes)
2021/06/17 03:44:58 [openwisp2] Sending keepalive
2021/06/17 03:44:58 [openwisp2] Sending data (165 bytes)
2021/06/17 03:45:50 [localhost] Sending keepalive
2021/06/17 03:45:50 [localhost] Sending data (165 bytes)
2021/06/17 03:45:58 [openwisp2] Sending keepalive
2021/06/17 03:45:58 [openwisp2] Sending data (165 bytes)
2021/06/17 03:46:50 [localhost] Sending keepalive
2021/06/17 03:46:50 [localhost] Sending data (165 bytes)
2021/06/17 03:46:58 [openwisp2] Sending keepalive

**Comment by juanfont** [comment]
Hi @outbackdingo,

Did you have those nodes (openwisp2, localhost) connected to Tailscale.com server before? If so, could you please reboot them?

**Comment by outbackdingo** [comment]
nope never on tailscale and just rebooted both anyway, same results

**Comment by outbackdingo** [comment]
ok deleted the two nodes cleared /var/lib/tailscale and tried again, its working now

**Comment by juanfont** [comment]
Thanks for the heads up! 

I will update the documentation accordingly :)
