### ISSUE TITLE
best way to background the process??

### ISSUE THREAD

**Issue by outbackdingo** [juanfont/headscale#39]
So running ./headscale serve &  does launch the system and allow client to reg/communicate until you drop that ssh session, then it appears to somehow hangup, i noticed this after rebooting a client and re-running tailscale up .... no joy it jjust sat there.

after i logged back into the headscale vm, and killed and restarted headscale serve, then the cleint would auth again. 
So... I think we need a systemd unit for headscale

**Comment by ptman** [comment]
Have you tried running it in screen/tmux? But a .service doesn't have to be hard:

```ini
[Unit]
Description=headscale
After=network.target

[Service]
ExecStart=/path/to/headscale serve

[Install]
WantedBy=multi-user.target
```

**Comment by outbackdingo** [comment]
that actually worked :)

**Comment by outbackdingo** [comment]
that actually worked :)
