### ISSUE TITLE
Print out loaded ACLs

### ISSUE THREAD

**Issue by 12nick12** [juanfont/headscale#492]
Print out loaded ACLs. This would be awesome to make sure all ACLs are loaded.

**Comment by kradalby** [comment]
We could have a command for inspecting the current loaded acls

**Comment by restanrm** [comment]
I started to draw some lines around a new API to retrieve, modify and check ACLs based on the official tailscale API.

**Comment by kradalby** [comment]
> I started to draw some lines around a new API to retrieve, modify and check ACLs based on the official tailscale API.

While I appreciate the need for API support, I really want this to be "config as code" first, I dont have any good idea on how to solve that yet.

I suppose a "study" of potential solutions would be sensible before going too far down one route.

**Comment by restanrm** [comment]
Ok, I'll keep that in mind and try to list different kind of solutions.
