### ISSUE TITLE
Add a description

### ISSUE THREAD

**Issue by bernhardreiter** [juanfont/headscale#5]
Hello,
consider adding a description. The current documentation assumes that people know what tailscale 
is and what a tailscale coordination server does.

Even if they know, it would be cool to have a description about this.
(Because there may come a time where people prefer this Free Software solution over whatevery was there before. ;))

**Comment by juanfont** [comment]
Hi @bernhardreiter,

Thanks for the suggestion. Just added it. What do you think?


Cheers,

Juan

**Comment by bernhardreiter** [comment]
Hi @juanfont,
yes, works for me! Thanks!

Three suggestions:
 * typo: propietary -> proprietary
 *  public key exchange. Do you mean "public key-exchange" or "public-key exchange"? I guess the latter, but it is not entirely clear, maybe use "as an exchance point for cryptographic (public) keys".
 * "open source" as a technical term is often capitalized, just like "Free Software" should be. ;)

**Comment by juanfont** [comment]
Done!

Thanks for the comments!!
