### ISSUE TITLE
Toggleable /swagger, /windows and /apple endpoints

### ISSUE THREAD

**Issue by reynico** [juanfont/headscale#503]
👋  Hi!

Although `/windows` and `/apple` may not disclose a lot of data, I'm a bit worried about `/swagger` and its exposure open wide on the general listening port.

I'd suggest making these endpoints toggleable by configuration

**Comment by restanrm** [comment]
Is it to prevent from security vulnerabilities on the unmanaged swagger code ? Even though the API is here doesn't mean that anyone can manage the Headscale server. You would still need a valid APIKey.

**Comment by reynico** [comment]
Hi!
> Is it to prevent from security vulnerabilities on the unmanaged swagger code ?

more than that, I don't see any reason to have a swagger endpoint exposed open wide. (But I could be missing something here!)

**Comment by reynico** [comment]
it's a fair point. Is there any reason to have the swagger endpoint available open wide rather than on an internal network?

**Comment by reynico** [comment]
I know this is not what makes you happy 😄 but in that case, why not just bring up another internal endpoint for `/swagger`?

**Comment by mannp** [comment]
> Not particularly, but I assume it will run into the same issue as `/metrics`, implementing it isn't straight forward enough to bother (at least at the moment)

Isn't an internal 'metrics' already implemented, could swagger be implemented in the same way, or is it more involved.

Out of interest, are these endpoints exposed for tailscale?

**Comment by mpldr** [comment]
Correct me if I'm wrong, but wouldn't it be easiest to just deny access (or blackhole) requests to these routes in the reverse proxy? Might be something worth documenting.

**Comment by RUzOfuz5m** [comment]
I was able to find all the endpoints by `grep router.HandleFunc ./app.go ` and I'm curious what other endpoints can be closed to the public.

**Comment by kradalby** [comment]
I will close this as wontfix, as we dont see the general need. There are ways to lock this down outside of headscale and it is currently out of scope.
