### ISSUE TITLE
Add DNS01 Challenge

### ISSUE THREAD

**Issue by philippderdiedas** [juanfont/headscale#504]
**Feature request**

Implement ACME-DNS01 Challenge

Makes it possible to use wildcard certificates or when http challenge is not an option.

Could be achieved by using [lego](https://github.com/go-acme/lego)

**Comment by renne** [comment]
We're running Headscale + Tailscale as an ingress router with ports 80 and 443 forwarded to a web-server on the same host.
There is no way to use ports 80 and 443 for the Let's Encrypt http challenge.

Please add the ACME-DNS01 challenge via [LEGO](https://github.com/go-acme/lego).
