### ISSUE TITLE
expiration time unit does not parse correctly

### ISSUE THREAD

**Issue by thelittlerocket** [juanfont/headscale#506]
**Bug description**
When creating a new preauthkey with ``--expiration`` flag, if the unit is not `h` then it will always return the unit is not correct.

**To Reproduce**
Try to create a preauthkey with expiration set to `30m` or `365d`
`docker exec -it headscale headscale preauthkeys create --namespace dev --expiration 365d`
it will return 
`Error: invalid argument "365d" for "-e, --expiration" flag: time: unknown unit "d" in duration "365d"`

**Context info**
- Version of headscale
``
docker exec -it headscale headscale version
dev
``
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by huskyii** [comment]
https://github.com/juanfont/headscale/issues/322 dup

**Comment by thelittlerocket** [comment]
thanks and sorry for the duplicated issue.
closing it now.
