### ISSUE TITLE
Profile doesn't work for the Tailscale iOS Client?

### ISSUE THREAD

**Issue by canselcik** [juanfont/headscale#515]
First of all, thank you for this great project. Everything is working as good as it could and most of the issues seem to be stemming from our attempt to override the control plane for Tailscale clients, and not from behavioral differences of the control plane itself.

So far no matter what I have done, I wasn't able to get the iOS Tailscale client to respect the profile from `/apple/ios` and communicate with my control server. And `tailscale-ios` isn't open-sourced unlike `tailscale-android` preventing us from being unable to write a quick patch? Is this known or expected?

**Comment by kradalby** [comment]
Yes iOS does not work, the code for the profile should be commented out and not presented in the web endpoint.

**Comment by kradalby** [comment]
Gonna close this since it is out of our hands. Feel free to update the docs that confused and mentioned iOS.

**Comment by dvtkrlbs** [comment]
What does an example .mobileconfig file looks like? Also I could not seem to way to install .mobileconfig files with the Apple Configurator 2. Can anyone nudge me in a direction on how it works with version 2?
