### ISSUE TITLE
The client cannot regenerate the registration key

### ISSUE THREAD

**Issue by shuncon** [juanfont/headscale#522]
System win10

click "log in..."Unable to enter web：http://serverIP:8080/register?key=ea29d5c827d9bc14936d9bc1ee6c1650fd41e2aeaea4cc06470d81712f6a2400

[](https://fanyi.baidu.com/?aldtype=16047###)[](javascript:void(0);)
Prompt after server registration: Cannot register machine: machine not found in registration cache

How to check and uninstall the registry of the client and how to clean up the call tail
After restarting the computer, the installer and the registry cannot be re registered

**Comment by shuncon** [comment]
headscale -n default nodes register --key ea29d5c827d9bc14936d9bc1ee6c1650fd41e2aeaea4cc06470d81712f6a2400
Cannot register machine: machine not found in registration cache

**Comment by shuncon** [comment]
to configure：server_url: http://headscleServerIP:8080   Can be solved

**Comment by systemctls** [comment]
v0.16.0-beta5 ，Reappearance, no solution. It has been reinstalled many times
