### ISSUE TITLE
客户端注册疑问

### ISSUE THREAD

**Issue by jenarlion** [juanfont/headscale#530]
使用Debian10架设headscale服务器，按照官方教程安装，也都成功了。
只是在使用tailscale客户端连接时，出现问题，是这样的：
服务器和客户端可以正常运行，服务端也显示注册成功，但是运行list看不到节点，在客户端也看不到虚拟IP，麻烦帮忙指教下，谢谢

**Comment by juanfont** [comment]
Hi, this is a question for discord, not a bug.
