### ISSUE TITLE
Create a Matrix Chat room

### ISSUE THREAD

**Issue by fariszr** [juanfont/headscale#532]
**Issue description**

Currently the project uses Discord for chat/quick support, which is great if you use discord already.
But i think an open source project should use an open source chat platform if it exists, and luckily it does!

Matrix.org is a fedrated chat protocol and it has bridges too!
you can bridge discord to matrix, so users can talk across services.

more details about matrix can be found on their site: https://matrix.org, public matrix servers include matrix.org, [tchncs.de](https://tchncs.de/matrix), [SNT](https://www.snt.utwente.nl/en/service/matrix) and others.

And there is a public discord bridge at [t2bot.io](https://t2bot.io/discord/)

**Comment by fariszr** [comment]
I couldn't remove the Bug label

**Comment by fariszr** [comment]
Also the Discord invite listed in the Readme is Invalid

**Comment by kradalby** [comment]
I have fixed the Discord link, I appreciate that it is not everyones main platform, but for the time being, it is the one we frequent and I dont see using Matrix as a good enough reason to try to build yet another community or split it.

Discord was mostly chosen over Gitter and Slack, and to avoid "yet another app" to pay attention to.

**Comment by fariszr** [comment]
Matrix's strong point is your don't have to pay attention to it.

There is a discord bridge, so its a new platform but not a new community.

-------- Original Message --------

**Comment by kradalby** [comment]
Hi, we dont have capacity to do this now, we might revisit it later. For now Discord will remain our community platform.

**Comment by gregismotion** [comment]
> Hi, we dont have capacity to do this now, we might revisit it later. For now Discord will remain our community platform.

Would love to see this, but understandable if it's still not an option.

**Comment by Justinzobel** [comment]
Can we please reopen this, as closed bugs aren't generally looked at by users or developers? I would be happy to help set up and maintain a Matrix bridge as Discord is closed.

**Comment by kradalby** [comment]
No, open indicates that it is something we consider, and we are not considering this, nor interested in having a bridge. We had a bridge for a while, but it was not used so it was teared down.

**Comment by Justinzobel** [comment]
Sad when an open source project uses closed source tools. 😦

**Comment by kradalby** [comment]
I am sorry about that, I don’t know how to solve that, at least 98% of the code I’ve written for this project was done on a Mac. We choose the tools that make us productive and able to achieve what we want. And that is discord.

**Comment by Justinzobel** [comment]
Really disappointing, the trend of keeping support/chat for open source projects in closed source applications.
