### ISSUE TITLE
Derp implementation, propagation, status, and an issue with ip assignment

### ISSUE THREAD

**Issue by thenitai** [juanfont/headscale#550]
Hi,

We are running the latest version 0.15.0. While mainly everything works there are some things:

1. DERP

It's great to not have to write a YAML file anymore for running a DERP server. However, I don't think "OmitDefaultRegions" is implemented?

We "fixed" it by using an empty array to the URLs for available DERPs. Though how would we go about using selective DERP servers? According to the Tailscale doc, we could pass "null" to entries. Should we just manually add entries we like here from https://controlplane.tailscale.com/derpmap/default ?

2. IP assignment

I see in https://github.com/juanfont/headscale/pull/346 that this is fixed. However, in my experience, we've added 70 new servers, deleted two, added new ones again, and we saw that those servers got the same IP over and over again.

3. Propagation

I'm a bit confused about how fast clients should pick up on changes of other clients. For example, if I change a DERP entry or add new servers, how fast do other clients pick up on this? I see that there is a time setting, so I've changed that from 24h down to 10m. Is that the correct setting?

4. Status

Doing a "tailscale status" shows many servers as "offline", some as direct, and others with DERP. Why are servers that are obviously online and working shown as offline?

Thank you for this wonderful piece of software. It's a joy to work with and configure.

**Comment by kradalby** [comment]
Hi @thenitai apologise overlooking this issue. Are all of these issues still present for you?

(Would be great if you split unrelated issues in separate issues next time :))

**Comment by thenitai** [comment]
Yes, I haven't changed much. Though we changed our usage, we only have 5 - 7 clients now.

**Comment by juanfont** [comment]
@thenitai some of the issues you mention should have been addressed with 0.16.x.

Can you check again?

**Comment by kradalby** [comment]
Going to close this for now, please reopen as separate issues if they occur.
