### ISSUE TITLE
Any plans to add option to disable key expiry?

### ISSUE THREAD

**Issue by xj25vm** [juanfont/headscale#562]
Tailscale has an option to disable the key expiry. This would be useful for example for laptops out in the field, where a user would be left with no remote access to a server. Is this something which might be considered for implementation at some point?

**Comment by kradalby** [comment]
Hi @xj25vm, could you elaborate what you mean by "key expiry"?

Currently pre-authenticated keys will expired, but they are only needed initially when you authenticate the machine. After that the machine should stay authenticated until it logs out or is manually expired.

**Comment by restanrm** [comment]
Key expiry is actually not implemented. You should not expect any disconnection with Headscale.
