### ISSUE TITLE
After adding IPv6 prefix in config, existing machines don't get IPv6 addresses

### ISSUE THREAD

**Issue by viq** [juanfont/headscale#614]
Configuration without any prefixes defined, thus using only the default `100.64.0.0/10`. A few machines connected. Added IPv6 prefix (shown in examples `fd7a:115c:a1e0::/48`), restarted headscale. Even after restarting their services, existing machines did not get IPv6 addresses, that required removing them from headscale and adding anew.

- set up config only with IPv4 prefix
- add some machines
- add IPv6 prefix to configuration
- only newly added machines receive IPv6 address

**Context info**

- headscale 0.15.0
- tailscale 1.24.2
- OS: headscale on NixOS (unstable); tailscale on NixOS (unstable), OpenBSD (snapshots); FreeBSD 12.3

**Comment by kradalby** [comment]
This highlights a couple of other issues as well, since the IP is only given when a node joins, it will not update if the user:

- adds more networks (like described here)
- removes a network
- changes a network

Not sure yet what would be the best approach.

We could;
- Check periodically if what we have in the DB aligns with the config
- Check when a node wakes up/reconnects 


-

**Comment by gbraad** [comment]
So this also means that when IPv6 is removed, it will still show an IPv6 address for nodes that have registered before the change... and probably also when the range changed?

**Comment by viq** [comment]
Ping.

**Comment by kradalby** [comment]
I've given this some thought, and it is definitively possible to do this now with the new allocator, what I am unsure about is "when" to do it, I first thought about it as a check every time we load a node, but it has a lot of sharp edges, both resource and what if:

- you had ipv4 and added ipv6?
- you had both, removed ipv6?
- all the other combos.

What I am leaning towards is having a "back fill based on current setting function" that can be called via CLI/API, and nothing automatic.

So if you have ipv4, and add ipv6, this func will iterate over all machines and add ipv6 if its missing. or if you have both and remove ipv6, it will iterate over and remove all ipv6 addrs. 

Yes it is a manual step, but this should be something needed on only rare occasions?
