### ISSUE TITLE
[Not bug, but Enhancement]Rename Machine won't change the name's record in [nodes ls]

### ISSUE THREAD

**Issue by 1itt1eB0y** [juanfont/headscale#647]
I changed my kali(ID:2) to pi.
It says success and it was changed in my clients.
But it is still the old name in headscale's command output.
![图片](https://user-images.githubusercontent.com/29831189/174085837-d67270ed-3e4a-48d9-bf7c-dbbe085858d3.png)
![图片](https://user-images.githubusercontent.com/29831189/174086013-4b30d905-e186-44bb-ba65-d8b714e500a2.png)

**Comment by 1itt1eB0y** [comment]
I noticed there is a `given_name` in DB, so why not make it list in the output of cli?

**Comment by huskyii** [comment]
Observe same issue, it's pretty confusing, I'd suggest add a `Hostname` column in the `nodes ls` outputs.
And the mapping is:
machine.Name -> Hostname
machine.GivenName -> Name

I've implemented this enhancement, @kradalby if you think this is ok, I can open a PR

**Comment by kradalby** [comment]
Yes please

**Comment by juanfont** [comment]
@huskyii we are very much looking for the PR :)
