### ISSUE TITLE
MagicDNS Enable will cause clients can't discover each other.

### ISSUE THREAD

**Issue by 1itt1eB0y** [juanfont/headscale#649]
### Steps:
* Init a headscale with MagicDNS `Enabled`
* Common register
* Check clients `status` and ip

### Result:
* [√]You can get normal response with `headscale nodes ls`
![图片](https://user-images.githubusercontent.com/29831189/174232480-cf473459-f6c9-40b9-b34b-23ec83d3e012.png)

* [×]You can't communicate with any other client.
![图片](https://user-images.githubusercontent.com/29831189/174232470-0e01f167-360f-478a-9e26-d0d5069e6ecf.png)

* If client has discoverd other clients' info before you active MagicDNS, it can communicate with the devices you've found. But can't discover or communicate with **New Device** was registered after active MagicDNS.

### Env:
* Docker with image 0.16.0-beta1

**Comment by kradalby** [comment]
I will close this as it might have been fixed in newer version, please try a new release and reopen if it still does not work.
