### ISSUE TITLE
failed to read or create private key: failed to parse private key: key hex has the wrong size, got 44 want 64

### ISSUE THREAD

**Issue by xxooo** [juanfont/headscale#669]
wg genkey > /etc/headscale/private.key

FTL ../../home/runner/work/headscale/headscale/cmd/headscale/cli/server.go:21 > Error initializing error="failed to read or create private key: failed to parse private key: key hex has the wrong size, got 44 want 64"

??? version is v0.15.0  v0.16.0-beta5

**Comment by kradalby** [comment]
Dont manually generate the key, Headscale will do it for you, delete the key and restart.

You must have read some outdated docs or not seen a changelog, can you link where you followed?

**Comment by xxooo** [comment]
@kradalby

**Comment by kradalby** [comment]
Hi, please ask about support requests on Discord.
