### ISSUE TITLE
`headscale version` gives unexpected output

### ISSUE THREAD

**Issue by Chaz6** [juanfont/headscale#679]
When running `headscale version`, instead of displaying version information, it displays the following output:-
```
2022-07-16T14:34:20Z WRN 'ip_prefixes' not configured, falling back to default: [100.64.0.0/10]
```
Version: 0.16.0-beta3 on Linux 4.18.0-372.16.1.el8_6.x86_64 with go 1.18.

**Comment by restanrm** [comment]
That is right, but I think that we shouldn't expect Headscale to have a valid configuration file just to get the current version.

**Comment by kradalby** [comment]
This is some handling of a deprecated config option, I think we can remove this soon and also get rid of the output. Lets do this for 0.17

**Comment by ctermiii** [comment]
Run this command under head scale config file directory will act as expected.
