### ISSUE TITLE
Docker port issue or by design?

### ISSUE THREAD

**Issue by mannp** [juanfont/headscale#68]
Thanks for the new dockerfile :)

I wondered why you are exposing 8080/tcp from the docker but use 8000/tcp in the sample config files.

Are both ports used or we should we update and use 8080 as the default?

Thanks.

**Comment by juanfont** [comment]
Uh... That's actually a hell of a point... 

All the Kubernetes code & Docker assumes 8080, and the examples 8000. 

I will prepare a PR, probably just changing the example files.
