### ISSUE TITLE
Regression in HTTP API for 0.16.0-beta5

### ISSUE THREAD

**Issue by routerino** [juanfont/headscale#681]
As of headscale `0.16.0-beta5`, the HTTP API has stopped working. All calls to the API return an `HTTP OK 200` code with no content. Versions before `0.16.0-beta5` work as expected.

See GIF below for working example (I've expired that API key since, for people thinking about being cheeky):

![chrome_nJT3ZR1tCr](https://user-images.githubusercontent.com/45954722/179677476-bb7a4ffc-3e39-493f-8358-a0510652d833.gif)

**Comment by kradalby** [comment]
Looking at the change log, it looks like this broke when we dropped Gin as our web framework. 

@juanfont can you have a look? If not I can by the end of the week.
