### ISSUE TITLE
Only distribute split dns entries when the corresponding route is available

### ISSUE THREAD

**Issue by FStelzer** [juanfont/headscale#682]
As far as i understand the split dns section of the config is unconditionally distributed to all client. However when it references nameservers only reachable by an advertised route then the client might not have access to it.
It is probably too complicated to evaluate the full acl policy to determine if DNS resoultion is possible, but removing entries for routes known to headscale that the client will not get at all should be possible.

I have a couple of environments each with their own subnet and authoritative dns zone. Every environment has a tailscale node advertising the environments network to vpn clients. However not all clients have access to all environments and best should not even know about them. In some situations these names might even result in a different lookup result on a public resolver.
Right now the clients get the split dns entries and every query will time out because the route to the dns is missing.

**Comment by kradalby** [comment]
> If this feature is of interest I could probably provide a patch with some guidance. I've looked into getMapResponse() a bit where valid peers and the dns config is assembled and it doesen't look too big of a change. An additional unfiltered listpeers (or similar filtering for advertised routes for this node) and some manipulation of the resulting dns config.

I think this sounds like an interesting feature, it sounds like it _should_ work. I am happy for you to take a stab at it. The main requirement for this, and possibly most of the work would be to add integration tests to verify that it works as intended and that it does not break current behaviour.

**Comment by davidmehren** [comment]
This is still a valid feature request, that should never go stale.
