### ISSUE TITLE
Make server errors exported

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [juanfont/headscale#690]
There's a bunch of errors that `headscale` server can return. For example [`"Namespace already exists"`](https://github.com/juanfont/headscale/blob/main/namespaces.go#L19). Would it be desirable to export them?

Specifically i would find it useful as i use `headscale` as a lib to create a built-in client in a service. And there i want to check returned errors.

**Comment by juanfont** [comment]
@GrigoriyMikhalkin happy to merge a PR doing this :)

Btw, out of pure curiosity, what is the use case?

**Comment by GrigoriyMikhalkin** [comment]
@juanfont [Here](https://github.com/metal-stack/metal-api/pull/308/files#diff-e3be14987652bb48dcefbab95f677cfd5db025653af59c036ffdad1bb5d1f898R252) i'm trying to catch the `Namespace already exists` error.

It actually could be solved in another way(additional request to get all namespaces and try to find the one that's expected), but it just doesn't feel as an elegant solution.

I was thinking about using `GetNamespace` method, but it also returns an error which is not exported.

**Comment by juanfont** [comment]
Happy to get all the errors exported. Can you prepare a PR?

**Comment by GrigoriyMikhalkin** [comment]
@juanfont Yep, sure!

**Comment by juanfont** [comment]
Fixed :)
