### ISSUE TITLE
Support `disableIPv4` network policy option

### ISSUE THREAD

**Issue by cwegener** [juanfont/headscale#702]
**Feature request**

Support the `disableIPv4` network policy option in Headscale which "prevents assigning IPv4 addresses to tailscale nodes".

This is required to support nodes which have a local IPv4 underlay network that conflicts with Tailscale's hard-coded `100.64.0.0/10` IPv4 overlay network.

References:

- Tailscale KB: https://tailscale.com/kb/1018/acls/#network-policy-options
- Tailscale Issue tracker: https://github.com/tailscale/tailscale/issues/1381

**Comment by enoperm** [comment]
Wouldn't just removing the default IPv4 range from the config file do the trick?

**Comment by cwegener** [comment]
> Wouldn't just removing the default IPv4 range from the config file do the trick?

No. That simply stops an IPv4 address from being assigned. The iptables v4 rules (and possible other magic) are still getting triggered in the tailscale client, thereby blocking all local LAN traffic to and from `100.64.0.0./10`

**Comment by restanrm** [comment]
> > Wouldn't just removing the default IPv4 range from the config file do the trick?
> 
> No. That simply stops an IPv4 address from being assigned. The iptables v4 rules (and possible other magic) are still getting triggered in the tailscale client, thereby blocking all local LAN traffic to and from `100.64.0.0./10`

I recently needed something like that and it doesn't work either in official tailscale, the `iptables` rules were still deployed with this option in the ACL's rules. Maybe there is something to fix on client side (I didn't conduct an investigation and instead used the `--netfilter-mode=off` option that is usable in my context).

**Comment by cwegener** [comment]
> > > Wouldn't just removing the default IPv4 range from the config file do the trick?
> > 
> > 
> > No. That simply stops an IPv4 address from being assigned. The iptables v4 rules (and possible other magic) are still getting triggered in the tailscale client, thereby blocking all local LAN traffic to and from `100.64.0.0./10`
> 
> I recently needed something like that and it doesn't work either in official tailscale, the `iptables` rules were still deployed with this option in the ACL's rules. Maybe there is something to fix on client side (I didn't conduct an investigation and instead used the `--netfilter-mode=off` option that is usable in my context).

Ah. That's a good find!

I never actually tested the `disableIPv4` setting in the Tailscale control plane.

I wonder what the `disableIPv4` setting actually does in the Tailscale control plane after all. Maybe it is really just the equivalent of removing the default IPv4 allocation subnet from the headscale configuration ...
