### ISSUE TITLE
You can change the coordination server on the android client  

### ISSUE THREAD

**Issue by peanutyost** [juanfont/headscale#717]
https://github.com/tailscale/tailscale-android/commit/d8aedf721ae17326561fa12b2699bdb19cc677f9
https://github.com/tailscale/tailscale-android/commit/b1501eb5d8e75bfb94f85ea7ea14bc02964d84d6

Update the documentation on the readme and maybe add some direction on how to enable.

**Comment by juanfont** [comment]
We have merged this in https://github.com/juanfont/headscale/pull/703
