### ISSUE TITLE
Yunohost app

### ISSUE THREAD

**Issue by renne** [juanfont/headscale#726]
Headscale is a great project! :1st_place_medal:

Please provide a [Yunohost app](https://yunohost.org/en/packaging_apps) for one-click-installation!

A Yunohost app will attract more users which will also attract more developers!

**Comment by kradalby** [comment]
Hi, we dont have the capacity to maintain different packaging solutions, we are happy to receive community maintained PRs, but we only support the actual binary file provided in releases.
