### ISSUE TITLE
Api tls on and off function and single/multiple allowed access netmask or ip

### ISSUE THREAD

**Issue by LOVECHEN** [juanfont/headscale#731]
This is a controversial issue. 
It is requested to support the switch of TLS remote cli invocation, and to set the network segment that the api controller can access. 
The headscale front end is provided with certificate services by nginx, and the server of the internal isolated network calls the headscale server api. 
This control server is not connected to the external network, so request to add tls off and on switch.

**Comment by kradalby** [comment]
Hi, I do not think we will be adding this for now, so I will close this. If it continues to be a problem, it can be reopened in the future, but we have too much else to prioritise.
