### ISSUE TITLE
Support Postgres TLS

### ISSUE THREAD

**Issue by 617a7a** [juanfont/headscale#741]
**Feature request**

Support for Postgres DBs to use TLS during connection. Maybe add a config option that switches it on/off. Changes would be made to the following lines in `app.go`.

```go
dbString = fmt.Sprintf(
	"host=%s port=%d dbname=%s user=%s password=%s sslmode=disable",
	cfg.DBhost,
	cfg.DBport,
	cfg.DBname,
	cfg.DBuser,
	cfg.DBpass,
)
```

Our databases run on separate machines on the same network, TLS connections are essential for security.

This is simple to change and I have it working with a quick patch, but thought I should open a PR to push a more polished version upstream later.

**Comment by juanfont** [comment]
@617a7a this looks like a simple change. Can you raise a PR?
