### ISSUE TITLE
Machines cannot register again after logging out

### ISSUE THREAD

**Issue by juanfont** [juanfont/headscale#749]
As described in #744, when logging out a machine and log in again there is an issue on how we handle it that leads to messages that the machine has expired

> When logging a user out (windows client) and then logging back in via oidc azure AD, I get the error
> Aug 18 09:49:46 <headscalehost> headscale[1601506]: 2022-08-17T21:49:46Z DBG Machine registration has expired. Sending a authurl to register machine=<machine name>

**Comment by jcputter** [comment]
i'm getting a similar issue when logged out and trying to auth again 

```/headscale/oidc.go:250 > Could not exchange code for token error="Post \"https://oauth2.googleapis.com/token\": dial tcp: lookup oauth2.googleapis.com on 127.0.0.53:53: read udp 127.0.0.1:47198->127.0.0.53:53: i/o timeout"
2022-08-19T16:19:49Z ERR ../home/runner/work/headscale/headscale/oidc.go:613 > could not register machine error="machine not found in registration cache"
2022-08-19T16:20:08Z ERR ../home/runner/work/headscale/headscale/oidc.go:613 > could not register machine error="machine not found in registration cache"```

**Comment by juanfont** [comment]
Fixed via https://github.com/juanfont/headscale/pull/754
