### ISSUE TITLE
Tailscale client fails to connect

### ISSUE THREAD

**Issue by skerit** [juanfont/headscale#777]
**Issue description**

I've followed the guide (both a docker & regular one) but as soon as I try to connect with the tailscale client, it fails.

I've tried:

```
tailscale up --login-server https://my-external-url-behind-a-reverse-proxy
```

And also

```
tailscale up --login-server http://192.168.50.2:8082
```

But both give me this error:

```
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)
```

When I download this page with curl, I don't get any errors. Just a blank output.
There's nothing in the headscale logs.

**Context info**

- Version of headscale used: [v0.16.4](https://github.com/juanfont/headscale/releases/tag/v0.16.4) (in docker) and v0.17 alpha (not in docker)
- Version of tailscale client: 1.30.0
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version: Arch linux 
- Kernel version: 5.19.6

**Comment by Some1OnLine** [comment]
Is your issue isolated to just Arch clients? Can or have you tested connectivity with any other clients from other OS Distro's like Windows or debian/ubuntu etc..? Process of elimination.

**Comment by ripdog** [comment]
Er... silly question, but `tailscaled` IS running, right?

What's the output of `sudo systemctl status tailscaled`?

**Comment by skerit** [comment]
@ripdog Ah... Well that's not a stupid question at all.
I totally thought it was referring to the headscale server.
