### ISSUE TITLE
Ability to remove Authkeys

### ISSUE THREAD

**Issue by bharathmsd7** [juanfont/headscale#78]
Currently there are options for authkey like reusable and expiration.
It will be better to have an option for removing authkey which are reusable and expiration period is long.

**Comment by juanfont** [comment]
Implemented! Will come in 0.5.3.

**Comment by Mark3xtrm** [comment]
Hi! No option for complete removing a preauth key?

Please, this, like the ability to rename Hostnames node would be very helpful @juanfont
