### ISSUE TITLE
How to use routes? In Android for example.

### ISSUE THREAD

**Issue by thehijacker** [juanfont/headscale#806]
**Issue description**

I think this is third time I am setting up Headscale. Each previous attempts I gave up as I was unable to configure it the same way as with Wireguard directly. I have three networks at home. All three reachable on docker server. 10.0.107.0/24, 10.0.208.0/24 and 192.168.28.0/24. My goal is to reach all three when I connect to Headscale server with any client. Client should be Windows or Android.

**To Reproduce**

I started the server using Docker. Then created namespace and connected two clients to it. One is another linux server, other is my Android phone. For linux server I added "--advertise-routes=192.168.28.0/24,10.0.107.0/24,10.0.208.0/24" parameter to tailscale command. Then I enabled all three routes on Headscale and this seems to work.

But for Android client I just can not find an option to add this routes client side. So when I am connected I for example can not ping 10.0.107.0/24 devices.

Can I add them on Headscale server side?

**Context info**

Headscale version: 0.17.0-alpha2
Android client: 1.30.1
OS: Linux Ubuntu

```
root@docker-server:~# docker exec headscale headscale nodes list
ID | Hostname      | Name          | NodeKey | Namespace | IP addresses                    | Ephemeral | Last seen           | Online  | Expired
1  | Mi 10T Pro    | mi-10t-pro    | [4LfgH] | clients   | 100.64.0.1, fd7a:115c:a1e0::1   | false     | 2022-09-14 10:39:52 | offline | no
2  | web-wg-server | web-wg-server | [goF/h] | clients   | 192.168.28.1, fd7a:115c:a1e0::2 | false     | 2022-09-14 10:01:20 | offline | no
root@docker-server:~# docker exec headscale headscale machines routes list -i 1
Route | Enabled
root@docker-server:~# docker exec headscale headscale machines routes list -i 2
Route           | Enabled
10.0.107.0/24   | true
10.0.208.0/24   | true
192.168.28.0/24 | true
```

**Comment by juanfont** [comment]
Can you please raise this in Discord?
