### ISSUE TITLE
How do I know if clients are really connected directly

### ISSUE THREAD

**Issue by Zhuangkh** [juanfont/headscale#810]
**Issue description**

I have deployed one headscale server and four tailscale clients. When I use the `tailscale status` command, I find that some clients show the IP of the Headscale server even though they display `direct`.  Does this mean that the two clients are not really direct connected to each other, but are using the headscale server as a relay? 

Thanks for this wonderful project.

**Context info**

- Version of headscale used: `v0.16.4`
- Version of tailscale client:
    - windows `1.30.2`
    - debian `1.30.2`

![image](https://user-images.githubusercontent.com/30818313/190893530-53b5c763-f4f7-4f61-a3e0-a51095678a72.png)

![image](https://user-images.githubusercontent.com/30818313/190893639-d4c5ea07-9562-4e72-8f1d-b1f24a66877d.png)

**Comment by juanfont** [comment]
Can you please raise this in Discord? Thanks!

**Comment by Zhuangkh** [comment]
I finally found out that this Issue came from my mistake. My gateway uses a proxy to send the DREP request, so the final display is the IP of the direct connection to the proxy server.

FYI, I fixed it by adding the proxy rule.
