### ISSUE TITLE
help me derp

### ISSUE THREAD

**Issue by shuncon** [juanfont/headscale#813]
I don't know if this is a bug, the client test derp is successful, but pinging any of them is not successful. I also can't mstsc remote
version: v0.15.0
[root@izwz9i740hosdw6ciggmi8z ~]# headscale node list
An updated version of Headscale has been found (0.17.0-alpha2 vs. your current v0.15.0). Check it out https://github.com/juanfont/headscale/releases
ID | Name            | NodeKey | Namespace | IP addresses | Ephemeral | Last seen           | Online | Expired
3  | desktop-89nfjdc | [In20O] | default   | 10.1.0.3     | false     | 2022-09-19 03:48:12 | online | no     
5  | ishun-20201124mhj | [tp1Kr] | default   | 10.1.0.1     | false     | 2022-09-19 03:48:17 | online | no     
6  | win-37ou0egd31j | [hzd8N] | default   | 10.1.0.2     | false     | 2022-09-19 03:48:11 | online | no
D:\Users\Administrator>tailscale status
# Health check:
#     - not connected to home DERP region 999

10.1.0.1        ishun-20201124mhj      default      windows -
                desktop-89nfjdc      default      windows offline
                win-37ou0egd31j      default      windows active; relay "headscale"; offline, tx 2960 rx 0

D:\Users\Administrator>tailscale status
# Health check:
#     - not connected to home DERP region 999

10.1.0.1        ishun-20201124mhj      default      windows -
                desktop-89nfjdc      default      windows offline
                win-37ou0egd31j      default      windows active; relay "headscale"; offline, tx 3256 rx 0

**Comment by shuncon** [comment]
I have also re-registered the client and it is already down 
10.1.0.1        ishun-20201124mhj      default      windows -
                desktop-89nfjdc      default      windows offline
                win-37ou0egd31j      default      windows active; relay "headscale"; offline, tx 14948 rx 0

**Comment by juanfont** [comment]
Can you please raise this support request in Discord?

(it is possible that you dont have the UDP port for STUN open)

**Comment by seolhw** [comment]
我也遇到这个问题，请问找到解决方案了吗？ @shuncon
