### ISSUE TITLE
Unique constraint failed on namespace name when registering clients using OIDC

### ISSUE THREAD

**Issue by juanfont** [juanfont/headscale#814]
When registering multiple clients at the same time using OIDC we might break the UNIQUE constraint on namespace name:

From `oidc.go`:
```go
	namespace, err := h.GetNamespace(namespaceName)
	if errors.Is(err, ErrNamespaceNotFound) {
		namespace, err = h.CreateNamespace(namespaceName)

		if err != nil {
			log.Error().
				Err(err).
				Caller().
				Msgf("could not create new namespace '%s'", namespaceName)
```

I reckon this is a bit of a edge case in our integration tests, but seems to be there.

**Comment by kradalby** [comment]
Is this still relevant with the new integration tests?
