### ISSUE TITLE
tls_client_auth_mode Documentation Question

### ISSUE THREAD

**Issue by RUzOfuz5m** [juanfont/headscale#826]
**Problem using tls_client_auth_mode relaxed or enforced**

Everything works fine if I have `tls_client_auth_mode: disabled`. However, I'd like to set it to enforced or even relaxed but I'm not able to. The [documentation](https://github.com/juanfont/headscale/blob/main/docs/tls.md) leaves a lot of open questions and I'm curious if this is a work in progress feature or if I'm doing something wrong.

It's a fresh install of CentOS7 with headscale v0.16.4 and tailscale v1.30.1. I followed the documentation here, exposed headscale directly on port 8443. I also set the `tls_cert_path` and `tls_cert_path` configuration parameters with my LetsEncrypt cert. It's running as a headscale user (non-root).

`tailscale up --login-server https://headscale.example.com:8443 --authkey 8876....a5a39 --advertise-exit-node`

```
headscale[9381]: 2022/09/23 22:53:31 http: TLS handshake error from 11.22.33.44:31124: tls: client didn't provide a certificate
tailscaled[812]: Received error: PollNetMap: Post "https://headscale.example.com:8443/machine/5248212521bd4ae12acd64c435a35236f32acdee42a53f2a64a2a3c424bc3243/map": remote error: tls: bad certificate
```

- Version of headscale: v0.16.4
- Version of tailscale client: 1.30.1
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version: CentOS Linux release 7.9.2009 (Core)
- Kernel version: 3.10.0-1160.71.1.el7.x86_64

So, I guess the question is, Should this work or am I doing something wrong? I'd be happy to send up a PR to update the documentation once I figure this out. Thank you!

**Comment by Georift** [comment]
I'm in a similar boat, I'm admittedly new to Tailscale and would love if someone could point me in the right direction to read more about the implications of disabling `tls_client_auth_mode` and/or how to get it working when setup in `relaxed` mode.
