### ISSUE TITLE
Allow SQLite to be defined as URL / with paramters

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#828]
Use case:

I want to be able to pass PRAGMA parameters to sqlite3 so I can enable Journal WAL and busy timeout:

`file:mydbfile.db?&_journal_mode=WAL&_busy_timeout=5000`

I want to be able to do this so I can back up my database with [litestream](https://litestream.io/).

**Comment by chriswiggins** [comment]
Chiming in here, I have set up litestream and did an initial replica of our original headscale DB. The headscale DB restored correctly with our kubernetes init container, and reading the docs it looks like litestream sets the mode to WAL anyway on startup?

**Comment by chriswiggins** [comment]
Further to this,I added a new user, restarted the container and it re-pulled in the latest changes. So not sure if we need to be setting those options inside headscale?

**Comment by kev-the-dev** [comment]
If I'm understanding correctly #1348 is towards this end by introducing a `DBUrl` config param which is passed directly into the driver rather then generiting from DBHost, DBUser, etc
