### ISSUE TITLE
log.tailscale.io DNS queries

### ISSUE THREAD

**Issue by marijnv2000** [juanfont/headscale#835]
**Issue description**

I'm seeing DNS queries to log.tailscale.io with logging disabled in the headscale config.
![image](https://user-images.githubusercontent.com/17097054/192324479-ff7b35ca-1386-460b-8c33-26274d5705bb.png)

I have not checked if it's actually sending logs, and I'm unsure if this is expected, but didn't find any previous reports.

I expected setting the logtail configuration to `false` in headscale meant this would be disabled.

**To Reproduce**

Install headscale, connect a client, wait, check DNS logs

**Context info**
Headscale v0.16.4
Tailscale 1.30.2 on Windows 10
Tailscale 1.20.2 on Android 12

Logtail configuration in config.yaml file on Headscale server:
```
# Logtail configuration
# Logtail is Tailscales logging and auditing infrastructure, it allows the control panel
# to instruct tailscale nodes to log their activity to a remote server.
logtail:
  # Enable logtail for this headscales clients.
  # As there is currently no support for overriding the log server in headscale, this is
  # disabled by default. Enabling this will make your clients send logs to Tailscale Inc.
  enabled: false
```

**Comment by kradalby** [comment]
I am not familiar with the internal mechanism of the client here, it would be helpful if you tried to inspect and check what the payload is.

**Comment by marijnv2000** [comment]
I'm not sure how to go about that. I left a pcap running on Windows 10 with Tailscale running and filtered on traffic from/to the IP log.tailscale.io resolved to, but of course it's all encrypted so not particularly helpful. It does show data is continuously sent after the lookup.

log.tailscale.io resolves to 34.229.201.48, which points to an amazon ec2 instance.

![image](https://user-images.githubusercontent.com/17097054/193411239-42fa8f8d-7aa0-49b1-b21a-c5bb46d4265a.png)


I can provide more details, I'm just not sure what or how.

**Comment by huskyii** [comment]
@marijnv2000 could you try start tailscaled with environment variable `TS_NO_LOGS_NO_SUPPORT` set? and check
1. if tailscaled still try to connect to `log.tailscale.io`?
2. if taiscaled logged `You have disabled logging. Tailscale will not be able to provide support.`

**Comment by kradalby** [comment]
I will close this as it go no more new response. Reopen if it is to be investigated again.
