### ISSUE TITLE
Default isolation of namespaces via config parameter

### ISSUE THREAD

**Issue by EvilBlood** [juanfont/headscale#841]
Hello everyone, I wanted to ask if there is a possibility of isolating namespaces via the config file, e.g. 'isolate_namespaces_default = true' which could be overridden using ACL. 

Example UserA only sees his devices and UserB only sees his devices, but it is possible that a device from UserA is released for UserB via ACL. 

My purpose for this feature is: I share a server with a few friends and we all want to switch our previous VPN solution to Headscale. For this we use an oidc backend which we also use for services. Currently I have to build a separate rule for each user in the ACL so that it works. It would be nice if there was the possibility that every user could do everything within his namespace by default without me creating a rule for him.

**Comment by iSchluff** [comment]
I think the proper solution would be implementing tailscale autogroups https://tailscale.com/kb/1018/acls/#autogroups in headscale.
Then you could just express it in a simple ACL definition

**Comment by juanfont** [comment]
Please use ACLs.

**Comment by EvilBlood** [comment]
I would like to use the ACLs but unfortunately the autogroup function does not work yet. An example would be: 
{
  "action": "accept",
  "src": ["autogroup:members"],
  "dst": ["autogroup:self"],
}

**Comment by juanfont** [comment]
Can you open a dedicated issue?

**Comment by Mansarde** [comment]
> I would like to use the ACLs but unfortunately the autogroup function does not work yet. An example would be: { "action": "accept", "src": ["autogroup:members"], "dst": ["autogroup:self"], }

You have to add the port to the `dst`, like so: `"dst": ["autogroup:self:*"]`
Then every member of your tailnet should be able to access their own devices.
