### ISSUE TITLE
MagicDNS without DNS nameservers

### ISSUE THREAD

**Issue by NyaomiDEV** [juanfont/headscale#842]
**Feature request**

The [MagicDNS documentation](https://tailscale.com/kb/1081/magicdns) over at Tailscale says this:

> MagicDNS does not requires a [DNS nameserver](https://tailscale.com/kb/1054/dns/#using-dns-settings-in-the-admin-console) if running Tailscale v1.20 or later. Otherwise, your network must have at least one DNS nameserver set in the [admin console][admin]. These nameservers will receive all DNS queries not handled by MagicDNS.

I wonder if this can be applied to Headscale too, since some computers are behind DNS sinkholes (Pi-Hole) and providing a nameserver defies the purpose of setting up those sinkholes for normal browsing.

**Comment by coelho** [comment]
Relevant #822

**Comment by huskyii** [comment]
Relevant https://github.com/juanfont/headscale/issues/660

**Comment by juanfont** [comment]
This was solved in https://github.com/juanfont/headscale/pull/874
