### ISSUE TITLE
tailscale file cp , cause 502 Bad Gateway

### ISSUE THREAD

**Issue by linxd** [juanfont/headscale#845]
Env
- headscale 0.17.0-alpha4, in docker with headscale-ui
- tailscale version 1.30.2

-  headscale run in docker in centos :  5.4.210-1.el7.elrepo.x86_64
 
 when run : 
    time tailscale.exe file cp dhis.war 100.64.0.1:
got : 
   502 Bad Gateway:

real    0m21.295s
user    0m0.000s
sys     0m0.015s

**Comment by juanfont** [comment]
Hi @linxd, are you still having this issues with the latest betas?
