### ISSUE TITLE
Usage of OIDC `groups` claim

### ISSUE THREAD

**Issue by edvardvb** [juanfont/headscale#846]
**Feature request / question**

We're in the process of setting up a Headscale instance for our organization, and are using our own Azure AD to handle authorization via OIDC. 

We noticed in `oidc.go` at [line 35](https://github.com/juanfont/headscale/blob/main/oidc.go#L35) that the OIDC `groups` claim is read, but not used for anything specific. 

We were wondering what use cases you envision down the line for this claim? I saw some comments in the file related to HostInfo, what would that entail? 

For our own case, this claim would be a big help when it comes to maintaining the ACL-file as people leave and join our teams. For instance, we would love to be able to set up all members of an AD group as the source in an ACL-rule, instead of each member explicitly. This would of course require a semi-regular refresh of the ACL as well, but I think we can find a solution for that on our end 😄

**Comment by newellz2** [comment]
I submitted a pull request (#1041) that was merged that added support for authorization via the OIDC groups claim. I tested it with Keycloak and it's working well in our deployment.

**Comment by kradalby** [comment]
Gonna close this as completed

**Comment by GoodiesHQ** [comment]
Were you ever able to get this done? I created a group claim:
![image](https://github.com/juanfont/headscale/assets/4576046/9d89abb5-5feb-42a6-93d9-7cdee64a04b0)

And set the `groups` scope within the headscale configuration:
![image](https://github.com/juanfont/headscale/assets/4576046/dc4a84f8-b50c-4418-a2c7-c27c8e577ffe)

But I always get this error:
![image](https://github.com/juanfont/headscale/assets/4576046/29d1e512-23dc-4711-ad56-b3fb5469a9f1)

`AADSTS650053: The application 'TailScale' asked for scope 'groups' that doesn't exist on the resource`

**Comment by newellz2** [comment]
Yes, it works well with Keycloak. It looks like `validateOIDCCallbackParams` or `RegisterOIDC` is returning an error because your groups claim is missing.

**Comment by gentoorax** [comment]
I think "allowed_groups" is slight different to what the OP was talking about regarding use of groups in ACLs _"this claim would be a big help when it comes to maintaining the ACL-file as people leave and join our teams"_

And I agree, trying to manage a changing set of users this way is painful. Furthermore, once linked with an identity provider, new people can register via the "allowed_groups" linked back to OIDC, but then unless you manually modify the ACLs to allow them access as well, they can't actually access anything if you have ACLs in place in some scenarios.
