### ISSUE TITLE
Running with no args produces panic

### ISSUE THREAD

**Issue by rosejn** [juanfont/headscale#848]
Using the latest v0.17.0-alpha4 release if you run headscale with no command line args it produces an error rather than the help text as in previous versions:

$ ./headscale
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/juanfont/headscale/cmd/headscale/cli.init.8()
	/home/runner/work/headscale/headscale/cmd/headscale/cli/root.go:18 +0x26f

**Comment by doebi** [comment]
This is still present in the latest docker image. How frequently do you intend to update hub.docker.com?
