### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by PJTewkesbury** [juanfont/headscale#850]
**Feature request**

Version 0.15 has a release for arm  and arm64, but later versions have dropped the arm releases.

Are there any plans for arm releases to be reinstated as I wish to run headscale on my Raspberry Pi 3

Thanks,

Peter

**Comment by juanfont** [comment]
You can compile it for armhf, but at this moment we do not plan to add support for it.

**Comment by abosaad11** [comment]
> You can compile it for armhf, but at this moment we do not plan to add support for it.

Hello

Would you please point me in the right direction for compiling this for armhf?

I used

`make `

in the headscale directory, but I get this error:

```
pi@raspi:~/hs/headscale $ make
nix build
make: nix: No such file or directory
make: *** [makefile:22: build] Error 127

```

**Comment by Ondjultomte** [comment]
There are good cloud instances on arm, I hope you can reconsider.

**Comment by juanfont** [comment]
@Ondjultomte https://github.com/juanfont/headscale/releases/tag/v0.23.0-alpha3

We are now supporting arm64 and armv5, armv6 and armv7.
