### ISSUE TITLE
/home/runner/work/headscale/headscale/cmd/headscale/cli/utils.go:122

### ISSUE THREAD

**Issue by Zhuzishuo** [juanfont/headscale#885]
**Bug description**
After I install and start, all commands using headscale, except help and version, report this exception:
```
FTL ../../../home/runner/work/headscale/headscale/cmd/headscale/cli/utils.go:122 > Could not connect: context deadline exceeded error="context deadline exceeded"
```
I'm not sure if this is the problem of my system environment, but I have no idea

**To Reproduce**

**Context info**

- Version of headscale used: v0.17.0-alpha4
- Version of tailscale client: i can't find it
- OS (e.g. Linux, Mac, Cygwin, WSL, etc.) and version: Centos7.9
- Kernel version: Linux version 6.0.3-1.el7.elrepo.x86_64
- The relevant config parameters you used
- Log output

**Comment by huskyii** [comment]
checkout https://github.com/juanfont/headscale/issues/523
I think your issue have same root cause with it.
