### ISSUE TITLE
Registering new nodes with offline private key

### ISSUE THREAD

**Issue by zebhlindqvist** [juanfont/headscale#894]
**Feature request**

Would it be possible to somehow disable the headscale server's ability to register new nodes (maybe by stripping the private key) and do part of that process offline with a master key?

My thought is that this would make an attacker with access to the headscale server unable to register new nodes without also having access to the master key which would preferably be kept offline.

Does this make sense at all, or wouldn't this do much to stop an attacker with access to the headscale server anyway?

**Comment by juanfont** [comment]
Hi @zebhlindqvist, Tailscale has addressed this concern with tailnet lock https://tailscale.com/blog/tailnet-lock/

We will eventually implement it, but right now is not a priority. Headscale is meant for self-hosters - so it is reasonable to assume you trust the person in charge of hosting it :)
