### ISSUE TITLE
Use headscale domain from configuration in MapResponse

### ISSUE THREAD

**Issue by kradalby** [juanfont/headscale#91]
There is two occurrences of the string "headscale.net" in the code, I assume it isnt that important, but should we consider basing it on the user configured headscale domain?

https://github.com/juanfont/headscale/blob/5b1b40ce93ffb5f2540449e94562cb9dc98e3267/api.go#L442

https://github.com/juanfont/headscale/blob/5b1b40ce93ffb5f2540449e94562cb9dc98e3267/namespaces.go#L197

**Comment by juanfont** [comment]
I am closing this, as everything related to domains and DNS will change with MagicDNS support.
