### ISSUE TITLE
Cannot login/register with Tailscale Windows client

### ISSUE THREAD

**Issue by rstewart868** [juanfont/headscale#917]
**Issue description**

Unless I'm doing something wrong, I cannot login/register with Tailscale Windows client.

**To Reproduce**

1) Install Headscale v0.17.0-beta2 on Linux box with direct public IP
2) Configure config.yaml to set server_url to hs.domain.tld:443 and listen_addr to 0.0.0.0:443 and tls_letsencrypt_hostname to hs.domain.tld
3) Run `headscale serve` and add namespace `cso`
4) Install `tailscale-ipn-setup-1.32.2.exe` on Windows 10 21H2, visit hs.domain.tld/windows and download/execute registry file.
5) Restart tailscaled service and Tailscale GUI.
6) Click Login on Windows Tailscale client, directs browser to https://hs.domain.tld:443/register/f27329529....
7) Headscale reports Unauthorized in browser
8) Add `nodekey:` prefix to hash, registers correctly.

Seems to be an issue with latest commit to api.go regex.

**Context info**

Headscale v0.17.0-beta2 on Linux Debian 11
Windows Tailscale client 1.32.2

```
2022-11-02T09:17:24-07:00 INF The HTTP2 server was closed error=EOF
2022-11-02T09:17:24-07:00 INF ../../home/runner/work/headscale/headscale/protocol_common.go:145 > New machine not yet in the database follow_up= machine=HPSFF node_key=[8nMpU] node_key_old= noise=true
2022-11-02T09:17:24-07:00 INF ../../home/runner/work/headscale/headscale/protocol_common.go:525 > Successfully sent auth url machine=HPSFF noise=true
2022-11-02T09:17:24-07:00 WRN Invalid node key passed to registration url node_key=f27329529....
```

**Comment by rstewart868** [comment]
Maybe changing utils.go from

```
var NodePublicKeyRegex = regexp.MustCompile("nodekey:[a-fA-F0-9]+")
```

to

```
var NodePublicKeyRegex = regexp.MustCompile("(nodekey:)?[a-fA-F0-9]+")
```

I'm not set up to do a PR.

**Comment by jesset** [comment]
The same happened to me, revert headscale server from 0.17.0-beta2 to 0.17.0-alpha4

**Comment by ademasi** [comment]
This also happen from the linux client, reverted to 0.16.4 allows registering new machine.

**Comment by matt1432** [comment]
Also happened to me on android and linux, so I reverted to 0.17.0-alpha4 and it worked again.

**Comment by NetworkEngineer509** [comment]
Can confirm after updating to the latest build that I started having this issue.

**Comment by lorenzo95** [comment]
Same. Was just trying to register a device before heading to the airport lol as it always happens.
Getting unauthorized on 0.17.0-beta2 android 1.32.2. Manual registration worked.

**Comment by juanfont** [comment]
@NetworkEngineer509 @lorenzo95 can you try with the latest beta?

**Comment by arch4ngel** [comment]
Issue seems to be fixed for me @juanfont!

**Comment by edgar-vincent** [comment]
I can confirm that it seems to be fixed for me too.
