### ISSUE TITLE
Failed to set up gRPC socket | permission denied

### ISSUE THREAD

**Issue by lue30499** [juanfont/headscale#950]
**Bug description**

When running the headscale binary under the headscale user I get:
```
2022-11-11T00:41:49Z FTL ../runner/work/headscale/headscale/cmd/headscale/cli/server.go:26 > Error starting server error="failed to set up gRPC socket: listen unix /var/run/headscale.sock: bind: permission denied"
```

I am using the default port for gRPC 50443 listening on 0.0.0.0
Its my understanding that creating files in /var/run is for pid 0 processes, so root.
This error doesn't occur when run as root.

How does one run the headscale binary as a non root user?

**To Reproduce**

Follow the installation setup and systemd instructions

**System**

- Version of headscale used: 0.16.4
- OS: Linux debian

**Comment by lue30499** [comment]
I didn't read docs properly...

**Comment by camaeel** [comment]
@lue30499 Can you, please, tell me what was the solution here?

**Comment by lue30499** [comment]
@camaeel I didn't follow [this part of the docs](https://github.com/juanfont/headscale/blob/main/docs/running-headscale-linux.md#running-headscale-in-the-background-with-systemd)

Point 2 is what snagged me

**Comment by camaeel** [comment]
Thanx. I solved it in the mean time, and it was the same reason for me.
