### ISSUE TITLE
Make headscale console ANSI output optional

### ISSUE THREAD

**Issue by mhameed** [juanfont/headscale#993]
For example:

        headscale node list

produces output with ANSI escape sequences.
The command also does not determine if the output is to a terminal or a file.
For someone who is blind and uses a braille display, ANSI escape sequences is just noise.
Can we please make the addition of ANSI escape sequences optional, or have a flag to turn them off?
 
Thanks.

**Comment by kradalby** [comment]
Hi

This is already implemented and we follow the principles of https://no-color.org, it _should_ be turned off if you set `NO_COLOR` as an environment variable.
https://github.com/juanfont/headscale/blob/main/cmd/headscale/headscale.go#L31

Please let me know if this is not the case.

**Comment by mhameed** [comment]
Thanks @kradalby for reminding me of the NO_COLOR environmental variable.
