### ISSUE TITLE
What are the security risks of providing services with the http protocol on the public Internet

### ISSUE THREAD

**Issue by bbbe-me** [juanfont/headscale#994]
Hello Developer, I'm a non-technical person

I want to use headscale directly on port 8080 of the IP address on the VPS to connect to the client
It has a public ipv4 address and is globally accessible

I don't want to use a domain name or configure an SSL certificate, so I'm wondering what the security implications of doing this are
Like this: http://123.123.123.123:8080

Can an attacker gain unauthorized access to my VLAN?
Is the data transmitted in the virtual local area network safe?

**Comment by juanfont** [comment]
A very decided attacker could have a man-in-the-middle attack. Please use certificates.
